In [330]:
from radd import build, models, fit, vis
from radd.toolbox import theta

In [329]:
#!/usr/local/bin/env python
from __future__ import division
from radd import models
from radd.toolbox import theta
from radd.toolbox.messages import logger, global_logger
from lmfit import Parameters, minimize
from radd.CORE import RADDCore
from scipy.optimize import basinhopping, differential_evolution, brute

In [6]:
%cd /home/kyle/Dropbox/
%mkdir xpro_test
%cd xpro_test


/home/kyle/Dropbox/Git/pynb/ELIFE_FINAL
/home/kyle/Dropbox/xpro_test


In [331]:
build=reload(build)

In [358]:
po = m.__get_optimized_params__()

In [356]:
m.inits

{'a': 0.48758096, 'tr': 0.29223792, 'v': 1.69870371, 'xb': 1.5}

In [375]:
x = np.mean(po['v'])
xx = x*np.ones(m.ncond)

In [376]:
x

1.6921012283333334

In [378]:
x+ x*np.linspace(-.3,.3,m.ncond)

array([ 1.18447,  1.38752,  1.59058,  1.79363,  1.99668,  2.19973])

In [369]:
xx*np.arange(-.3,.3,m.ncond)

array([-0.50763, -0.50763, -0.50763, -0.50763, -0.50763, -0.50763])

In [362]:
p

{'a': array([ 0.48758,  0.48758,  0.48758,  0.48758,  0.48758,  0.48758]),
 'tr': array([ 0.29224,  0.29224,  0.29224,  0.29224,  0.29224,  0.29224]),
 'v': array([ 1.66778,  1.62578,  1.79208,  1.82898,  1.87333,  1.88919]),
 'xb': array([ 1.5,  1.5,  1.5,  1.5,  1.5,  1.5])}

In [361]:
m.opt.simulator.sim_fx(p)

array([ 0.68607,  0.7623 ,  0.40636,  0.32173,  0.21729,  0.17827,
        0.51224,  0.52324,  0.53024,  0.53824,  0.54524,  0.51724,
        0.52824,  0.53624,  0.54124,  0.54724])

In [360]:
m.avg_y

array([ 0.94754,  0.79627,  0.55578,  0.34832,  0.12668,  0.09254,
        0.52486,  0.53896,  0.54297,  0.54493,  0.54529,  0.54026,
        0.54454,  0.5447 ,  0.54518,  0.54532])

In [359]:

m.opt.simulator.sim_fx(po)

array([ 0.95378,  0.82533,  0.57803,  0.35054,  0.12125,  0.09484,
        0.50524,  0.51724,  0.52624,  0.53424,  0.54324,  0.52324,
        0.53224,  0.53924,  0.54424,  0.54624])

In [352]:
m = build.Model(data=prodf_store.prodata, kind='xpro', dynamic='hyp', depends_on={'v':'pGo'}, tb=.550)
m.make_optimizer(multiopt=True)
m.opt.make_simulator()
p, fmin = m.opt.multivariate_basinhopping(m.inits)
#m.optimize(tol=1.e-10, ntrials=10000, maxfev=5000)

basinhopping step 0: f 1.43671
basinhopping step 1: f 1.43671 trial_f 1.66183 accepted 0  lowest_f 1.43671
basinhopping step 2: f 1.32835 trial_f 1.32835 accepted 1  lowest_f 1.32835
found new global minimum on step 2 with function value 1.32835
basinhopping step 3: f 1.51511 trial_f 1.51511 accepted 1  lowest_f 1.32835
basinhopping step 4: f 1.21783 trial_f 1.21783 accepted 1  lowest_f 1.21783
found new global minimum on step 4 with function value 1.21783
basinhopping step 5: f 1.25976 trial_f 1.25976 accepted 1  lowest_f 1.21783
basinhopping step 6: f 1.09284 trial_f 1.09284 accepted 1  lowest_f 1.09284
found new global minimum on step 6 with function value 1.09284
basinhopping step 7: f 1.00372 trial_f 1.00372 accepted 1  lowest_f 1.00372
found new global minimum on step 7 with function value 1.00372
basinhopping step 8: f 1.07998 trial_f 1.07998 accepted 1  lowest_f 1.00372
basinhopping step 9: f 0.726265 trial_f 0.726265 accepted 1  lowest_f 0.726265
found new global minimum on st

In [339]:
m.inits

{'a': 0.4433013, 'sso': 0.1999348, 'ssv': 3.018744, 'tr': 0.2171978, 'v': 1.29}

In [348]:
m.avg_y=m.avg_y.flatten()

In [350]:
m = build.Model(data=redf_store.redata, kind='xiact', dynamic='hyp', depends_on={'v':'Cond'})
m.optimize(tol=1.e-10, ntrials=10000, maxfev=5000)

In [271]:
wts = array([1.7453, 1.0, 0.8537, 0.9899, 2.2004, 2.2004, 0.2066, 0.3122, 0.5341, 1.8537, 3.1526, 0.0995, 0.2675, 0.2767, 0.9439, 0.9439])

In [273]:
p = {'a': 0.487581,'xb':1.840808, 'tr':.29223, 'v':array([1.39423800,1.53535562,1.65557698,1.75515234,1.88985329,1.92243114])}
m.opt.simulator.wts =wts
m.opt.simulator.ncond = 6

In [275]:

simfx=m.opt.simulator.sim_fx


In [317]:
m.y+m.opt.simulator.__cost_fx__(p)

array([ 0.9496 ,  0.82353,  0.58885,  0.35974,  0.12396,  0.08177,
        0.51216,  0.57756,  0.56847,  0.54969,  0.54591,  0.65948,
        0.58766,  0.56445,  0.54723,  0.54628])