In [71]:
from radd import build, vis
#m=build.Model(data=redata, kind='radd')
#m.inits = p
#x = m.simulate(analyze=False)
#sim = m.simulator.sim_fx

In [4]:
trs=np.arange(90,160, 20)
l = [np.ones(trx) for trx in trs]

In [9]:
trs

array([ 90, 110, 130, 150])

In [ ]:
%mv

In [ ]:
Pg = 0.5*(1 + p['v']*self.dx/self.si)
Tg = np.ceil((self.tb-p['tr'])/self.dt).astype(int)
t = np.cumsum([self.dt]*Tg.max())
np.ones()
xtb = self.temporal_dynamics(p, t)
self.xtb = np.vstack([np.append(np.ones(diff[i]), xtb[i][:tg]) for tr in Tg])
diff = [trs.max()-trx for trx in trs]
[np.append(np.ones(diff[i]), [.0005]*trs[i]) for i in range(4)]

In [11]:
t

array([ 0.0005,  0.001 ,  0.0015,  0.002 ,  0.0025,  0.003 ,  0.0035,
        0.004 ,  0.0045,  0.005 ,  0.0055,  0.006 ,  0.0065,  0.007 ,
        0.0075,  0.008 ,  0.0085,  0.009 ,  0.0095,  0.01  ,  0.0105,
        0.011 ,  0.0115,  0.012 ,  0.0125,  0.013 ,  0.0135,  0.014 ,
        0.0145,  0.015 ,  0.0155,  0.016 ,  0.0165,  0.017 ,  0.0175,
        0.018 ,  0.0185,  0.019 ,  0.0195,  0.02  ,  0.0205,  0.021 ,
        0.0215,  0.022 ,  0.0225,  0.023 ,  0.0235,  0.024 ,  0.0245,
        0.025 ,  0.0255,  0.026 ,  0.0265,  0.027 ,  0.0275,  0.028 ,
        0.0285,  0.029 ,  0.0295,  0.03  ,  0.0305,  0.031 ,  0.0315,
        0.032 ,  0.0325,  0.033 ,  0.0335,  0.034 ,  0.0345,  0.035 ,
        0.0355,  0.036 ,  0.0365,  0.037 ,  0.0375,  0.038 ,  0.0385,
        0.039 ,  0.0395,  0.04  ,  0.0405,  0.041 ,  0.0415,  0.042 ,
        0.0425,  0.043 ,  0.0435,  0.044 ,  0.0445,  0.045 ])

In [408]:
a={'a': array([ 0.4367 ,  0.45355]), 'z': 0.15753848075714916, 'v': array([ 0.96655,  0.96655]), 'xb': array([ 1.49384,  1.49384]), 'a_bsl': 0.43669782451423506, 'ssv': -0.91313037558732457, 'tr': array([ 0.30363,  0.30363]), 'a_pnl': 0.45355059204993331}
v={'a': array([ 0.44393,  0.44393]), 'v_pnl': 0.91899274888279592, 'z': 0.16643841595622483, 'v': array([ 0.97772,  0.91899]), 'xb': array([ 1.42516,  1.42516]), 'ssv': -0.94888344899188182, 'tr': array([ 0.30485,  0.30485]), 'v_bsl': 0.97772273133301812}
tr={'a': array([ 0.44473,  0.44473]), 'tr_pnl': 0.30956358881279894, 'z': 0.15188210098850022, 'tr_bsl': 0.29872925160858826, 'v': array([ 0.98759,  0.98759]), 'xb': array([ 1.36793,  1.36793]), 'ssv': -0.88710169697796726, 'tr': array([ 0.29873,  0.30956], dtype=np.float32)}


In [94]:
sc.append(m.simulate(analyze=True).reshape(2,16)[:, 1:6])

array([ 0.9883 ,  0.9978 ,  0.9896 ,  0.9518 ,  0.4376 ,  0.0772 ,
        0.50872,  0.53172,  0.55072,  0.57172,  0.60472,  0.50072,
        0.52372,  0.54172,  0.56072,  0.58872,  0.976  ,  0.999  ,
        0.9928 ,  0.9658 ,  0.5844 ,  0.12   ,  0.51891,  0.54191,
        0.56091,  0.58191,  0.61291,  0.51091,  0.53491,  0.54991,
        0.56891,  0.59791])

In [95]:
models = ['a', 'v', 'tr']
params= [a, v, tr]
sc=[array([0.9966, 0.9865, 0.9038, 0.5087, 0.1036],[0.9991, 0.9907, 0.9329, 0.5987, 0.1819])]
gos=[]

for i, mx in enumerate(models):
      m=build.Model(data=redata, kind='xradd', depends_on={mx:'Cond'})
      m.inits = params[i]
      x = m.simulate(analyze=False)
      sc.append(m.simulate(analyze=True).reshape(2,16)[:, 1:6])
      sim=m.simulator.sim_fx
      gort, ssrt = get_rts(m.simulator, x, m.inits)
      gos.append(gort)
sc = np.asarray(sc)


In [103]:
sc[0] = np.vstack([sc[0], [0.9991, 0.9907, 0.9329, 0.5987, 0.1819]])

In [14]:
gort, ssrt = get_rts(m.simulator, x, m.inits)

In [138]:
def get_rts(sim, DVg, p):

      nss = m.simulator.nss; prob = m.simulator.prob
      ssd = m.simulator.ssd; tb = m.simulator.tb
      nc = m.simulator.ncond; #nssd=m.simulator.nssd
      #DVg, DVs = DV
      
      gdec = m.simulator.resp_up(DVg, p['a'])
      gort = m.simulator.RT(p['tr'], gdec)
      #sdec = m.simulator.resp_lo(DVs)
      #ssrt = m.simulator.RT(ssd, sdec)
      
      return gort#, ssrt

In [239]:
gort2.shape

(2, 10000, 10000)

In [16]:
gdf = pd.DataFrame(gort.T, columns=['bsl', 'pnl'])
gdf = gdf[gdf<m.tb]

In [90]:
sdf = pd.DataFrame(np.nanmean(x[1], axis=1).T, columns=['bsl', 'pnl'])

In [111]:
pn = [scx[1] for scx in sc]
bs = [scx[0] for scx in sc]

In [ ]:
m.data.groupby('HL')

In [ ]:
def plot_pred_pdf(c=['Green','Blue','Red'], sdf=None, gos=None, errs=None, l=[]):

      sns.set(style='white', font_scale=1.4)
      bsl = redata.query('response==1&acc==1&Cond=="bsl"').rt
      pnl = redata.query('response==1&acc==1&Cond=="pnl"').rt
      
      sns.kdeplot(bsl, color='k', cumulative=True, linewidth=3.5, ax=ax1, bw=.01)
      sns.kdeplot(pnl, color='k', cumulative=True, linewidth=3.5, ax=ax2, bw=.01)
      
      for 

In [457]:
def plot_pred_pdf(c=['Green','Blue','Red'], crt_list=None, ert_list=None, l=[]):

      sns.set(style='white', font_scale=1.4)
      #bsl = redata.query('response==1&acc==1&Cond=="bsl"').rt
      #bsle = redata.query('response==1&acc==0&Cond=="bsl"').rt
      
      #pnl = redata.query('response==1&acc==1&Cond=="pnl"').rt
      #pnle = redata.query('response==1&acc==0&Cond=="pnl"').rt
      
      y = array([[ 0.94125,  0.99668,  0.98653,  0.90386,  0.50872,  0.10362,
               0.51461,  0.54372,  0.56341,  0.58263,  0.61047,  0.50345,
               0.53184,  0.54934,  0.56775,  0.59466],
             [ 0.92624,  0.99918,  0.9908 ,  0.93297,  0.59871,  0.18197,
               0.52012,  0.55012,  0.57034,  0.59051,  0.61803,  0.51074,
               0.53919,  0.55427,  0.5731 ,  0.60007]])
      
      cq = y[:, 6:11]
      eq = y[:, 11:]
      bw=.004
      
      bslc=analyze.kde_fit_quantiles(cq[0], bw=bw)
      pnlc=analyze.kde_fit_quantiles(cq[1], bw=bw)      
      sns.kdeplot(bslc, color='k', cumulative=True, linewidth=3.5, ax=ax1, bw=bw, label='Baseline')
      sns.kdeplot(pnlc, color='k', cumulative=True, linewidth=3.5, ax=ax4, bw=bw, label='Caution')
      
      bsle= analyze.kde_fit_quantiles(eq[0], bw=bw)
      pnle= analyze.kde_fit_quantiles(eq[1], bw=bw)
      sns.kdeplot(bsle, color='k', cumulative=True, linewidth=3.5, ax=ax2, bw=bw)
      sns.kdeplot(pnle, color='k', cumulative=True, linewidth=3.5, ax=ax5, bw=bw)
      
      l=['Boundary', 'Drift', 'Onset']
      for i, crt in enumerate(crt_list):
            bsl_rt = analyze.kde_fit_quantiles(crt[0], bw=bw)
            pnl_rt = analyze.kde_fit_quantiles(crt[1], bw=bw)
            sns.kdeplot(bsl_rt, color=c[i], bw=bw, ax=ax1, linestyle='--', linewidth=3, cumulative=True,  alpha=.9, label=l[i])
            sns.kdeplot(pnl_rt, color=c[i], bw=bw, ax=ax4, linestyle='--', linewidth=3, cumulative=True,  alpha=.9, label=l[i])

      for i, ert in enumerate(ert_list):
            bsl_ert = analyze.kde_fit_quantiles(ert[0], bw=bw)
            pnl_ert = analyze.kde_fit_quantiles(ert[1], bw=bw)
            sns.kdeplot(bsl_ert, color=c[i], bw=bw, ax=ax2, linestyle='--', linewidth=3, cumulative=True,  alpha=.9)
            sns.kdeplot(pnl_ert, color=c[i], bw=bw, ax=ax5,  linestyle='--', linewidth=3, cumulative=True, alpha=.9)

      for ax in [ax1, ax2, ax4, ax5]:
            ax.set_xlim(.46,.64)
            xx=ax.get_xticks()[::2]
            ax.set_xticks(xx)
            ax.set_xticklabels([int(xxx*1000) for xxx in xx])
            ax.set_xlabel('RT (ms)')
      plt.tight_layout()
      sns.despine()

In [133]:
c = ['k', "#e74c3c", '#27ae60', '#4168B7']

In [297]:
ert.shape

(2, 5, 5000)

In [337]:
def get_rts(sim, DV, p):

      nss = m.simulator.nss; prob = m.simulator.prob
      ssd = m.simulator.ssd; tb = m.simulator.tb
      nc = m.simulator.ncond; nssd=m.simulator.nssd
      
      DVg, DVs = DV
      
      gdec = m.simulator.resp_up(DVg, p['a'])
      gort = m.simulator.RT(p['tr'], gdec)
      sdec = m.simulator.resp_lo(DVs)
      ssrt = m.simulator.RT(ssd, sdec)
      
      errs = gort[:, :5000][:,None]*np.ones_like(ssrt)
      
      ert = np.nanmean(np.where(errs<ssrt, 1, np.nan)*errs, axis=1)
      crt = np.where(gort<tb, 1, np.nan)*gort
      return crt, ert

In [400]:
v={'a': array([ 0.44379,  0.44379]), 'v_pnl': 0.92610080235444836, 'z': 0.15747169927370966, 'v': array([ 0.98682,  0.9261 ], dtype=np.float32), 'xb': array([ 1.6832,  1.6832]), 'ssv': -0.90937114625950954, 'tr': array([ 0.30594,  0.30594]), 'v_bsl': 0.98681687638702054}

In [452]:
models = ['a', 'v', 'tr']
params= [a, v, tr]
mlist=[]

sc, cq, eq = [], [], []
for i, mx in enumerate(models):
      m=build.Model(data=redata, kind='xradd', depends_on={mx:'Cond'})
      mlist.append(m)
y = m.avg_y
wts=m.avg_wts
sc.append(y[:, 1:6])

In [453]:
gos=[]
errs=[]

for i, mx in enumerate(models):
      m=mlist[i]
      m.inits = params[i]
      m.fitparams['ntrials']=2000
      yhat = m.simulate(analyze=True).reshape(2,16)
      
      sc.append(yhat[:, 1:6])
      cq.append(y[:, 6:11] + (y[:,6:11] - yhat[:,6:11])*wts.reshape(2,16)[:, 6:11])
      eq.append(y[:, 11:] + (y[:, 11:] - yhat[:,11:])*wts.reshape(2,16)[:, 11:])
      
      #cq.append(m.simulate(analyze=True).reshape(2,16)[:, 1:6])
      #sim=m.simulator.sim_fx
      #gort, ert = get_rts(m.simulator, x, m.inits)
      #gdf = pd.DataFrame(gort.T, columns=['bsl', 'pnl'])
      #edf = pd.DataFrame(ert.T, columns=['bsl', 'pnl'])
      #gos.append(gdf)
      #errs.append(edf)

sc = np.asarray(sc)
cq = np.asarray(cq)
eq = np.asarray(eq)

In [459]:
f, axes = plt.subplots(2, 3, figsize=(13,8))
axes=np.array(axes).flatten()
ax1, ax2, ax3, ax4, ax5, ax6 = axes[0], axes[1], axes[2], axes[3], axes[4], axes[5]

plot_pred_pdf(c=["#e74c3c", '#27ae60', '#4168B7'], crt_list=cq, ert_list=eq, l=models)
ax2.set_title('Baseline')
ax5.set_title('Caution')
plt.subplots_adjust(hspace=.30)

bs = [scx[0] for scx in sc]
pn = [scx[1] for scx in sc]

condlist=[bs, pn]
for i, axx in enumerate([ax3, ax6]):
      lines=condlist[i]
      vis.scurves(lines=lines, labels=['Data', 'Bound', 'Drift', 'Onset'], linestyles=['-', '--', '--', '--'], colors=c, kind='radd', ax=axx)
plt.savefig('reactive_models_comparison_weighted_b004.svg', rasterized=True)
plt.savefig('reactive_models_comparison_weighted_b004.png', rasterized=True)

In [414]:
eq

array([[[ 0.50763,  0.53263,  0.55163,  0.57263,  0.60363],
        [ 0.52163,  0.54663,  0.56563,  0.58463,  0.61363]],

       [[ 0.51294,  0.53794,  0.55494,  0.57494,  0.60194],
        [ 0.51994,  0.54494,  0.56394,  0.58494,  0.61294]],

       [[ 0.51073,  0.53773,  0.55773,  0.57873,  0.60873],
        [ 0.52156,  0.54656,  0.56656,  0.58756,  0.61756]]])

In [419]:
y[:, 6:11] + (y[:,6:11] - eq[0])*wts.reshape(2,16)[:, 6:11]

array([[ 0.51463,  0.55822,  0.56346,  0.59197,  0.61693],
       [ 0.52012,  0.55469,  0.57036,  0.596  ,  0.62219]])

In [422]:
y[:,6:11]

array([[ 0.51461,  0.54372,  0.56341,  0.58263,  0.61047],
       [ 0.52012,  0.55012,  0.57034,  0.59051,  0.61803]])

In [420]:
eq[0]

array([[ 0.50763,  0.53263,  0.55163,  0.57263,  0.60363],
       [ 0.52163,  0.54663,  0.56563,  0.58463,  0.61363]])

In [ ]:
pn = [scx[1] for scx in sc]
bs = [scx[0] for scx in sc]

condlist=[bs, pn]
for i, axx in enumerate([ax3, ax5]):
      lines=condlist[i]
      vis.scurves(lines=lines, labels=['Data', 'Bound', 'Drift', 'Onset'], linestyles=['-', '--', '--', '--'], colors=c, kind='radd', ax=axx)

#plt.savefig('Reactive_BSL_PNL_ModelFits.svg', rasterized=True)
#plt.savefig('Reactive_BSL_PNL_ModelFits.png', dpi=400)

In [ ]:
      xrt = np.where(errs<ssrt, 1, np.nan)*errs

In [168]:
wts = array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0038, 1.3072, 0.0044, 0.9340, 0.9436, 0.9436, 0.2193, 0.3471, 0.3615, 0.3382, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0038, 1.3072, 0.0044, 0.9340, 0.9436, 0.9436, 0.2193, 0.3471, 0.3615, 0.3382])
y = array([0.9412, 0.9966, 0.9865, 0.9038, 0.5087, 0.1036, 0.5146, 0.5437, 0.5634, 0.5826, 0.6104, 0.5034, 0.5318, 0.5493, 0.5677, 0.5946, 0.9262, 0.9991, 0.9907, 0.9329, 0.5987, 0.1819, 0.5201, 0.5501, 0.5703, 0.5905, 0.6180, 0.5107, 0.5391, 0.5542, 0.5731, 0.6000])


In [190]:
tr_hat = array([0.9514, 0.9974, 0.9872, 0.9388, 0.4834, 0.1292, 0.5173, 0.5463, 0.5673, 0.5883, 0.6193, 0.5093, 0.5373, 0.5543, 0.5753, 0.6043, 0.9324, 0.9988, 0.9916, 0.9572, 0.6052, 0.17, 0.5269, 0.5539, 0.5749, 0.5979, 0.6269, 0.5189, 0.5449, 0.5619, 0.5829, 0.6119])

trchi = np.sum(((y-tr_hat)**2)*wts)

In [175]:
a_hat = array([0.9562, 0.998, 0.9874, 0.94, 0.5006, 0.1288, 0.5166, 0.5436, 0.5646, 0.5876, 0.6206, 0.5096, 0.5346, 0.5536, 0.5726, 0.6046, 0.9247, 0.9988, 0.993, 0.9584, 0.5786, 0.1734, 0.5296, 0.5586, 0.5776, 0.5986, 0.6266, 0.5196, 0.5466, 0.5656, 0.5846, 0.6136])
achi = np.sum(((y-a_hat)**2)*wts)

In [178]:
len(v_hat)

32

In [192]:
trchi

0.0039732376499999975

In [169]:
vhat = array([0.9578, 0.9978, 0.987, 0.9376, 0.4868, 0.1274, 0.5138, 0.5428, 0.5648, 0.5878, 0.6178, 0.5108, 0.5338, 0.5508, 0.5718, 0.6008, 0.9159, 0.998, 0.9894, 0.9524, 0.5848, 0.1926, 0.5258, 0.5528, 0.5758, 0.5968, 0.6278, 0.5138, 0.5428, 0.5628, 0.5838, 0.6118])
vchi = np.sum(((y-v_hat)**2)*wts)

In [193]:
tr_chi = 0.0039732376499999975
v_chi = 0.0036767844039999982
a_chi=0.0040501057079999955

In [182]:
def assess_fit(finfo, chi, ncond=6):

      chisqr = chi #(finfo['chi']**2).sum()
      ndata = 32
      nvarys= ncond
      nfree = ndata - nvarys
      rchi = chisqr / nfree

      log_likelihood = ndata * np.log(rchi)
      aic = log_likelihood + 2 * nvarys
      bic = log_likelihood + np.log(ndata) * nvarys

      return aic, bic


In [184]:
assess_fit('x', v_chi)
v_aic = 

(-271.64202400231221, -262.84760858551385)

In [185]:
assess_fit('x', a_chi)

(-268.54748273552161, -259.75306731872325)

In [194]:
assess_fit('x', tr_chi)

(-269.16065682241043, -260.36624140561207)

In [187]:
tr_chi = 

0.004553747559999996

In [172]:
yhat = array([0.9514, 0.9974, 0.9872, 0.9388, 0.4834, 0.1292, 0.5173, 0.5463, 0.5673, 0.5883, 0.6193, 0.5093, 0.5373, 0.5543, 0.5753, 0.6043, 0.9324, 0.9988, 0.9916, 0.9572, 0.6052, 0.17, 0.5269, 0.5539, 0.5749, 0.5979, 0.6269, 0.5189, 0.5449, 0.5619, 0.5829, 0.6119])
tr_chi=

0.0045537475599999964

In [167]:
v_chi = 0.0036767844039999982

0.0036767844039999982

In [176]:
a_chi=0.0040501057079999955

0.0040501057079999955

In [173]:
vchi

0.0036767844039999982

In [ ]:
chi: 0.00001152
      0.00001499

In [492]:
xprov={'a': array([ 0.48672,  0.48672,  0.48672,  0.48672,  0.48672,  0.48672]), 'v_0': 1.4204744923605306, 'xb': array([ 1.86673,  1.86673,  1.86673,  1.86673,  1.86673,  1.86673]), 'v': array([ 1.42047,  1.54611,  1.67993,  1.75729,  1.87396,  1.89252]), 'tr': array([ 0.29334,  0.29334,  0.29334,  0.29334,  0.29334,  0.29334]), 'v_100': 1.8925194341059219, 'v_60': 1.7572925581377903, 'v_80': 1.8739583821515711, 'v_20': 1.5461146129935177, 'v_40': 1.6799320687772294}
#xproa={'a': array([ 0.54429,  0.46187,  0.45809,  0.37324,  0.3401 ,  0.33121]), 'a_20': 0.46186670201561836, 'a_0': 0.5442868037421783, 'a_100': 0.33120847422722277, 'tr': array([ 0.15493,  0.15493,  0.15493,  0.15493,  0.15493,  0.15493]), 'a_80': 0.34009512359516814, 'xb': array([ 0.87853,  0.87853,  0.87853,  0.87853,  0.87853,  0.87853]), 'a_60': 0.37323925179971412, 'a_40': 0.45809072103682474, 'v': array([ 0.94717,  0.94717,  0.94717,  0.94717,  0.94717,  0.94717])}
xprotr={'tr_80': 0.28706936544590755, 'a': array([ 0.33093,  0.33093,  0.33093,  0.33093,  0.33093,  0.33093]), 'xb': array([ 1.39482,  1.39482,  1.39482,  1.39482,  1.39482,  1.39482]), 'tr_0': 0.3629863222975761, 'tr': array([ 0.36299,  0.34382,  0.32439,  0.30814,  0.28707,  0.28049]), 'tr_60': 0.30813672200937137, 'tr_20': 0.34381508967070357, 'tr_40': 0.32439120823028805, 'v': array([ 1.35891,  1.35891,  1.35891,  1.35891,  1.35891,  1.35891]), 'tr_100': 0.28048943734544829}
xproa={'a':array([0.58689325,0.54086615 ,0.50483462 ,0.47312626 ,0.43397831 ,0.42288989]),
'xb': 1.970817, 'tr': 0.284143, 'v':  1.630117}

provtr={'tr_80': 0.33951513531300465, 'a': array([ 0.34218,  0.34218,  0.34218,  0.34218,  0.34218,  0.34218]), 'v': array([ 1.44044,  1.27013,  1.59645,  1.27281,  1.82057,  1.36874]), 'v_0': 1.4404377929707215, 'xb': array([ 1.,  1.,  1.,  1.,  1.,  1.]), 'tr_0': 0.35675266724138277, 'tr': array([ 0.35675,  0.31196,  0.33909,  0.26999,  0.33952,  0.252  ]), 'tr_60': 0.2699869312165879, 'tr_20': 0.31195868332328336, 'v_100': 1.3687399223750985, 'tr_40': 0.33908665087267442, 'v_60': 1.2728088593327467, 'tr_100': 0.25199784169629791, 'v_80': 1.8205659366828479, 'v_20': 1.2701251276032504, 'v_40': 1.5964496804953119}


In [515]:
def plot_pro_rts(c=['Green','Blue','Red'], sdf=None, hi_list=None, lo_list=None, l=[]):


      sns.set(style='white', font_scale=1.4)   
      y=array([ 0.94443,  0.79361,  0.55094,  0.343  ,  0.12147,  0.0856 ,
        0.51469,  0.53463,  0.5414 ,  0.54469,  0.54527,  0.53737,
        0.54404,  0.5447 ,  0.54518,  0.54532])
      

      bw=.006
      
      hi=analyze.kde_fit_quantiles(y[6:11], bw=bw)
      lo=analyze.kde_fit_quantiles(y[11:], bw=bw)      
      sns.kdeplot(hi, color='k', linewidth=3.5, ax=ax1, bw=bw, label='High')
      sns.kdeplot(lo, color='k', linewidth=3.5, ax=ax2, bw=bw, label="Low")
      
      for i, high in enumerate(hi_list):
            h_rt = analyze.kde_fit_quantiles(high, bw=bw)
            sns.kdeplot(h_rt, color=c[i], bw=bw, ax=ax1, linestyle='--', linewidth=3, alpha=.9, label=l[i])
            
      for i, low in enumerate(lo_list):
            l_ert = analyze.kde_fit_quantiles(low, bw=bw)
            sns.kdeplot(l_ert, color=c[i], bw=bw, ax=ax2, linestyle='--', linewidth=3, alpha=.9)

      for ax in [ax1, ax2]:
            ax.set_xlim(.450,.600)
            xx=ax.get_xticks()[::2]
            ax.set_xticks(xx)
            ax.set_xticklabels([int(xxx*1000) for xxx in xx])
            ax.set_xlabel('RT (ms)')
      plt.tight_layout()
      sns.despine()

In [ ]:
minits = [xproa, xprov, xprotr, provtr]
mkind = ['xpro']*3+['pro']
models = ['a', 'v', 'tr', 'vtr']


def get_rts(sim, DVg, p):

      nss = m.simulator.nss; prob = m.simulator.prob
      ssd = m.simulator.ssd; tb = m.simulator.tb
      nc = m.simulator.ncond; #nssd=m.simulator.nssd
      #DVg, DVs = DV
      
      gdec = m.simulator.resp_up(DVg, p['a'])
      gort = m.simulator.RT(p['tr'], gdec)
      #sdec = m.simulator.resp_lo(DVs)
      #ssrt = m.simulator.RT(ssd, sdec)
      
      return gort#, ssrt

In [462]:
m.avg_y

array([ 0.94443,  0.79361,  0.55094,  0.343  ,  0.12147,  0.0856 ,
        0.51469,  0.53463,  0.5414 ,  0.54469,  0.54527,  0.53737,
        0.54404,  0.5447 ,  0.54518,  0.54532])

In [493]:

minits = [xproa, xprov, xprotr, provtr]
mkind = ['xpro']*3+['pro']
models = ['a', 'v', 'tr', 'vtr']
mlist=[]
for i, dep in enumerate(models):
      if dep == 'vtr':
            depends_on = {'v':'pGo', 'tr':'pGo'}
      else:
            depends_on = {dep: 'pGo'}
      m=build.Model(data=prodf_store.prodata, kind=mkind[i], depends_on=depends_on)   
      mlist.append(m)

In [494]:
sc, cq, eq = [], [], []      
sc.append(y[:6])
for i, dep in enumerate(models):
      
      m=mlist[i]
      wts=m.avg_wts
      y=m.avg_y
      m.inits = minits[i]
      yhat = m.simulate(analyze=True)
      sc.append(yhat[:6])
      cq.append(yhat[6:11])# + (y[6:11] - yhat[6:11])*wts[6:11])
      eq.append(yhat[11:])# + (y[11:] - yhat[11:])*wts[11:])

sc = np.asarray(sc)

array([ 0.48458,  0.5318 ,  0.5788 ,  0.55813,  0.54336])

In [470]:
purples

['#9B59B6', '#8E44AD', '#663399', '#674172']

In [472]:
eq

[array([ 0.53992,  0.5518 ,  0.55208,  0.54799,  0.54513]),
 array([ 0.53826,  0.54782,  0.54767,  0.546  ,  0.54497]),
 array([ 0.53852,  0.54824,  0.54859,  0.54661,  0.54503]),
 array([ 0.53854,  0.54817,  0.54879,  0.54612,  0.54501])]

In [516]:
f, axes = plt.subplots(1,3, figsize=(13,4))
axes=np.array(axes).flatten()
ax1, ax2, ax3 = axes[0], axes[1], axes[2]
models = ['Bound', 'Drift', 'Onset', 'Drift+Onset']
c=["#e74c3c", '#27ae60', '#4168B7', '#8E44AD']
plot_pro_rts(c=c, hi_list=cq, lo_list=eq, l=models)
c=['k'] + c
models = ['Data'] + models
vis.scurves(lines=sc, labels=models, linestyles=['-', '--', '--', '--', '--'], colors=c, kind='pro', ax=ax3)
plt.savefig('proactive_models_comparison_pdf.svg', rasterized=True)
plt.savefig('proactive_models_comparison_pdf.png', dpi=600)