In [676]:
from radd import build, fit, vis, models, utils, CORE
from numpy import array
img = prodf_store.proimg
from scipy.stats.mstats import mquantiles as mq
beh = prodf_store.prodata

In [603]:
build=reload(build)

In [864]:
fit.Simulator(m)

AttributeError: 'Simulator' object has no attribute '__simulate_functions__'

In [865]:

wts = np.hstack((presponse.values.T * sq_ratio.T).T)

In [637]:
np.sort(presponse)

array([ 0.11554,  0.74736,  0.96251])

In [686]:
CORE.rt_quantiles(d)

array([ 518.34884,  538.03516,  538.466  ,  539.03904,  539.71856,
        520.31172,  537.82144,  538.263  ,  538.85052,  539.58168])

In [685]:
d = data[(data.idx==47) & (data.response==1)]
rrr = []
for c, df in d.groupby('HML'):
      rt = df.rt.values
      rrr.append(mq(rt, prob=prob))

In [694]:
for i in m.split:
      if i not in d[m.split].unique():
            rrr.append(array([np.nan]*len(prob)))

In [857]:
m = build.Model(data=prodf_store.prodata, fit_on='average', kind='xpro', depends_on={'v':'pGo'}, split='HL')


      Model is prepared to fit on average xpro data, allowing
      Drift-Rate to vary across levels of pGo (0, 20, 40, 60, 80, 100) 

      It'll probably work this time 


In [858]:
m.optimize()

AttributeError: 'Simulator' object has no attribute '__init_analyze_functions__'

In [846]:

r1 = m.avg_y[5:10]
r2 = m.avg_y[10:15]
r3 = m.avg_y[15:]

In [847]:
plt.plot(r1)
plt.plot(r2)
plt.plot(r3)

In [832]:
m.fits

array([ 0.93,  0.85,  0.41,  0.03,  0.03,  0.52,  0.54,  0.55,  0.56,
        0.56,  0.52,  0.54,  0.55,  0.57,  0.56,  0.53,  0.55,  0.55,
        0.54,  0.54])

In [848]:
vis.plot_fits(m.avg_y, m.fits, bw=.00009, kind='pro')

In [546]:
ss.dynamic='hyp'
m.inits['xb']=.1
dvg = ss.simulate_pro(p=m.inits, analyze=False)

#ss.xtb

In [838]:
gpal(4)

array([[ 0.4 ,  0.72,  0.56,  1.  ],
       [ 0.29,  0.69,  0.55,  1.  ],
       [ 0.19,  0.66,  0.53,  1.  ],
       [ 0.09,  0.63,  0.52,  1.  ]])

In [547]:
for i in dvg[1, :5, :]:
      plt.plot(i)

In [525]:
nss = ss.nss; prob = ss.prob
ssd = ss.ssd; tb = ss.tb
ncond = ss.ncond

dvg = ss.simulate_pro(p=m.inits, analyze=False)

gdec = ss.resp_up(dvg, p['a'])
rt = ss.RT(p['tr'], gdec)

hi = np.hstack(rt[3:])
lo = np.hstack(rt[:3])
qrt = np.hstack(ss.fRTQ(zip([hi, lo],[tb]*2)))
# Get response and stop accuracy information
nogo = 1-np.mean(np.where(rt<tb, 1, 0), axis=1)

In [526]:
rt

array([[    nan,     nan,  0.559 , ...,     nan,     nan,     nan],
       [ 0.5595,     nan,     nan, ...,  0.5595,  0.5595,     nan],
       [ 0.5595,     nan,     nan, ...,  0.559 ,  0.5595,  0.5545],
       [    nan,  0.557 ,  0.5565, ...,  0.5565,  0.5565,  0.559 ],
       [ 0.558 ,  0.559 ,  0.559 , ...,  0.5575,     nan,  0.558 ],
       [ 0.5585,  0.554 ,  0.5565, ...,  0.553 ,  0.557 ,  0.5535]])

In [363]:
Pg = 0.5*(1 + p['v']*ss.dx/ss.si)
Tg = np.ceil((ss.tb-p['tr'])/ss.dt).astype(int)
t = np.cumsum(np.ones(Tg.max()))[::-1]

In [368]:
ss.xtb = map((lambda x: x[0]*1/(1+(x[1]*t))), zip(p['a'], p['xb']))

In [356]:
nogo

array([ 0.02581,  0.0084 ,  0.006  ,  0.0006 ,  0.0006 ,  0.     ])

In [282]:
m.make_simulator()
ss = m.sim
p = ss.vectorize_params(m.inits)
#t = np.cumsum(np.ones(575))[::-1]
dvg = ss.simulate_pro(p=m.inits, analyze=False)

In [275]:
p['xb'] = 0

In [276]:
p['xb']=.01

In [244]:
xtb = map((lambda x: x[0]/(1+(x[1]*t))), zip(p['a'], p['xb']))[0]

In [251]:
(xtb[:, None].T + np.ones((6,1666,575))).shape

(6, 1666, 575)

In [384]:
exp_factors = np.arange(.1, .2, .01)
t = np.cumsum([1]*500)
xtb = array([(np.exp(exf*t)) for exf in exp_factors])
hyb = array([.5*(p['a'][0])/(1+(.02*(t[::-1]))) for hyf in exp_factors])
a=np.linspace(0.1,.7,len(hyb))
for i, hybi in enumerate(hyb):
      plt.plot(hybi, color=gpal(1)[0], alpha=a[i])

In [383]:
hyb[0] - hyb[0][0]

array([  0.00000e+00,   9.43865e-05,   1.89117e-04,   2.84195e-04,
         3.79620e-04,   4.75396e-04,   5.71524e-04,   6.68006e-04,
         7.64844e-04,   8.62040e-04,   9.59596e-04,   1.05751e-03,
         1.15580e-03,   1.25444e-03,   1.35346e-03,   1.45285e-03,
         1.55260e-03,   1.65274e-03,   1.75325e-03,   1.85413e-03,
         1.95540e-03,   2.05705e-03,   2.15909e-03,   2.26151e-03,
         2.36433e-03,   2.46753e-03,   2.57113e-03,   2.67513e-03,
         2.77952e-03,   2.88431e-03,   2.98951e-03,   3.09511e-03,
         3.20112e-03,   3.30754e-03,   3.41438e-03,   3.52162e-03,
         3.62929e-03,   3.73737e-03,   3.84588e-03,   3.95481e-03,
         4.06417e-03,   4.17396e-03,   4.28418e-03,   4.39484e-03,
         4.50593e-03,   4.61746e-03,   4.72944e-03,   4.84186e-03,
         4.95473e-03,   5.06805e-03,   5.18182e-03,   5.29605e-03,
         5.41073e-03,   5.52588e-03,   5.64150e-03,   5.75758e-03,
         5.87413e-03,   5.99115e-03,   6.10865e-03,   6.22662e