In [2]:
from radd import build, models, fit, vis
from radd.toolbox import theta

In [15]:
m.opt.simulator.wts

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [16]:
m = build.Model(data=prodf_store.prodata, kind='xpro', dynamic='hyp', depends_on={'tr':'pGo'}, tb=.550)
m.optimize(tol=1.e-10, ntrials=10000, maxfev=5000)

/home/kyle/anaconda/lib/python2.7/site-packages/scipy/optimize/_minimize.py:378: RuntimeWarning: Method Nelder-Mead does not use gradient information (jac).
  RuntimeWarning)


In [9]:
data=redf_store.redata
rt = redata.query('response==1&acc==1').rt.values

In [10]:
prob = np.arange(.1,1.1,.1)

In [25]:
m = build.Model(data=prodf_store.prodata, kind='xpro', dynamic='hyp', depends_on={'tr':'pGo', 'v':'pGo'}, tb=.550)
m.optimize(tol=1.e-10, ntrials=10000, maxfev=5000)

0.285837164911
[ 0.94754  0.52486  0.53896  0.54297  0.54493  0.54529]
1
{'a': 0.36371801712881013, 'xb': 1.5716011270381633, 'tr': 0.28583716491100142, 'v': array([ 1.18686,  1.17755,  1.16824,  1.15893,  1.14962,  1.14031])}
[  1.74539   0.20665   0.31222   0.53414   1.85371  19.6562 ]
[ 0.94754  0.52486  0.53896  0.54297  0.54493  0.54529]


ValueError: operands could not be broadcast together with shapes (11,) (6,) 

In [22]:
m.fwts

array([  1.49831,   0.15312,   0.2899 ,   0.40542,   8.58918,  11.74552])

In [24]:
m.opt.bwts

array([[  1.74539,   0.20665,   0.31222,   0.53414,   1.85371,  19.6562 ],
       [  1.     ,   0.20665,   0.31222,   0.53414,   1.85371,  19.6562 ],
       [  0.85377,   0.20665,   0.31222,   0.53414,   1.85371,  19.6562 ],
       [  0.9899 ,   0.09959,   0.26758,   0.2767 ,  15.32465,   3.83484],
       [  2.20041,   0.09959,   0.26758,   0.2767 ,  15.32465,   3.83484],
       [  2.20041,   0.09959,   0.26758,   0.2767 ,  15.32465,   3.83484]])

In [20]:
m.opt.simulator.ncond

1

In [271]:
wts = array([1.7453, 1.0, 0.8537, 0.9899, 2.2004, 2.2004, 0.2066, 0.3122, 0.5341, 1.8537, 3.1526, 0.0995, 0.2675, 0.2767, 0.9439, 0.9439])

In [273]:
p = {'a': 0.487581,'xb':1.840808, 'tr':.29223, 'v':array([1.39423800,1.53535562,1.65557698,1.75515234,1.88985329,1.92243114])}
m.opt.simulator.wts =wts
m.opt.simulator.ncond = 6

In [275]:

simfx=m.opt.simulator.sim_fx


In [317]:
m.y+m.opt.simulator.__cost_fx__(p)

array([ 0.9496 ,  0.82353,  0.58885,  0.35974,  0.12396,  0.08177,
        0.51216,  0.57756,  0.56847,  0.54969,  0.54591,  0.65948,
        0.58766,  0.56445,  0.54723,  0.54628])