In [25]:
### import radd
from radd import build
from radd.tools import analyze
from itertools import takewhile
from scipy.stats.mstats_extras import mjci
homedir = os.path.expanduser('~')

ssb = pd.read_csv(os.path.join(homedir, "Dropbox/Projects/SSBayes/alldata_clean.csv"))
udf = ssb[ssb.cond.isin(['uniform'])]
edf = ssb[ssb.cond.isin(['early'])]
ldf = ssb[ssb.cond.isin(['late'])]

re = pd.read_csv(os.path.join(homedir, "Dropbox/Projects/SS/Reactive/Re_Data.csv"), index_col=0)
cox = pd.read_csv(os.path.join(homedir, "Dropbox/Projects/Coxon/coxon_behav_data_binned.csv"))

inits = {'a': 0.45, 'v': 1.26, 'xb': 1.3, 'ssv': -1.3, 'tr': 0.2}

In [27]:
fdf = pd.read_csv('mlate_fitinfo.csv', index_col=0, names = 'p')
finfo = fdf['p']

In [34]:
popt_flat = {'a': 0.5878,  'ssv': -1.1539, 'tr': 0.120, 'v': 0.95904, 'xb': 1.845}
popt = {k: finfo[k] for k in list(popt_flat)}

In [35]:
popt

{'a': 0.66214145831100002,
 'ssv': -1.02697005739,
 'tr': 0.022159446484699998,
 'v': 0.84287984682799999,
 'xb': 1.6950950216299998}

In [2]:
popt_flat = {'a': 0.5878,  'ssv': -1.1539, 'tr': 0.120, 'v': 0.95904, 'xb': 1.845}

In [36]:
#me = build.Model(data=edf, inits=popt_flat, kind='xdpm', fit_on='average')
#mu = build.Model(data=udf, inits=popt_flat, kind='xdpm', fit_on='average')
m = build.Model(data=ldf, inits=popt, kind='xdpm', fit_on='average', ssd_method='all')

In [40]:
udf = udf.copy()
udf['Cond'] = 'flat'

In [71]:
mu = build.Model(data=udf, inits=popt_flat, kind='xdpm', fit_on='average', ssd_method='all', depends_on={'v':'Cond'})

In [88]:
mu = build.Model(data=udf, inits=popt_flat, kind='xdpm', fit_on='average', ssd_method='all', depends_on={'a':'Cond'})

In [89]:
mu.set_basinparams(nrand_inits=20, nrand_samples=500, interval=5, niter=40, stepsize=.06, niter_success=30, tol=1e-4, disp=True)

mu.optimize(fit_flat=False, fit_cond=True)

basinhopping step 0: f 0.415985
basinhopping step 1: f 0.450535 trial_f 0.450535 accepted 1  lowest_f 0.415985
basinhopping step 2: f 0.401037 trial_f 0.401037 accepted 1  lowest_f 0.401037
found new global minimum on step 2 with function value 0.401037
basinhopping step 3: f 0.349825 trial_f 0.349825 accepted 1  lowest_f 0.349825
found new global minimum on step 3 with function value 0.349825
basinhopping step 4: f 0.285205 trial_f 0.285205 accepted 1  lowest_f 0.285205
found new global minimum on step 4 with function value 0.285205
adaptive stepsize: acceptance rate 0.800000 target 0.500000 new stepsize 0.0666667 old stepsize 0.06
basinhopping step 5: f 0.275879 trial_f 0.275879 accepted 1  lowest_f 0.275879
found new global minimum on step 5 with function value 0.275879
basinhopping step 6: f 0.250948 trial_f 0.250948 accepted 1  lowest_f 0.250948
found new global minimum on step 6 with function value 0.250948
basinhopping step 7: f 0.268872 trial_f 0.268872 accepted 1  lowest_f 0.2

In [85]:
mu.opt.simulator.pvc

['a', 'tr', 'xb', 'ssv']

In [69]:
#pc = deepcopy(mu.pc_map)
pc={}
len(list(pc))

0

In [49]:
m.opt.fitparams['nlevels']

KeyError: 'nlevels'

In [149]:
mlate.observed_flat = yhat
mlate.inits = popt
mlate.opt.inits = popt

In [151]:
mlate.set_basinparams(nrand_inits=20, nrand_samples=500, interval=5, niter=40, stepsize=.06, niter_success=30, tol=1e-4, disp=True)
mlate.optimize()    

default inits: fmin0=0.000865609
basinhopping step 0: f 0.0137541
basinhopping step 1: f 0.00725966 trial_f 0.00725966 accepted 1  lowest_f 0.00725966
found new global minimum on step 1 with function value 0.00725966
basinhopping step 2: f 0.0457984 trial_f 0.0457984 accepted 1  lowest_f 0.00725966
basinhopping step 3: f 0.293627 trial_f 0.293627 accepted 1  lowest_f 0.00725966
basinhopping step 4: f 0.200481 trial_f 0.200481 accepted 1  lowest_f 0.00725966
adaptive stepsize: acceptance rate 0.800000 target 0.500000 new stepsize 0.0666667 old stepsize 0.06
basinhopping step 5: f 0.186578 trial_f 0.186578 accepted 1  lowest_f 0.00725966
basinhopping step 6: f 0.470357 trial_f 0.470357 accepted 1  lowest_f 0.00725966
basinhopping step 7: f 0.432656 trial_f 0.432656 accepted 1  lowest_f 0.00725966
basinhopping step 8: f 0.432656 trial_f 0.650908 accepted 0  lowest_f 0.00725966
basinhopping step 9: f 0.286033 trial_f 0.286033 accepted 1  lowest_f 0.00725966
adaptive stepsize: acceptance ra

NameError: global name 'finfo' is not defined

In [157]:
popt

{'a': array([ 0.66039], dtype=float32),
 'ssv': array([-1.01864], dtype=float32),
 'tr': array([ 0.02051], dtype=float32),
 'v': array([ 0.83393], dtype=float32),
 'xb': array([ 1.71752], dtype=float32)}

In [162]:
mlate.yhat_flat_list

[]

In [203]:
mlate.fitinfo.iloc[1, :] = mfinfo

In [174]:
if mlate.fit_on=='average':
    mfinfo = mlate.fitinfo.mean()
    mfinfo['idx'] = 'average'

In [191]:
mfinfo

idx         average
a           0.65351
ssv         -1.0186
tr         0.020509
v           0.83393
xb           1.7175
nfev              7
nvary             5
df               11
chi       0.0011695
rchi     0.00010632
logp        -146.39
AIC         -136.39
BIC            -142
cnvrg             1
dtype: object

In [293]:
sim=mlate.opt.simulator

In [294]:
fp = mlate.fitparams
fp['yhat'] = yhat
ntot = sim.ntot
nl = sim.nlevels
nss = sim.nss
nssd = sim.nssd
ssdix = np.arange(nssd)
nss_per = sim.nss_per_ssd
dx = sim.dx
def go_process(Pg, Tg, xtb):
    go_traces = xtb[:, na]*csum(np.where((rs((nl, ntot, Tg)).T < Pg),dx,-dx).T, axis=2)    
    return go_traces
def dpm_stop_process(go, sson, Ps, Ts):
    ssgo = go[:,:nss,:].reshape(nl, nssd, nss_per, go.shape[-1])
    ssinit = np.array([ssgo[i, ssdix, :, ix] for i, ix in enumerate(sson)])[:,:,:,na]
    stop_traces = ssinits + csum(np.where(rs((nl, nssd, nss_per, Ts))<Ps, dx, -dx), axis=3)
    return stop_traces


In [7]:
from radd.models import goSimulator, dpmSimulator

analyze_fx = sim.analyze_fx
dynamics_fx = sim.temporal_dynamics
vectorize_fx = sim.vectorize_params

dpm = dpmSimulator(analyze_fx=analyze_fx, dynamics_fx=dynamics_fx, vectorize_fx=vectorize_fx)

sim = m.opt.simulator
fp=dict(deepcopy(m.fitparams))
p=dict(deepcopy(m.inits))

fp['ntot'] = sim.ntot
fp['nl'] = sim.nlevels
fp['nss'] = sim.nss
fp['ssd'] = sim.ssd
fp['nssd'] = sim.nssd
fp['ssd_ix'] = np.arange(fp['nssd'])
fp['nss_per_ssd'] = sim.nss_per_ssd
fp['dx'] = sim.dx
fp['tb'] = sim.tb

%timeit dpm.__update_stop__(p, fp)



m = build.Model(data=redata, inits=popt_flat, kind='xdpm', fit_on='average', ssd_method='all')

In [4]:
sim = m.opt.simulator
sim.fitparams['ssd'] = m.ssd[0]
sim.__update__()

In [22]:
%timeit sim.sim_fx(m.inits)

1 loop, best of 3: 255 ms per loop


In [299]:
p = sim.vectorize_params(p)
#Pg, Tg, xtb = sim.__update_go_process__(p)
Ps, Ts = sim.__update_stop_process__(p)
ss_onsets = np.where(Ts<Tg[:, None], Tg[:, None]-Ts, 0)

In [300]:
ss_onsets

array([[178, 228, 278, 328, 378]])

In [287]:
arrays = zip(array_names, [fp[k].flatten() for k in array_names])
y_str, wts_str, yhat_str = [astring(akey, stringify(a)) for akey, a in array_]

SyntaxError: invalid syntax (<ipython-input-287-d253d7ca44b0>, line 6)

In [285]:
y_str

'y = array([0.997500, 0.988000, 0.870000, 0.510000, 0.222000, 0.127000, 0.499159, 0.535159, 0.560159, 0.586159, 0.628159, 0.491159, 0.521159, 0.545159, 0.569159, 0.604159])'

In [275]:
writevector('y', y_str)

'y = array([0.997500, 0.988000, 0.870000, 0.510000, 0.222000, 0.127000, 0.499159, 0.535159, 0.560159, 0.586159, 0.628159, 0.491159, 0.521159, 0.545159, 0.569159, 0.604159])'

In [156]:
popt = {pkey: mlate.opt.finfo[pkey] for pkey in list(mlate.inits)}
yhat = mlate.opt.simulator.sim_fx(popt)

In [103]:
#mlate.params_io(
popt = {pkey: mlate.opt.finfo[pkey] for pkey in list(mlate.inits)}
yhat = mlate.opt.simulator.sim_fx(popt)

In [155]:
popt_first = dict(deepcopy(popt))
yhat_first = deepcopy(yhat)

In [104]:
y = mlate.fitparams['y']

In [ ]:
from radd.tools.analyze import assess_fit
from radd.models import Simulator
from lmfit import minimize, fit_report
from scipy.optimize import basinhopping
from numpy.random import uniform


In [106]:
finfo = mlate.opt.finfo

In [108]:
from radd.tools import messages

In [109]:
fp = mlate.opt.fitparams
wts = mlate.flat_wts[0]
#finfo = assess_fit(sim.finfo)
print(finfo['cnvrg'])
popt = theta.all_params_to_scalar(popt, exclude=list(mlate.opt.pc_map))
log_arrays = {'y': y, 'yhat': yhat, 'wts': wts}
#param_report = fit_report()
messages.logger(finfo=finfo, pdict=popt, depends_on=fp['depends_on'], log_arrays=log_arrays, is_flat=True, kind=mlate.kind, fit_on=fp['fit_on'], dynamic=fp['dynamic'], pc_map=mlate.opt.pc_map)

True


a           0.66214
chi       0.0022914
cnvrg          True
ndata            16
nfev             82
nvary             5
ssv          -1.027
tr         0.022159
v           0.84288
xb           1.6951
df               11
rchi     0.00020831
logp        -135.62
AIC         -125.62
BIC         -131.24
dtype: object

In [137]:
mlate.fitinfo.iloc[0, :] = finfo

In [142]:
df = mlate.fitinfo.mean().dropna()
df.to_csv("mlate_fitinfo.csv")

In [116]:
np.squeeze(quant_cor)

array([ 0.9966 ,  0.991  ,  0.871  ,  0.543  ,  0.225  ,  0.098  ,
        0.50116,  0.53616,  0.56016,  0.58716,  0.62816,  0.49216,
        0.52328,  0.54516,  0.57016,  0.60416])

In [117]:
y

[[[[array([ 1.     ,  0.96883,  0.89183,  0.53   ,  0.21883,  0.12517,
            0.49681,  0.52901,  0.55286,  0.58218,  0.63156,  0.48679,
            0.51284,  0.53615,  0.56241,  0.60033])]]]]

In [118]:
#fp = dict(deepcopy(m.fitparams))
from radd.tools.analyze import kde_fit_quantiles
def breakdown_vector(vector):
    nssd = 5+1
    nquant = 5 # len(fp['percentiles'])
    
    presp = vector[1:nssd]
    quant = vector[-nquant*2:]
    quant_cor = quant[:nquant]
    quant_err = quant[-nquant:]
    #quant_err = vector[nssd+nquant:]    
    return presp, quant_cor, quant_err

y = mlate.fitparams['y']
yhat = mlate.opt.simulator.sim_fx(popt)
y = [y]#y.reshape(2, 16)
yhat = [yhat]#.reshape(2, 16)

phat, qchat, qehat, qchat_samples, qehat_samples = [], [], [], [], []
for yh in yhat:
    presp, quant_cor, quant_err = breakdown_vector(yh)
    phat.append(presp)
    qchat.append(quant_cor)
    qehat.append(quant_err)
    qchat_samples.append(kde_fit_quantiles([quant_cor], bw=.01))
    qehat_samples.append(kde_fit_quantiles([quant_err], bw=.01))
    

p, qc, qe, qc_samples, qe_samples = [], [], [], [], []
for yy in y:
    presp, quant_cor, quant_err = breakdown_vector(yy)
    p.append(presp)
    qc.append(quant_cor)
    qe.append(quant_err)
    qc_samples.append(kde_fit_quantiles([quant_cor], bw=.01))
    qe_samples.append(kde_fit_quantiles([quant_err], bw=.01))


p.extend(phat)

In [126]:
p

[array([ 0.96883,  0.89183,  0.53   ,  0.21883,  0.12517]),
 array([ 0.988,  0.87 ,  0.51 ,  0.222,  0.127])]

In [127]:
qc_samples

[array([ 0.50435,  0.52421,  0.55124, ...,  0.5597 ,  0.58589,  0.62903])]

In [135]:
from radd.tools import vis
f, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(14, 5))
clrs_emp=["#4168B7", "#674172"]
clrs_hat = ["#3498db", "#9B59B6"]
clrs = np.hstack((clrs_emp, clrs_hat)).tolist()

vis.scurves(p, colors=[clrs_emp[0],clrs_hat[0]],markers=False, linestyles=['-', '--'], ax=ax1, labels=['Observed', 'DPM Fit'])
#for i in range(1):
sns.kdeplot(qc_samples[0], cumulative=True, color=clrs_emp[0], ax=ax2, lw=3)
sns.kdeplot(qchat_samples[0], cumulative=True, color=clrs_hat[0], ax=ax2, lw=3, linestyle='--')

sns.kdeplot(qe_samples[0], cumulative=True, color=clrs_emp[0], ax=ax3, lw=3)
sns.kdeplot(qehat_samples[0], cumulative=True, color=clrs_hat[0], ax=ax3, lw=3, linestyle='--')

ax1.set_title('Stop Accuracy')
ax2.set_title('Correct RT Quantiles')
ax3.set_title('Error RT Quantiles')
for ax in [ax2, ax3]:
    ax.set_xlim(.45, .65)
plt.tight_layout()
f.savefig('lategroup_ssbayes_fits.png', dpi=600)

In [110]:
popt

{'a': 0.6621414422988892,
 'ssv': -1.0269700288772583,
 'tr': 0.02215944603085518,
 'v': 0.8428798317909241,
 'xb': 1.6950950622558594}

In [42]:
mlate.observed_flat

[0.58652452434524138]

In [62]:
mlate.ssd_method

'central'

In [7]:

mlate.finfo_flat_list

[]