In [1]:
from radd import build, vis
from radd.toolbox import analyze
from __future__ import division

In [189]:
fpopt = {'a': 0.18759179356224287,
 'tr': 0.40527757024683442,
 'v': 1.0402480224339579,
 'xb': 4.0567403494222916,'si':.01}
fpopt1 = {'a': array([ 0.48986]),
 'tr': array([ 0.29207]),
 'v': array([ 1.72645]),
 'xb': array([ 1.51129])}

In [190]:
m = build.Model(data=pro, kind='xpro', depends_on={'tr':'pGo', 'v':'pGo'}, inits=fpopt1)

In [191]:
m.optimize(stage='flat', multiopt=True, )

basinhopping step 0: f 0.000674659
basinhopping step 1: f 0.000674659 trial_f 0.276129 accepted 0  lowest_f 0.000674659
basinhopping step 2: f 0.0632029 trial_f 0.0632029 accepted 1  lowest_f 0.000674659
basinhopping step 3: f 0.0106623 trial_f 0.0106623 accepted 1  lowest_f 0.000674659
basinhopping step 4: f 0.202022 trial_f 0.202022 accepted 1  lowest_f 0.000674659
basinhopping step 5: f 0.0012494 trial_f 0.0012494 accepted 1  lowest_f 0.000674659
basinhopping step 6: f 0.232154 trial_f 0.232154 accepted 1  lowest_f 0.000674659
basinhopping step 7: f 0.155685 trial_f 0.155685 accepted 1  lowest_f 0.000674659
basinhopping step 8: f 0.212431 trial_f 0.212431 accepted 1  lowest_f 0.000674659
basinhopping step 9: f 0.291783 trial_f 0.291783 accepted 1  lowest_f 0.000674659
adaptive stepsize: acceptance rate 0.800000 target 0.500000 new stepsize 0.0555556 old stepsize 0.05
basinhopping step 10: f 0.233669 trial_f 0.233669 accepted 1  lowest_f 0.000674659
basinhopping step 11: f 0.0391441 

In [193]:
m.opt.basin_decision

'using default inits: fmin=0.000393641'

In [192]:
fpopt1

{'a': array([ 0.48986]),
 'tr': array([ 0.29207]),
 'v': array([ 1.72645]),
 'xb': array([ 1.51129])}

In [194]:
m.optimize(stage='conditional', multiopt=False, inits=fpopt1)

In [195]:
m.fitinfo

a           0.48986
chi       0.0071677
cnvrg         False
ndata            16
nfev           5000
nvary            12
tr_0         0.2959
tr_100      0.28618
tr_20       0.29532
tr_40       0.29575
tr_60       0.28715
tr_80       0.29078
v_0          1.4878
v_100        1.9366
v_20         1.6009
v_40         1.7151
v_60         1.7432
v_80         1.8675
xb           1.5113
df                4
rchi      0.0017919
logp        -101.19
AIC         -77.192
BIC         -95.934
dtype: object

In [148]:
m.opt.basinhopping_full(fpopt, is_flat=False)

basinhopping step 0: f 0.704718
basinhopping step 1: f 0.704718 trial_f 0.781162 accepted 0  lowest_f 0.704718
basinhopping step 2: f 0.737462 trial_f 0.737462 accepted 1  lowest_f 0.704718
basinhopping step 3: f 0.703641 trial_f 0.703641 accepted 1  lowest_f 0.703641
found new global minimum on step 3 with function value 0.703641
basinhopping step 4: f 0.709691 trial_f 0.709691 accepted 1  lowest_f 0.703641
basinhopping step 5: f 0.706772 trial_f 0.706772 accepted 1  lowest_f 0.703641
basinhopping step 6: f 0.80778 trial_f 0.80778 accepted 1  lowest_f 0.703641
basinhopping step 7: f 0.797394 trial_f 0.797394 accepted 1  lowest_f 0.703641
basinhopping step 8: f 0.7846 trial_f 0.7846 accepted 1  lowest_f 0.703641
basinhopping step 9: f 0.761692 trial_f 0.761692 accepted 1  lowest_f 0.703641
adaptive stepsize: acceptance rate 0.800000 target 0.500000 new stepsize 0.0555556 old stepsize 0.05
basinhopping step 10: f 0.752844 trial_f 0.752844 accepted 1  lowest_f 0.703641
basinhopping step 

({'a': 0.18759179356224287,
  'si': 0.01,
  'tr': 0.4052775702468344,
  'v': 1.0402480224339579,
  'xb': array([ 3.96636,  3.98236,  4.04457,  4.02791,  4.10872,  4.08487])},
 0.70364051617007295)

In [90]:
xprov={'a': array([ 0.48672,  0.48672,  0.48672,  0.48672,  0.48672,  0.48672]), 'v_0': 1.4204744923605306, 'xb': array([ 1.86673,  1.86673,  1.86673,  1.86673,  1.86673,  1.86673]), 'v': array([ 1.42047,  1.54611,  1.67993,  1.75729,  1.87396,  1.89252]), 'tr': array([ 0.29334,  0.29334,  0.29334,  0.29334,  0.29334,  0.29334]), 'v_100': 1.8925194341059219, 'v_60': 1.7572925581377903, 'v_80': 1.8739583821515711, 'v_20': 1.5461146129935177, 'v_40': 1.6799320687772294}
m.simulate(xprov)

array([ 0.91897,  0.72629,  0.42737,  0.2473 ,  0.08643,  0.06182,
        0.50734,  0.52034,  0.52934,  0.53834,  0.54734,  0.52218,
        0.53434,  0.54134,  0.54734,  0.55234])

In [134]:
m.avg_y

array([ 0.93996,  0.79037,  0.54775,  0.33996,  0.11803,  0.08139,
        0.50343,  0.53158,  0.54094,  0.54427,  0.54527,  0.53376,
        0.54393,  0.5447 ,  0.54517,  0.54533])

In [137]:
m.simulate(m.popt)

array([ 0.92557,  0.80672,  0.56122,  0.33673,  0.10564,  0.09064,
        0.50728,  0.51828,  0.52928,  0.53628,  0.54728,  0.52028,
        0.53328,  0.54228,  0.54728,  0.55328])

In [186]:
x = theta.all_params_to_scalar(x)
x['xb']=np.linspace(1,4,6)

In [188]:
x

{'a': array([ 0.18759,  0.18759,  0.18759,  0.18759,  0.18759,  0.18759]),
 'si': 0.01,
 'tr': array([ 0.40528,  0.40528,  0.40528,  0.40528,  0.40528,  0.40528]),
 'v': array([ 1.04025,  1.04025,  1.04025,  1.04025,  1.04025,  1.04025]),
 'xb': array([ 3.97573,  4.00797,  4.03958,  4.10455,  4.1056 ,  4.17196], dtype=float32),
 'xb_0': 3.9757307477109034,
 'xb_100': 4.1719601103923889,
 'xb_20': 4.0079689316360785,
 'xb_40': 4.039577288171829,
 'xb_60': 4.10454658197916,
 'xb_80': 4.1055980613923237}

In [182]:
x=deepcopy(popt)

In [187]:
vis.plot_fits(m.avg_y, m.simulate(x), kind='pro', cdf=True)

In [95]:
from scipy.stats.mstats import mquantiles as mq

In [100]:
emp_kq = lambda rts: analyze.kde_fit_quantiles(mq(rts, prob=np.arange(0,1,.02)), bw=.01)
hi_rts = data.query('response==1 & pGo>.5').rt.values
lo_rts = data.query('response==1 & pGo<.5').rt.values
dat_cq = emp_kq(hi_rts)
dat_eq = emp_kq(lo_rts)
y=array([ 0.93996,  0.79037,  0.54775,  0.33996,  0.11803,  0.08139,
        0.50343,  0.53158,  0.54094,  0.54427,  0.54527,  0.53376,
        0.54393,  0.5447 ,  0.54517,  0.54533])

In [118]:
f, (ax1, ax2, ax3) = plt.subplots(1,3,figsize=(14,6), sharey=False)
shade=True; alpha=.5; bw=.1; lw=2.5; ls='-'
sns.distplot(dat_cq, kde=False, color='k', norm_hist=True, ax=ax1, bins=30)
sns.distplot(dat_eq, kde=False, color='k', norm_hist=True, ax=ax2, bins=70)
plot_params={'shade':shade, 'alpha':alpha, 'bw':bw, 'lw':lw, 'ls':ls}

In [106]:
m.tb

0.555

In [117]:
vis.plot_fits(y, v, plot_params=plot_params, axes=[ax1,ax2,ax3], mc=mcpals[i], kind='pro', colors=[pals[i]]*2)
for ax in axes.flatten():
      if ax.is_last_col():
            continue
      ax.set_xlim(.42, .64)
      if ax.is_first_col():
            ax.set_ylabel('P(RT)')
      #if ax.is_last_row():
      ax.set_xlabel('RT (s)')
      ax.set_xticklabels([int(xx) for xx in ax.get_xticks()*1000])

ValueError: max() arg is an empty sequence

In [132]:
data=m.data
sns.set_context('notebook', font_scale=1.8)
#f, (ax1, ax2, ax3) = plt.subplots(1,3,figsize=(14, 5.5), sharey=False)
f, axes = plt.subplots(4,3,figsize=(18, 20), sharey=False)
y=array([ 0.93996,  0.79037,  0.54775,  0.33996,  0.11803,  0.08139,
        0.50343,  0.53158,  0.54094,  0.54427,  0.54527,  0.53376,
        0.54393,  0.5447 ,  0.54517,  0.54533])
tr = array([ 0.93277,  0.79712,  0.51741,  0.37875,  0.13265,  0.09424,
        0.46173,  0.48873,  0.50597,  0.52497,  0.54273,  0.50455,
        0.52355,  0.53431,  0.54355,  0.55055])
a = array([ 0.95558,  0.83253,  0.52041,  0.35834,  0.13806,  0.10384,
        0.46871,  0.49071,  0.50871,  0.52371,  0.54171,  0.50171,
        0.52371,  0.53571,  0.54571,  0.55271])
vtr = array([ 0.95438,  0.82653,  0.56783,  0.33133,  0.12785,  0.10204,
        0.50045,  0.51288,  0.52445,  0.53461,  0.54688,  0.53148,
        0.53948,  0.54348,  0.54891,  0.55319])
v = array([ 0.96098,  0.78391,  0.53121,  0.34754,  0.14526,  0.06963,
        0.51113,  0.52213,  0.53113,  0.53913,  0.55013,  0.52413,
        0.53513,  0.54213,  0.54813,  0.55213])

for i, yhat in enumerate([a, tr, vtr, v][::-1]):
      
      ax1, ax2, ax3 = axes[i]
      # set parameters for simulated plots
      shade=True; alpha=.5; bw=.01; lw=2.5; ls='-'
      #sns.distplot(dat_cq, kde=False, color='k', norm_hist=True, ax=ax1, bins=15)
      #sns.distplot(dat_eq, kde=False, color='k', norm_hist=True, ax=ax2, bins=20)
      sns.kdeplot
      plot_params={'shade':shade, 'alpha':alpha, 'bw':bw, 'lw':lw, 'ls':ls}

      vis.plot_profits(y, yhat, plot_params=plot_params, axes=[ax1,ax2,ax3], kind='pro', colors=[pals[i]]*2)

for ax in axes.flatten():
      if ax.is_last_col():
            continue
      ax.set_xlim(.42, .64)
      if ax.is_first_col():
            ax.set_ylabel('P(RT)')
      #if ax.is_last_row():
      ax.set_xlabel('RT (s)')
      ax.set_xticklabels([int(xx) for xx in ax.get_xticks()*1000])

In [ ]:
def plot_pro_rts(c=['Green','Blue','Red'], sdf=None, hi_list=None, lo_list=None, l=[]):


      sns.set(style='white', font_scale=1.4)   
      y=array([ 0.94443,  0.79361,  0.55094,  0.343  ,  0.12147,  0.0856 ,
        0.51469,  0.53463,  0.5414 ,  0.54469,  0.54527,  0.53737,
        0.54404,  0.5447 ,  0.54518,  0.54532])
      

      bw=.006
      
      hi=analyze.kde_fit_quantiles(y[6:11], bw=bw)
      lo=analyze.kde_fit_quantiles(y[11:], bw=bw)      
      sns.kdeplot(hi, color='k', linewidth=3.5, ax=ax1, bw=bw, label='High')
      sns.kdeplot(lo, color='k', linewidth=3.5, ax=ax2, bw=bw, label="Low")
      
      for i, high in enumerate(hi_list):
            h_rt = analyze.kde_fit_quantiles(high, bw=bw)
            sns.kdeplot(h_rt, color=c[i], bw=bw, ax=ax1, linestyle='--', linewidth=3, alpha=.9, label=l[i])
            
      for i, low in enumerate(lo_list):
            l_ert = analyze.kde_fit_quantiles(low, bw=bw)
            sns.kdeplot(l_ert, color=c[i], bw=bw, ax=ax2, linestyle='--', linewidth=3, alpha=.9)

      for ax in [ax1, ax2]:
            ax.set_xlim(.450,.600)
            xx=ax.get_xticks()[::2]
            ax.set_xticks(xx)
            ax.set_xticklabels([int(xxx*1000) for xxx in xx])
            ax.set_xlabel('RT (ms)')
      plt.tight_layout()
      sns.despine()

In [68]:
m.opt.hop_around(fpopt, ninits=10, is_flat=True)

basinhopping step 0: f 0.000869081
basinhopping step 1: f 0.235274 trial_f 0.235274 accepted 1  lowest_f 0.000869081
basinhopping step 2: f 0.060528 trial_f 0.060528 accepted 1  lowest_f 0.000869081
basinhopping step 3: f 0.060528 trial_f 0.260926 accepted 0  lowest_f 0.000869081
basinhopping step 4: f 0.272677 trial_f 0.272677 accepted 1  lowest_f 0.000869081
basinhopping step 5: f 0.268499 trial_f 0.268499 accepted 1  lowest_f 0.000869081
basinhopping step 6: f 0.268499 trial_f 1.66345 accepted 0  lowest_f 0.000869081
basinhopping step 7: f 0.000264682 trial_f 0.000264682 accepted 1  lowest_f 0.000264682
found new global minimum on step 7 with function value 0.000264682
basinhopping step 8: f 0.208955 trial_f 0.208955 accepted 1  lowest_f 0.000264682
basinhopping step 9: f 0.000938363 trial_f 0.000938363 accepted 1  lowest_f 0.000264682
adaptive stepsize: acceptance rate 0.700000 target 0.500000 new stepsize 0.0555556 old stepsize 0.05
basinhopping step 10: f 0.0294049 trial_f 0.0294

{'a': 0.18759179356224287,
 'tr': 0.40527757024683442,
 'v': 1.0402480224339579,
 'xb': 4.0567403494222916}

In [121]:
m.opt.basins

AttributeError: 'Optimizer' object has no attribute 'basins'

In [69]:
m.opt.basin_decision

'found global miniumum new: fmin=0.000154722; norig= 0.000265)'

In [66]:
m.flat_popt

{'a': array([ 0.48866]),
 'tr': array([ 0.29139]),
 'v': array([ 1.71892]),
 'xb': array([ 1.54099])}

In [11]:
fpopt = deepcopy(m.flat_popt)
      for name in names:
      m.depends_on={name:'pGo'}
      m.inits=fpopt
      

In [2]:
iv = {'v':array([ 1.41106,  1.56252,  1.68275,  1.76071,  1.87995,  1.92475]), 'a': 0.487226, 'xb':   1.563474, 'tr':   0.292126}
itr = {'a': 0.62868, 'v': 1.421123, 'xb': 0.640829, 'tr':array([ 0.18203,  0.16131,  0.13355,  0.11741,  0.08473,  0.07697])}
ia = {'a':array([ 0.37922,  0.34356,  0.30503,  0.28076,  0.24567,  0.23642]), 'xb': 0.9136456, 'v': 1.127346, 'tr': 0.2997148}
ixb={'a': 0.48158, 'xb': array([ 0.04638,  0.1547 ,  0.37575,  0.53875,  1.29523,  1.29254]), 'tr':0.27438, 'v': 1.54521}

In [6]:
pd.DataFrame(inits_list)

Series([], dtype: float64)

In [3]:
inits_list = [iv, itr, ia, ixb]

In [ ]:
iv = {'v':array([ 1.41106,  1.56252,  1.68275,  1.76071,  1.87995,  1.92475]), 'a': 0.487226, 'xb':   1.563474, 'tr':   0.292126}
itr = {'a': 0.62868, 'v': 1.421123, 'xb': 0.640829, 'tr':array([ 0.18203,  0.16131,  0.13355,  0.11741,  0.08473,  0.07697])}
ia = {'a':array([ 0.37922,  0.34356,  0.30503,  0.28076,  0.24567,  0.23642]), 'xb': 0.9136456, 'v': 1.127346, 'tr': 0.2997148}
ixb={'a': 0.48158, 'xb': array([ 0.04638,  0.1547 ,  0.37575,  0.53875,  1.29523,  1.29254]), 'tr':0.27438, 'v': 1.54521}


names = ['v', 'tr', 'a', 'xb']
inits_list = [iv, itr, ia, ixb]
for i, idc in enumerate(inits_list):
      idc[names[i]] = np.mean(idc[names[i]])

ivtr['v']=np.mean(ivtr['v'])
ivtr['tr']=np.mean(ivtr['tr'])
inits_list.append(ivtr)

In [ ]:
parameter = 'vtr'
depends_on = {'v':'pGo', 'tr':'pGo'}
finfo_list, yhat_list = [], []
d = '/'.join(['FinalPro', parameter])
if not os.path.isdir(pth+d):
      os.mkdir(pth+d)
os.chdir(pth+d)
finfo_list, yhat_list = [], []

In [ ]:
for i in range(20):
      xinits_list = [dict(deepcopy(xinit for xinit in inits_list))]
      
      for xi in xinits_list:
            model = build.Model(data=prodata, kind='xpro', inits=xi, depends_on=depends_on)
            model.make_optimizer(tol=1.e-5, multiopt=True, maxfev=500)
            opt=model.opt
            opt.make_simulator()

            ydata, ywts = model.avg_y, model.avg_wts
            # STAGE 3 (Final Simplex)
            yhat, finfo, xiv = opt.gradient_descent(y=ydata, wts=ywts, inits=xi, is_flat=False)
            finfo_list.append(finfo)
            yhat_list.append(yhat)

In [ ]:
dfx = pd.DataFrame([fi.T for fi in finfo_list])
dff = dfx[['cnvrg', 'logp', 'chi', 'rchi', 'AIC', 'BIC', 'a', 'v_0', 'v_20', 'v_40', 'v_60', 'v_80',  'v_100', 'tr_0', 'tr_20', 'tr_40', 'tr_60', 'tr_80', 'tr_100', 'xb']]


dff.to_csv('xpro_vtr_bootinfo.csv', index=False)
yhatdf = pd.DataFrame(np.asarray(yhat_list))
yhatdf.to_csv('xpro_vtr_bootfits.csv', index=False)