In [264]:
from radd import fitre, utils, cRADD, build, fit
from lmfit import minimize

In [325]:
data=redf_store['redata']
inits = redf_store['rebsl_boot_popt']
y = build.rangl_data(data)

In [322]:
theta = t
bias='v'
ncond=2
depends_list = [bias]
for par in depends:
      
      for i in range(ncond-1):
            dep_init = theta[bias]
            theta[bias + str(i)] = dep_init
            depends_list.append(bias+str(i))


In [323]:
t

{'a': 0.44409409212000012,
 'ssv': 0.94733930094933305,
 'tr': 0.30487069828933316,
 'v': 1.1223597714793327,
 'v0': 1.1223597714793327,
 'v1': 1.1223597714793327,
 'x': 10,
 'z': 0.15424655465199996}

In [310]:
deplist = [theta.pop(bias+str(i+1)) for i in range(ncond)]
#theta[bias] = np.array(deplist.insert(0))

KeyError: 'v1'

In [286]:
cond_vals = np.hstack(labels*len(indx))
idx_vals = idx_vals = np.sort(np.hstack(indx*ncond))

In [268]:
indx=list(m.data.idx.unique())
ncond=len(['bsl', 'pnl'])
np.sort(np.hstack(indx*ncond))

array([28, 28, 29, 29, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34, 35, 35, 36,
       36, 37, 37, 38, 38, 39, 39, 40, 40, 41, 41, 42, 42, 43, 43, 44, 44,
       45, 45, 47, 47, 48, 48, 50, 50, 51, 51, 52, 52, 54, 54, 55, 55, 56,
       56, 57, 57, 58, 58, 59, 59, 60, 60, 61, 61, 62, 62, 63, 63, 65, 65,
       66, 66, 67, 67, 68, 68, 69, 69, 70, 70, 71, 71, 72, 72, 73, 73, 74,
       74, 75, 75, 76, 76, 77, 77, 78, 78, 79, 79, 80, 80, 81, 81, 82, 82,
       83, 83, 84, 84, 85, 85, 86, 86, 87, 87, 88, 88, 89, 89, 90, 90, 95,
       95, 97, 97])

In [299]:
datdf = data.groupby(['idx', 'Cond']).apply(build.rangl_data, kind='reactive')
cond_vals = datdf.index.get_level_values('Cond')
indx_vals = datdf.index.get_level_values('idx')

In [302]:
d = np.vstack(datdf.values)
ixdf = pd.DataFrame({'idx': indx_vals, 'Cond': cond_vals}, columns=['idx', 'Cond'])
observed = pd.concat([ixdf, pd.DataFrame(data=np.vstack(datdf.values), columns=qp_cols)], axis=1)

In [303]:
observed

idx Cond      Go   200   250   300   350   400      c5     c25     c50  \
0     28  bsl  0.9917  1.00  1.00  0.95  0.60  0.00  5.0509  5.3191  5.5812   
1     28  pnl  0.9752  1.00  1.00  0.95  0.80  0.10  5.1767  5.4517  5.7184   
2     29  bsl  0.9917  1.00  1.00  1.00  0.90  0.00  5.2504  5.4513  5.5850   
3     29  pnl  0.9669  1.00  1.00  1.00  0.75  0.35  5.3145  5.5997  5.8502   
4     30  bsl  0.9421  1.00  1.00  1.00  0.80  0.25  5.2978  5.7188  5.9812   
5     30  pnl  0.8678  1.00  1.00  1.00  0.65  0.45  5.1845  5.5843  5.8501   
6     31  bsl  1.0000  1.00  1.00  1.00  0.65  0.00  5.3165  5.4515  5.5850   
7     31  pnl  0.9669  1.00  1.00  1.00  0.85  0.30  5.3178  5.5824  5.7175   
8     32  bsl  0.9504  1.00  1.00  1.00  0.75  0.10  5.4496  5.6036  5.8513   
9     32  pnl  0.9669  1.00  1.00  1.00  0.75  0.10  5.3495  5.7178  5.8518   
10    33  bsl  0.9421  1.00  1.00  0.85  0.25  0.15  5.0511  5.3180  5.4625   
11    33  pnl  0.9091  1.00  1.00  0.85  0.50  0.05  5.1845  5.4496  5.5845   
12    34  bsl  0.9504  1.00  1.00  1.00  0.50  0.05  5.0515  5.3169  5.4510   
13    34  pnl  0.9835  1.00  0.95  1.00  0.65  0.10  5.1837  5.5830  5.7188   
14    35  bsl  0.9669  1.00  1.00  0.90  0.45  0.00  5.0833  5.3195  5.4534   
..   ...  ...     ...   ...   ...   ...   ...   ...     ...     ...     ...   
107   85  pnl  0.9917  1.00  1.00  0.65  0.15  0.10  4.9175  5.1838  5.4474   
108   86  bsl  0.9339  1.00  0.95  0.95  0.60  0.05  5.0509  5.3168  5.7162   
109   86  pnl  0.8843  1.00  0.95  1.00  0.75  0.20  5.1844  5.5840  5.8510   
110   87  bsl  1.0000  1.00  1.00  0.75  0.30  0.00  4.9887  5.1869  5.3198   
111   87  pnl  1.0000  1.00  1.00  0.90  0.35  0.05  5.0538  5.3170  5.4503   
112   88  bsl  0.8099  1.00  0.95  0.85  0.65  0.10  5.1855  5.5848  5.9827   
113   88  pnl  0.7190  1.00  1.00  0.95  0.80  0.55  5.0538  5.5834  5.8489   
114   89  bsl  0.9752  1.00  1.00  1.00  0.85  0.30  5.3478  5.7203  5.8547   
115   89  pnl  0.9587  1.00  1.00  1.00  1.00  0.60  5.5873  5.9802  6.1165   
116   90  bsl  0.9917  1.00  1.00  0.95  0.85  0.05  5.4513  5.7166  5.8511   
117   90  pnl  0.9339  1.00  1.00  1.00  0.80  0.20  5.4505  5.7758  5.9837   
118   95  bsl  1.0000  1.00  0.90  0.50  0.15  0.00  4.7845  5.0491  5.1732   
119   95  pnl  0.9752  1.00  0.90  0.90  0.65  0.10  4.7849  5.1853  5.4510   
120   97  bsl  1.0000  1.00  1.00  0.95  0.50  0.00  5.0508  5.2853  5.3367   
121   97  pnl  0.9587  0.95  1.00  0.95  0.45  0.05  5.0510  5.3166  5.4508   

        c75     c95      e5     e25     e50     e75     e95  
0    5.6643  5.9818  4.9608  5.3166  5.3187  5.4585  5.6744  
1    5.9735  6.1186  5.1983  5.4525  5.5858  5.7181  6.0212  
2    5.7196  5.9844  5.2676  5.4510  5.5845  5.7092  5.9019  
3    5.9849  6.2498  5.3144  5.4477  5.5171  5.7507  5.9804  
4    6.1175  6.3843  5.3607  5.6057  5.8535  6.0980  6.2076  
5    6.1172  6.3834  5.0054  5.5847  5.7183  5.8690  5.9852  
6    5.7178  5.9846  5.0524  5.3177  5.4512  5.5836  5.9686  
7    5.8516  6.2506  5.3178  5.4512  5.5857  5.7220  6.1014  
8    5.9855  6.3818  5.3194  5.5002  5.7084  5.9308  6.0717  
9    6.0416  6.3697  5.0521  5.4512  5.5855  5.7188  6.0219  
10   5.7172  5.9835  4.9065  5.1846  5.4501  5.5837  5.8415  
11   5.8510  6.2500  5.1840  5.3260  5.4518  5.5850  5.9826  
12   5.7174  6.2503  5.1837  5.3179  5.4516  5.6963  5.8498  
13   5.9838  6.2509  5.3202  5.4515  5.5845  5.7176  6.1118  
14   5.5864  5.8538  5.1465  5.3213  5.4518  5.4553  5.7178  
..      ...     ...     ...     ...     ...     ...     ...  
107  5.5933  5.9835  4.7842  4.9187  5.2476  5.3184  5.5822  
108  5.9832  6.2506  4.6578  5.4417  5.5829  5.8282  6.2034  
109  6.1174  6.3847  4.7656  5.3180  5.5926  5.8510  5.9833  
110  5.5847  5.8504  4.7861  5.0512  5.1858  5.3195  5.5866  
111  5.5900  5.8535  4.9201  5.1848  5.3187  5.7159  5.8775  
112  6.1172  6.3823  5.0939  5.5846  5.8505  5.9844  6.2660  
113  6.1256  6.3840  5.1108  5.5837  5.7171  5.896

In [291]:
#datdf = data.groupby(['idx', 'Cond']).apply(build.rangl_data, kind='reactive')


labels = ['bsl', 'pnl']
indx=list(m.data.idx.unique())
index = np.sort(np.hstack(indx*ncond))
delays = sorted(data.query('trial_type=="stop"').ssd.unique().astype(np.int))
qp_cols = ['Go'] + delays +['c5','c25','c50','c75','c95'] + ['e5','e25','e50','e75','e95']

df = pd.DataFrame(data=np.vstack(datdf.values), columns=qp_cols)

In [292]:
df

Go   200   250   300   350   400      c5     c25     c50     c75  \
0    0.9917  1.00  1.00  0.95  0.60  0.00  5.0509  5.3191  5.5812  5.6643   
1    0.9752  1.00  1.00  0.95  0.80  0.10  5.1767  5.4517  5.7184  5.9735   
2    0.9917  1.00  1.00  1.00  0.90  0.00  5.2504  5.4513  5.5850  5.7196   
3    0.9669  1.00  1.00  1.00  0.75  0.35  5.3145  5.5997  5.8502  5.9849   
4    0.9421  1.00  1.00  1.00  0.80  0.25  5.2978  5.7188  5.9812  6.1175   
5    0.8678  1.00  1.00  1.00  0.65  0.45  5.1845  5.5843  5.8501  6.1172   
6    1.0000  1.00  1.00  1.00  0.65  0.00  5.3165  5.4515  5.5850  5.7178   
7    0.9669  1.00  1.00  1.00  0.85  0.30  5.3178  5.5824  5.7175  5.8516   
8    0.9504  1.00  1.00  1.00  0.75  0.10  5.4496  5.6036  5.8513  5.9855   
9    0.9669  1.00  1.00  1.00  0.75  0.10  5.3495  5.7178  5.8518  6.0416   
10   0.9421  1.00  1.00  0.85  0.25  0.15  5.0511  5.3180  5.4625  5.7172   
11   0.9091  1.00  1.00  0.85  0.50  0.05  5.1845  5.4496  5.5845  5.8510   
12   0.9504  1.00  1.00  1.00  0.50  0.05  5.0515  5.3169  5.4510  5.7174   
13   0.9835  1.00  0.95  1.00  0.65  0.10  5.1837  5.5830  5.7188  5.9838   
14   0.9669  1.00  1.00  0.90  0.45  0.00  5.0833  5.3195  5.4534  5.5864   
..      ...   ...   ...   ...   ...   ...     ...     ...     ...     ...   
107  0.9917  1.00  1.00  0.65  0.15  0.10  4.9175  5.1838  5.4474  5.5933   
108  0.9339  1.00  0.95  0.95  0.60  0.05  5.0509  5.3168  5.7162  5.9832   
109  0.8843  1.00  0.95  1.00  0.75  0.20  5.1844  5.5840  5.8510  6.1174   
110  1.0000  1.00  1.00  0.75  0.30  0.00  4.9887  5.1869  5.3198  5.5847   
111  1.0000  1.00  1.00  0.90  0.35  0.05  5.0538  5.3170  5.4503  5.5900   
112  0.8099  1.00  0.95  0.85  0.65  0.10  5.1855  5.5848  5.9827  6.1172   
113  0.7190  1.00  1.00  0.95  0.80  0.55  5.0538  5.5834  5.8489  6.1256   
114  0.9752  1.00  1.00  1.00  0.85  0.30  5.3478  5.7203  5.8547  6.1159   
115  0.9587  1.00  1.00  1.00  1.00  0.60  5.5873  5.9802  6.1165  6.2521   
116  0.9917  1.00  1.00  0.95  0.85  0.05  5.4513  5.7166  5.8511  5.9847   
117  0.9339  1.00  1.00  1.00  0.80  0.20  5.4505  5.7758  5.9837  6.1172   
118  1.0000  1.00  0.90  0.50  0.15  0.00  4.7845  5.0491  5.1732  5.3169   
119  0.9752  1.00  0.90  0.90  0.65  0.10  4.7849  5.1853  5.4510  5.5845   
120  1.0000  1.00  1.00  0.95  0.50  0.00  5.0508  5.2853  5.3367  5.5832   
121  0.9587  0.95  1.00  0.95  0.45  0.05  5.0510  5.3166  5.4508  5.5849   

        c95      e5     e25     e50     e75     e95  
0    5.9818  4.9608  5.3166  5.3187  5.4585  5.6744  
1    6.1186  5.1983  5.4525  5.5858  5.7181  6.0212  
2    5.9844  5.2676  5.4510  5.5845  5.7092  5.9019  
3    6.2498  5.3144  5.4477  5.5171  5.7507  5.9804  
4    6.3843  5.3607  5.6057  5.8535  6.0980  6.2076  
5    6.3834  5.0054  5.5847  5.7183  5.8690  5.9852  
6    5.9846  5.0524  5.3177  5.4512  5.5836  5.9686  
7    6.2506  5.3178  5.4512  5.5857  5.7220  6.1014  
8    6.3818  5.3194  5.5002  5.7084  5.9308  6.0717  
9    6.3697  5.0521  5.4512  5.5855  5.7188  6.0219  
10   5.9835  4.9065  5.1846  5.4501  5.5837  5.8415  
11   6.2500  5.1840  5.3260  5.4518  5.5850  5.9826  
12   6.2503  5.1837  5.3179  5.4516  5.6963  5.8498  
13   6.2509  5.3202  5.4515  5.5845  5.7176  6.1118  
14   5.8538  5.1465  5.3213  5.4518  5.4553  5.7178  
..      ...     ...     ...     ...     ...     ...  
107  5.9835  4.7842  4.9187  5.2476  5.3184  5.5822  
108  6.2506  4.6578  5.4417  5.5829  5.8282  6.2034  
109  6.3847  4.7656  5.3180  5.5926  5.8510  5.9833  
110  5.8504  4.7861  5.0512  5.1858  5.3195  5.5866  
111  5.8535  4.9201  5.1848  5.3187  5.7159  5.8775  
112  6.3823  5.0939  5.5846  5.8505  5.9844  6.2660  
113  6.3840  5.1108  5.5837  5.7171  5.8960  6.2983  
114  6.3563  5.0820  5.5831  5.7187  5.7773  6.2058  
115  6.3874  5.9098  6.1205  6.2489  6.3817  6.3866  
116  6.2519  5.3181  5.5830  5.6020  5.8513  6.0219  
117  6.3832  5.3727  5.7173  5.8598  6.0557  6.2497  
118  5.6421  4.7001  4.9176  5.0

In [266]:
datdf = data.groupby(['idx', 'Cond']).apply(build.rangl_data, kind='reactive')
dat = np.vstack(datdf.as_matrix())# unstack().values.shape#.astype(np.float32)

In [222]:
dat = np.vstack([[build.rangl_data(idxdf) for idx, idxdf in cdf.groupby('idx')] for c, cdf in data.groupby('Cond')]).astype(np.float32)

In [233]:
dat[0]

array([ 0.99173552,  1.        ,  1.        ,  0.94999999,  0.60000002,
        0.        ,  5.05088902,  5.31908226,  5.58122206,  5.66428423,
        5.98183012,  4.96080875,  5.31661272,  5.31869507,  5.45847368,
        5.67435551], dtype=float32)

In [234]:
dat[1]

array([ 0.97520661,  1.        ,  1.        ,  0.94999999,  0.80000001,
        0.1       ,  5.176723  ,  5.45167112,  5.71843767,  5.97350597,
        6.11857319,  5.19827795,  5.45248842,  5.58578682,  5.71808434,
        6.02119255], dtype=float32)

In [55]:
ip=inits.copy()
ip['v'] = np.array([ip['v'], ip['v']])

In [172]:
yhat = fit.resim_only(ip)

2


In [174]:
wtc, wte = wts[0], wts[1]
cost = np.hstack([y[:6]-yhat[:6], wtc*y[6:11]-wtc*yhat[6:11], wte*y[11:]-wte*yhat[11:]]).astype(np.float32)

(2, 16)

In [269]:
m = build.Model(data=data, inits=ip, depends_on={'v':'Cond'})

In [236]:
m.prepare_fit()

ValueError: Shape of passed values is (2, 61), indices imply (16, 61)

In [208]:
m.wts

array([[ 0.84369385,  0.88343162,  0.7599295 ,  0.92508843,  0.87331289,
         0.1805332 ,  0.30360656,  0.27065157,  0.09194022,  0.24185675],
       [ 0.94201328,  0.81246562,  0.81392183,  0.88639332,  0.92724563,
         0.26623978,  0.26808909,  0.07757932,  0.26409836,  0.23662228]])

In [209]:
y

array([ 0.93462944,  0.99385244,  0.98401642,  0.91106558,  0.54959017,
        0.14221312,  5.05235386,  5.45005417,  5.600739  ,  5.85156584,
        6.24984407,  4.91835451,  5.31585741,  5.45129824,  5.71668339,
        5.98433924], dtype=float32)

In [162]:
bsl = sdc[0]
bsl.min()/bsl

array([ 0.89562841,  1.        ,  0.93781229,  0.86247788,  0.80670785])

In [178]:
wts

array([[[ 0.84369385,  0.94201328,  0.88343162,  0.81246562,  0.7599295 ],
        [ 0.1805332 ,  0.26623978,  0.30360656,  0.26808909,  0.27065157]],

       [[ 0.81392183,  0.92508843,  0.88639332,  0.87331289,  0.92724563],
        [ 0.07757932,  0.09194022,  0.26409836,  0.24185675,  0.23662228]]])

In [179]:
(pc*(sdc.min(axis=1)/sdc_tr)).T

array([[ 0.84369385,  0.94201328,  0.88343162,  0.81246562,  0.7599295 ],
       [ 0.81392183,  0.92508843,  0.88639332,  0.87331289,  0.92724563]])

In [161]:
sdc.min(axis=1)#/
sdc_tr = sdc.T

In [94]:
wtc, wte = wts[0], wts[1]

cost = np.hstack([y[:6]-yhat[:6], wtc*y[6:11]-wtc*yhat[6:11], wte*y[11:]-wte*yhat[11:]]).astype(np.float32)


array([[ 0.958     ,  0.997     ,  0.991     ,  0.944     ,  0.517     ,
         0.119     ,  5.09370698,  5.37370698,  5.58370698,  5.79370698,
         6.11370698,  4.77370698,  4.93370698,  5.00870698,  5.15310698,
         5.30750698],
       [ 0.961     ,  0.996     ,  0.989     ,  0.95      ,  0.519     ,
         0.136     ,  5.08370698,  5.36370698,  5.54370698,  5.77370698,
         6.10850698,  4.78410698,  4.92630698,  5.01870698,  5.15370698,
         5.29350698]])

In [92]:
yhat

In [89]:
x = [np.hstack([i[ii] for i in yhat]) for ii in range(ncond)]

In [90]:
x

[array([ 0.966     ,  1.        ,  0.987     ,  0.956     ,  0.495     ,
         0.119     ,  5.10370698,  5.35630698,  5.54370698,  5.79370698,
         6.12370698,  4.83090698,  4.90730698,  4.97370698,  5.09010698,
         5.23650698]),
 array([ 0.96      ,  0.998     ,  0.984     ,  0.95      ,  0.507     ,
         0.12      ,  5.09790698,  5.35370698,  5.57370698,  5.82370698,
         6.13370698,  4.77810698,  4.95230698,  5.01370698,  5.10510698,
         5.27150698])]

In [6]:
m=build.Model(data=data, inits=inits)
m.prepare_fit()
wts=m.wts

preparing reactive model using subjects method


In [20]:
wts

{'bsl': [array([ 0.85057508,  0.94201328,  0.85581924,  0.83270821,  0.80039883]),
  array([ 0.23334144,  0.28508601,  0.30360656,  0.25749045,  0.24355159])]}

In [85]:
print '--'*20+'\n\n'


----------------------------------------




In [328]:
#!/usr/local/bin/env python
from __future__ import division
import time
import numpy as np
import pandas as pd
from lmfit import Parameters, Minimizer, fit_report
import lmfit
from radd.utils import *
from radd.cRADD import recost
from radd import RADD


def fit_reactive_model(y, inits={}, depends=['xx'], wts=None, model='radd', ntrials=5000, maxfev=5000, ftol=1.e-3, xtol=1.e-3, all_params=0, disp=False, fitid=None, method='Nelder-Mead'):

      ip = inits.copy()
      lim = {'tr': (.001, .5), 'v': (.01, 4.),  'ssv': (-4., -.01),  'a' : (.01, .6), 'z':(.001, .9)}
      if 'pGo' in ip.keys(): del ip['pGo']
      if 'ssd' in ip.keys(): del ip['ssd']
      ip['ssv']=-abs(ip['ssv'])

      p=Parameters()
      if not all_params:
            d0 = [p.add(d, value=ip.pop(d), vary=1, min=lim[d][0], max=lim[d][1]) for d in depends]
            vary=0
      else:
            vary=1
            if method=='differential_evolution':
                  pass
            else:
                  aval = ip.pop('a'); zval = ip.pop('z')
                  p.add('a', value=aval, vary=1, min=lim['a'][0], max=lim['a'][1])
                  p.add('zperc', value=zval/aval, vary=1)
                  p.add('z', expr="zperc*a")

      p0 = [p.add(k, value=v, vary=vary, min=lim[k][0], max=lim[k][1]) for k, v in ip.items()]


      popt = minimize(recost, p, args=(y, ntrials), method='nelder', kws={'wts':wts}, options={'disp':disp, 'xtol':xtol, 'ftol':ftol, 'maxfev':maxfev})

      params = p.valuesdict()
      params['chi']=popt.chisqr
      params['rchi']=popt.redchi
      params['AIC']=popt.aic
      params['BIC']=popt.bic
      resid=popt.residual; yhat=y+resid
      
      if fitid is None:
            fitid = time.strftime('%H:%M:%S')
      
      with open('fit_report.txt', 'a') as f:
            f.write(str(fitid)+'\n')
            f.write(fit_report(popt, show_correl=False)+'\n')
            f.write('AIC: %.8f' % popt.aic)
            f.write('BIC: %.8f' % popt.bic)
            f.write('--'*20+'\n\n')
      return params, yhat

In [329]:
print lmfit.__version__

0.8.2


In [86]:
print fit_report(popt, show_correl=False)
print '--'*20+'\n\n'

[[Fit Statistics]]
    # function evals   = 7
    # data points      = 16
    # variables        = 5
    chi-square         = 0.020376541
    reduced chi-square = 0.002
[[Variables]]
    a:       0.44409409 (init= 0.4440941)
    zperc:   0.34732854 (init= 0.3473285)
    z:       0.15424655  == 'zperc*a'
    ssv:    -0.94733930 (init=-0.9473393)
    tr:      0.30487069 (init= 0.3048707)
    v:       1.12235977 (init= 1.12236)
----------------------------------------




In [72]:
popt, p = fit_reactive_model(y, inits=inits, all_params=1, wts=wts['bsl'], maxfev=2, disp=True, xtol=.5, ftol=.5)


In [47]:
fitid=None
with open('fit_report.txt', 'a') as f:
      if fitid is None:
            fitid = time.strftime('%H:%M:%S')
      f.write(str(fitid)+'\n')
      #f.write(fit_report(popt)+'\n\n\n')

In [93]:
a=inits['a']; tr=inits['tr']; v=inits['v']; ssv=inits['ssv']; z=inits['z']; 
ssd=np.arange(.2, .45, .05)
nss=1000
ntot=2000
tb=0.650
tau=.0005
si=.01
depends=None

In [89]:
from numpy.random import random_sample as rs

In [100]:
Pg

array([ 0.62548364,  0.60038691])

In [134]:
vec[0]<Pg[0]

array([[False, False,  True, False,  True],
       [False,  True,  True, False, False],
       [ True,  True,  True, False,  True]], dtype=bool)

In [140]:
#ncond = len(vv)
#vec = rs((ncond, 3, 5))
(vec.T<Pg).T

array([[[False, False,  True, False,  True],
        [False,  True,  True, False, False],
        [ True,  True,  True, False,  True]],

       [[ True,  True,  True, False, False],
        [ True,  True,  True, False,  True],
        [False, False,  True,  True,  True]]], dtype=bool)

In [182]:
rsg = rs((ncond, ntot, Tg))
DVg = z + np.cumsum(np.where((rsg.T < Pg).T, dx, -dx), axis=2)
DVgx = z + np.cumsum(np.where((rsg.T < Pg), dx, -dx).T, axis=2)

In [211]:

vv=np.array([v, v*.8])
ssv=-abs(ssv)
ncond=len(vv)
Pg = 0.5*(1 + vv*dx/si)
Tg = np.ceil((tb-tr)/tau).astype(int)

Ps = 0.5*(1 + ssv*dx/si)
Ts = np.ceil((tb-ssd)/tau).astype(int)

DVg = z + np.cumsum(np.where((rs((ncond, ntot, Tg)).T < Pg), dx, -dx).T, axis=2)
init_ss = np.array([np.array([DVc[:nss, ix] for ix in np.where(Ts<Tg, Tg-Ts, 0)]) for DVc in DVg])
DVs = init_ss[:, :, :, None] + np.cumsum(np.where(rs((ncond, nssd, nss, Ts.max()))<Ps, dx, -dx), axis=3)

In [177]:
DVs = init_ss[:, :, :, None] + np.cumsum(np.where(rs((ncond, nssd, nss, Ts.max()))<Ps, dx, -dx), axis=3)

In [212]:
grt = np.where(DVg[:, nss:, :].max(axis=2)>=a, tr + np.argmax(DVg[:, nss:, :]>=a, axis=2)*tau, np.nan)
ert = np.where(DVg[:, :nss, :].max(axis=2)>=a, tr + np.argmax(DVg[:, :nss, :]>=a, axis=2)*tau, np.nan)

ssrt = np.where(np.any(DVs<=0, axis=3), ssd[:, None]+np.argmax(DVs<=0, axis=3)*tau, np.nan)

In [ ]:
cg_quant = np.vstack([mq(rtc[rtc<tb], prob=p) for rtc in grt])
eg_quant = mq(np.hstack([np.extract(rte<ssi, rte) for ssi in ssrt]), prob=p)

In [215]:
gac = np.where(grt<tb,1,0).mean(axis=1)

In [248]:
 p=np.array([.1, .3, .5, .7, .9])

In [255]:
len(rte)

1000

In [253]:
rte[rte<rts]

IndexError: too many indices for array

In [261]:
erq = [mq(np.hstack([np.extract(ert[i]<srt, ert[i]) for srt in ssrt[i]]), prob=p) for i in range(len(ert))]

[array([ 0.5013707,  0.5275307,  0.5483707,  0.5683707,  0.5973707]),
 array([ 0.5273707,  0.5563707,  0.5813707,  0.6033707,  0.6301507])]

In [249]:
grq = np.vstack([mq(rtc[rtc<tb], prob=p) for rtc in grt])
eg_quant = np.vstack([mq(np.hstack([np.extract(rte<rts, rte) for rts in ssrt]), prob=p) for rte in ert])

IndexError: index 1046 is out of bounds for size 1000

In [289]:
#np.mean(np.hstack([srt for srt in ssrt[i]]) for i in range(len(ert))], axis=1)
len(ssrt.mean(axis=1))
c_ssrt = ssrt.mean(axis=1)
grq = np.vstack([mq(rtc[rtc<tb], prob=p) for rtc in grt])
erq = [mq(np.extract(ert[i]<c_ssrt[i], ert[i]), prob=p) for i in range(ncond)]

In [302]:
sacc = [1 - np.where(ert[i]<ssrt[i], 1, 0).mean(axis=1) for i in range(ncond)]

In [305]:
gac = np.where(grt<tb, 1, 0).mean(axis=1)

In [303]:
sacc

[array([ 0.998,  0.992,  0.946,  0.503,  0.122]),
 array([ 1.   ,  0.998,  0.988,  0.812,  0.464])]

In [243]:
sacc = 1 - np.where(np.vstack(ert)<c_ssrt, 1, 0).mean(axis=2)

ValueError: operands could not be broadcast together with shapes (2,1000) (2,5000) 

In [229]:
ert

array([[ 0.5233707,  0.5793707,  0.5533707, ...,  0.5613707,        nan,
         0.5223707],
       [ 0.6033707,  0.5953707,  0.5163707, ...,  0.6253707,  0.5233707,
               nan]])

In [91]:
nssd=len(ssd);
dx=np.sqrt(si*tau)

Pg = 0.5*(1 + v*dx/si)
Tg = np.ceil((tb-tr)/tau).astype(int)

Ps = 0.5*(1 + ssv*dx/si)
Ts = np.ceil((tb-ssd)/tau).astype(int)

DVg = z + np.cumsum(np.where(rs((ntot, Tg)) < Pg, dx, -dx), axis=1)

init_ss = np.array([DVg[:nss, ix] for ix in np.where(Ts<Tg, Tg-Ts, 0)])
DVs = init_ss[:, :, None] + np.cumsum(np.where(rs((nssd, nss, Ts.max()))<Ps, dx, -dx), axis=2)


In [213]:
ssrt

array([[[ 0.3565,  0.4775,  0.3785, ...,  0.3245,  0.3475,  0.3135],
        [ 0.4055,  0.3785,  0.4165, ...,  0.4405,  0.4365,  0.4315],
        [ 0.4835,  0.4035,  0.4115, ...,  0.4235,  0.4295,  0.4505],
        [ 0.6375,  0.5245,  0.5825, ...,  0.5665,  0.5135,  0.6015],
        [ 0.6515,  0.5455,  0.6585, ...,  0.8065,  0.5105,  0.7275]],

       [[ 0.3935,  0.3155,  0.3435, ...,  0.3085,  0.4055,  0.3485],
        [ 0.4115,  0.3645,  0.4095, ...,  0.3675,  0.4335,  0.3945],
        [ 0.4185,  0.4085,  0.4045, ...,  0.4765,  0.4485,  0.4305],
        [ 0.5175,  0.5435,  0.6165, ...,  0.6655,  0.6095,  0.5855],
        [ 0.5445,  0.7285,  0.7045, ...,  0.5985,  0.5725,  0.6525]]])