In [1]:
from radd import build
from radd.toolbox import theta

In [133]:
m = build.Model(data=prodf_store.prodata, kind='xpro', depends_on={'tr':'pGo'}, verbose=False)

In [135]:
m.make_optimizer(tol=1.e-5, multiopt=True)

In [138]:
m.optimize()

basinhopping step 0: f 0.537974
basinhopping step 1: f 0.537974 trial_f 3.29221 accepted 0  lowest_f 0.537974
basinhopping step 2: f 0.537974 trial_f 1.99576 accepted 0  lowest_f 0.537974
basinhopping step 3: f 0.537974 trial_f 1.92842 accepted 0  lowest_f 0.537974
basinhopping step 4: f 0.537974 trial_f 2.30038 accepted 0  lowest_f 0.537974
basinhopping step 5: f 0.537974 trial_f 1.47397 accepted 0  lowest_f 0.537974
basinhopping step 6: f 0.46798 trial_f 0.46798 accepted 1  lowest_f 0.46798
found new global minimum on step 6 with function value 0.46798
basinhopping step 7: f 0.740417 trial_f 0.740417 accepted 1  lowest_f 0.46798
basinhopping step 8: f 0.508124 trial_f 0.508124 accepted 1  lowest_f 0.46798
basinhopping step 9: f 0.781432 trial_f 0.781432 accepted 1  lowest_f 0.46798
adaptive stepsize: acceptance rate 0.400000 target 0.500000 new stepsize 0.063 old stepsize 0.07
basinhopping step 10: f 1.14895 trial_f 1.14895 accepted 1  lowest_f 0.46798
basinhopping step 11: f 1.14895

TypeError: float argument required, not numpy.ndarray

In [144]:
m.opt.residual

array([  3.00564e-02,   2.03126e-01,   5.20301e-01,   3.29221e-02,
         8.10022e-02,   9.62481e-02,   1.35944e-01,   7.90481e-02,
         3.59536e-02,   5.60621e-03,   1.28049e-04,   8.41333e-02,
         1.53367e-02,   1.42391e-02,   2.25971e-04,   8.65675e-04])

In [143]:
m.avg_y + m.opt.residual

array([ 0.9776 ,  0.9994 ,  1.07608,  0.38124,  0.20769,  0.18878,
        0.66081,  0.61801,  0.57893,  0.55053,  0.54542,  0.62439,
        0.55987,  0.55894,  0.5454 ,  0.54619])

In [145]:
m.avg_y

array([ 0.94754,  0.79627,  0.55578,  0.34832,  0.12668,  0.09254,
        0.52486,  0.53896,  0.54297,  0.54493,  0.54529,  0.54026,
        0.54454,  0.5447 ,  0.54518,  0.54532])

In [127]:
s.wts

array([  1.74539,   1.     ,   0.85377,   0.9899 ,   2.20041,   2.20041,
         0.20665,   0.31222,   0.53414,   1.85371,  19.6562 ,   0.09959,
         0.26758,   0.2767 ,  15.32465,   3.83484])

In [ ]:
sns.