In [14]:
from radd import build, models, fit, vis
from radd.toolbox import theta
from numpy import newaxis as na
from numpy import hstack as hs
from scipy.stats.distributions import norm, gamma
from numpy.random import random_sample as rs
from numpy import concatenate as concat
#!/usr/local/bin/env python
from __future__ import division
import os
import time
from copy import deepcopy
import numpy as np
import pandas as pd
from numpy import array
from radd import models
from radd.toolbox import theta
from radd.toolbox.messages import logger, global_logger
from lmfit import Parameters, minimize
from radd.CORE import RADDCore
from scipy.optimize import basinhopping, differential_evolution, brute


In [291]:
#os.mkdir('/Users/kyle/Dropbox/INTERACTIVE_R1/')
os.chdir('/Users/kyle/Dropbox/xINTERACT/')
m = build.Model(data=redf_store.redata, kind='interact')
m.make_optimizer(tol=1.e-2, maxfev=100, ntrials=5000, random_inits=False)

In [292]:
m.wts

array([  1.03249,  10.68561,   6.1261 ,   0.96949,   0.3851 ,   0.74263,
         1.08741,   0.91089,   0.83842,   0.86138,   0.9527 ,   0.31861,
         0.29348,   0.27133,   0.22974,   0.23311,   0.85181,  10.39935,
         6.61195,   1.2106 ,   0.49128,   0.55394,   1.0382 ,   0.97846,
         0.96614,   0.90873,   1.07851,   0.23561,   0.23643,   0.2566 ,
         0.24777,   0.27201])

In [288]:
m.optimize()

Optimization terminated successfully.
         Current function value: 0.003114
         Iterations: 23
         Function evaluations: 52
Optimization terminated successfully.
         Current function value: 0.007180
         Iterations: 10
         Function evaluations: 21


In [289]:
sims = m.simulator.sim_fx(m.popt).reshape(2,16)

for i in range(m.ncond):
      vis.plot_fits(m.y[i], m.fits.reshape(2,16)[i], kind='radd', save=True, savestr='_'.join([m.labels[i], 'INTERACTIVE_drift_w_hyp_FITS']))
      vis.plot_fits(m.y[i], sims[i], kind='radd', save=True, savestr='_'.join([m.labels[i], 'INTERACTIVE_drift_w_hyp_SIMS']))

In [278]:

%cd /Users/kyle/Dropbox/PROFITS2
m = build.Model(data=prodf_store.prodata, kind='xpro')
m.optimize(tol=1.e-7, maxfev=500, ntrials=10000, random_inits=True)

/Users/kyle/Dropbox/PROFITS2
this tie is blacknot


In [280]:
vis.plot_fits(m.y, m.fits, kind='pro', save=True, savestr='pro_vhyp')

In [271]:
m.opt.__hop_around__(niter=10, nsuccess=25)

this tie is blacknot


{'a': 0.48758096, 'tr': 0.29223792, 'v': 1.69870371, 'xb': 1.84080798}

In [245]:
yh = m.opt.simulator.sim_fx(m.opt.contender)
#vis.plot_fits(m.y, yh, kind='pro')

In [257]:
mm = build.Model(data=prodf_store.prodata, kind='xpro')
mm.get_wts()

In [258]:
mm.wts

array([ 1.74539,  1.     ,  0.85377,  0.9899 ,  2.20041,  2.20041,
        0.20665,  0.31222,  0.53414,  1.85371,  3.15268,  0.09959,
        0.26758,  0.2767 ,  0.94393,  0.94393])

In [256]:
m.y

array([ 0.93593,  0.76048,  0.48493,  0.24628,  0.03778,  0.00566,
        0.52662,  0.53943,  0.54339,  0.54519,  0.55181,  0.54193,
        0.54467,  0.54504,  0.54584,  0.55422])

In [237]:
sim.sim_fx(m.inits)

array([ 0.28331,  0.51924,  0.53224,  0.53924,  0.54824,  0.55524])

In [235]:
sim.ncond

6

In [172]:
p = m.inits

m.make_optimizer(tol=1.e-7, maxfev=100, ntrials=5000)
opt = m.opt
m.make_simulator()
sim = m.simulator
m.inits ={'a':    0.4875809,
'xb':   1.8408079,
'tr':   0.2922379,
'v':array([1.39423800,1.53535562,1.65557698,1.75515234,1.88985329,1.92243114])}

In [127]:
y = array([0.9475, 0.7962, 0.5557, 0.3483, 0.1266, 0.0925, 0.5248, 0.5389, 0.5429, 0.5449, 0.5452, 0.5402, 0.5445, 0.5447, 0.5451, 0.5453])

In [143]:
wts = array([1.7453, 1.0, 0.8537, 0.9899, 2.2004, 2.2004, 0.2066, 0.3122, 0.5341, 1.8537, 3.1526, 0.0995, 0.2675, 0.2767, 0.9439, 0.9439])


In [181]:
(sim.sim_fx(m.inits)-y)*wts

array([-0.00894,  0.04294,  0.0575 ,  0.00816,  0.00936, -0.01335,
       -0.00404, -0.00676, -0.0089 , -0.01976, -0.00619, -0.00189,
       -0.00328, -0.00151, -0.00081,  0.00277])

In [129]:
yhat = array([0.9322, 0.8025, 0.5650, 0.3487, 0.1517, 0.0777, 0.5203, 0.5315, 0.5332, 0.5251, 0.5419, 0.5381, 0.5409, 0.5427, 0.5442, 0.5476])
y = array([0.9475, 0.7962, 0.5557, 0.3483, 0.1266, 0.0925, 0.5248, 0.5389, 0.5429, 0.5449, 0.5452, 0.5402, 0.5445, 0.5447, 0.5451, 0.5453])

In [130]:
yhat-y

array([-0.0153,  0.0063,  0.0093,  0.0004,  0.0251, -0.0148, -0.0045,
       -0.0074, -0.0097, -0.0198, -0.0033, -0.0021, -0.0036, -0.002 ,
       -0.0009,  0.0023])

# Hop Around

In [52]:
opt.perform_basinhopping

array([ 0.94754,  0.52486,  0.53896,  0.54297,  0.54493,  0.54529])

In [47]:
opt.perform_basinhopping(popt)

IndexError: index 1 is out of bounds for axis 0 with size 1

In [44]:
xfmin

[[9.3905023601513413e-09], [0.61204762825284753]]

In [104]:
opt.contender

{'a': array([ 0.44515]),
 'tr': array([ 0.29395]),
 'v': array([ 1.74299]),
 'xb': array([ 0.03663])}

In [183]:
yhat = array([0.4579, 0.5252, 0.5363, 0.5403, 0.5389, 0.5492])
y = array([0.4778, 0.5270, 0.5403, 0.5442, 0.5451, 0.5452])
a:    0.48758096
xb:   1.84080798
tr:   0.29223792
v:    1.69870371

In [185]:
prev = {'a': array([ .48758096]),
 'tr': array([0.29223792]),
 'v': array([ 1.69870371]),
 'xb': array([ 1.84080798])}

In [197]:
opt.simulator.ncond=1

#opt.simulator.sim_fx(contender)[1:]

In [196]:
contender=dict(deepcopy({'a': array([ 0.44515]),
 'tr': array([ 0.29395]),
 'v': array([ 1.74299]),
 'xb': array([ 0.03663])}))
ctd = dict(deepcopy(contender))

In [198]:
opt.simulator.sim_fx(ctd)

array([ 0.43818,  0.51395,  0.52595,  0.53395,  0.54195,  0.54795])

In [200]:
plt.plot(opt.simulator.sim_fx(ctd)[1:], label='contender')
plt.plot(yhat[1:], label='yhat')
plt.plot(y[1:], label='y')
plt.gca().legend()

In [202]:
opt.__hop_around__(niter=2, nsuccess=1)

{'a': array([ 0.47533,  0.52947]), 'xb': array([ 1.77801,  3.66273]), 'tr': array([ 0.31044,  0.28731]), 'v': array([ 0.26743,  0.66407])}


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [69]:
opt.contender

{'a': array([ 0.44515]),
 'tr': array([ 0.29395]),
 'v': array([ 1.74299]),
 'xb': array([ 0.03663])}

In [105]:
#def __hop_around__(opt, niter=2, nsuccess=1):

niter=2; nsuccess=1
      
inits = opt.inits.keys()
bnd = theta.get_bounds(kind=opt.kind, tb=opt.fitparams['tb'])
random_inits = {pkey: theta.init_distributions(pkey, bnd[pkey], nrvs=niter, kind=opt.kind) for pkey in inits}

opt.logs, xpopt, xfmin = [], [], []
for i in range(niter):
      p={pkey: random_inits[pkey][i] for pkey in inits}
      popt, fmin = perform_basinhopping(opt, p=p, is_flat=True, nsuccess=nsuccess)
      yhat = opt.simulator.sim_fx(popt)
      cost = opt.simulator.__cost_fx__(popt)
      opt.logs.append({'pkeys':popt.keys(), 'pvals':popt.values(), 'fmin':fmin, 'cost':cost, 'yhat':yhat})
      xpopt.append(popt)
      xfmin.append(fmin)

#global_logger(opt.logs)

# get the best fitting set of params
opt.contender = xpopt[np.argmin(xfmin)]
popt=dict(deepcopy(opt.contender))
# test against original inits and return better
#p1 = opt.__test_global__(popt, nsuccess=nsuccess)

{'a': array([ 0.43757]), 'xb': array([ 1.593]), 'tr': array([ 0.25162]), 'v': array([ 0.60022])}
{'a': array([ 0.43757]), 'xb': array([ 1.593]), 'tr': array([ 0.25162]), 'v': array([ 0.60022])}


KeyboardInterrupt: 

In [112]:
print opt.simulator.sim_fx(opt.contender)
print opt.flat_y

[ 0.4922   0.50717  0.52345  0.53145  0.54045  0.54745]
[ 0.47786  0.52706  0.54031  0.54426  0.54516  0.54528]


# Perform Basinhopping

In [107]:
#def perform_basinhopping(opt, p, is_flat=True, nsuccess=20, stepsize=.05):
is_flat=True
nsuccess=20; stepsize=.05
fp = opt.fitparams
if is_flat:
      bdata=[opt.flat_y]
      bwts=[fp['flat_wts']]
      ncond=1
      basin_keys=p.keys()
      p={k:array([v]) for k,v in p.items()}
else:
      basin_keys=opt.pc_map.keys()
      # get condition wise y vectors
      bdata, bwts = opt.__prep_basin_data__()
      ncond=sim.ncond
print bdata
print bwts
mkwargs = {"method":"Nelder-Mead", 'jac':True}
opt.simulator.__prep_global__(method='basinhopping', basin_keys=basin_keys)

xopt, funcmin = [], []
for i in range(ncond):
      #print p
      params = {k: v[i] for k,v in p.items()}
      x=[params[pk] for pk in basin_keys]
      opt.simulator.basin_params = params
      opt.simulator.y = bdata[i]
      opt.simulator.wts = bwts[i]
      # run basinhopping on simulator.basinhopping_minimizer func
      #out = basinhopping(opt.simulator.basinhopping_minimizer, x, stepsize=stepsize, minimizer_kwargs=mkwargs, niter_success=nsuccess)
      xopt.append(out.x)
      funcmin.append(out.fun)

for i, pk in enumerate(basin_keys):
      p[pk]=array([xopt[c][i] for c in range(ncond)])
if opt.xbasin!=[]:
      opt.xbasin.extend(funcmin)
else:
      opt.xbasin = funcmin
return p, funcmin

[array([ 0.47786,  0.52706,  0.54031,  0.54426,  0.54516,  0.54528])]
[array([ 1.49831,  0.15312,  0.2899 ,  0.40542,  1.39882,  2.0483 ])]
{'a': array([ 0.43757]), 'xb': array([ 1.593]), 'tr': array([ 0.25162]), 'v': array([ 0.60022])}


NameError: name 'out' is not defined

# Test Global

In [227]:
#def __test_global__(opt, popt, nsuccess=10):

cost = lambda x: np.sum(m.opt.simulator.__cost_fx__(x))**2

m.opt.simulator.ncond=1;
m.opt.simulator.wts=fp['flat_wts']
m.opt.simulator.y=opt.flat_y

yh0 = [cost(popt) for i in range(nsuccess)]
yh1 = [cost(prev) for i in range(nsuccess)]
tests = np.array([1 if c0<c1 else 0 for c0, c1 in zip(yh0, yh1)])

if np.sum(tests)>=(nsuccess/2.0):
      print "great success, borat"
      print tests[np.argmin(tests)]
else:
      print "this tie is blacknot"
      


this tie is blacknot


In [229]:
yh0

[0.013854561742284393,
 0.0077662897730978817,
 0.010984779647712271,
 0.0076925891410583444,
 0.0029642452942470325,
 0.0023170889997168979,
 0.005793568418855562,
 0.0027714201799541437,
 0.0017526876521499145,
 0.0053033867953401837,
 0.0056578030339094988,
 0.0069772988083155974,
 0.010692003452351257,
 0.00470629104716012,
 0.0040244242895302465,
 0.0091804820881864879,
 0.0025047767183781324,
 0.0079078881204092573,
 0.0019937711030222779,
 0.001758990316875139]

In [216]:
prev = {'a': array([ .48758096]),
 'tr': array([0.29223792]),
 'v': array([ 1.69870371]),
 'xb': array([ 1.84080798])}

In [226]:
opt.simulator.sim_fx(prev)

array([ 0.5066 ,  0.51724,  0.52824,  0.53524,  0.54124,  0.54624])

In [218]:
popt

{'a': array([ 0.44515]),
 'tr': array([ 0.29395]),
 'v': array([ 1.74299]),
 'xb': array([ 0.03663])}

In [223]:
opt.simulator.sim_fx(popt)

array([ 0.44658,  0.51099,  0.52395,  0.53195,  0.54195,  0.54795])

In [225]:
opt.simulator.sim_fx(opt.inits)

array([ 0.07803,  0.4985 ,  0.5105 ,  0.5195 ,  0.5305 ,  0.5405 ])

In [219]:
opt.inits

{'a': array([ 0.4748]),
 'tr': array([ 0.2725]),
 'v': array([ 1.6961]),
 'xb': array([ 2.])}