In [153]:
from radd import build, models, fit, vis
from radd.toolbox import theta
from numpy import newaxis as na
from numpy import hstack as hs
from scipy.stats.distributions import norm, gamma
from numpy.random import random_sample as rs
from numpy import concatenate as concat
from scipy.stats.mstats import mquantiles as mq
from scipy.stats import scoreatpercentile as sp
from scipy.stats import percentileofscore as pos
from radd.toolbox import analyze

In [506]:
simrt = sim_bsl

In [605]:
list(set(m.inits) - set(m.opt.simulator.pvc))

['ssv', 'z']

In [610]:
m = build.Model(data=redf_store.redata, kind='xradd')
m.optimize(tol=1.e-5, maxfev=2000, random_inits=True)

this tie is blacknot


In [614]:
m.popt

{'a': array([ 0.44576,  0.44576]),
 'ssv': -0.92351652681310947,
 'tr': array([ 0.30785,  0.30785]),
 'v': array([ 1.07845,  1.03264], dtype=float32),
 'v_bsl': 1.0784494252637529,
 'v_pnl': 1.0326407503356068,
 'xb': array([ 0.10061,  0.10061]),
 'z': 0.1595912396735753}

In [613]:
sims = m.simulator.sim_fx(m.popt).reshape(2,16)

for i in range(m.ncond):
      vis.plot_fits(m.y[i], m.fits.reshape(2,16)[i], kind='radd', save=True, savestr='_'.join([m.labels[i], 'drift_w_hyp_FITS']))
      vis.plot_fits(m.y[i], sims[i], kind='radd', save=True, savestr='_'.join([m.labels[i], 'drift_w_hyp_SIMS']))

In [600]:
p = m.opt.storage['p2']
#p['z'] = p['z'][0]
p['ssv'] = p['ssv'][0]
m.opt.simulator.sim_fx(p)

(2, 5, 5000)


array([ 0.9313 ,  0.9988 ,  0.9924 ,  0.9544 ,  0.5668 ,  0.1662 ,
        0.52191,  0.54991,  0.57191,  0.59391,  0.62591,  0.51191,
        0.53991,  0.55791,  0.57991,  0.60991,  0.9987 ,  0.9952 ,
        0.9716 ,  0.8674 ,  0.217  ,  0.0298 ,  0.48791,  0.50991,
        0.52591,  0.54391,  0.57391,  0.48391,  0.50391,  0.51991,
        0.53791,  0.56391])

In [581]:
m.opt.wts

array([ 1.     ,  2.     ,  1.5    ,  1.     ,  0.5    ,  0.5    ,
        1.08741,  0.91089,  0.83842,  0.86138,  0.9527 ,  0.31861,
        0.29348,  0.27133,  0.22974,  0.23311,  1.     ,  2.     ,
        1.5    ,  1.     ,  0.5    ,  0.5    ,  1.0382 ,  0.97846,
        0.96614,  0.90873,  1.07851,  0.23561,  0.23643,  0.2566 ,
        0.24777,  0.27201])

In [579]:
%pwd

u'/Users/kyle/Dropbox/INTERACT'

In [6]:
#os.mkdir('/Users/kyle/Dropbox/INTERACT/')
os.chdir('/Users/kyle/Dropbox/INTERACT/')
m = build.Model(data=redf_store.redata, kind='interact')
p = m.inits
m.make_optimizer(tol=1.e-7, maxfev=100, ntrials=5000)

In [ ]:
m.optimize(tol=1.e-3,)

In [14]:
m.opt.simulator.sim_fx(m.inits, )

array([ 0.92479,  0.99916,  0.99523,  0.93506,  0.56448,  0.15071,
        0.52098,  0.54677,  0.56493,  0.58217,  0.60543,  0.51584,
        0.53844,  0.55327,  0.57067,  0.59465])

In [773]:
DVg, DVs, gss = sim.sim_fx(m.inits, analyze=False)

In [851]:
yhat = sim.sim_fx(m.inits)

In [852]:
for i in range(sim.ncond):
      vis.plot_fits(m.y[i], yhat.reshape(2,16)[i], kind='radd')

In [823]:
ssgdec.reshape(ncond, nssd*int(nss/nssd))

array([[ 0.175,  0.314,  0.243, ...,  0.182,  0.338,  0.221],
       [ 0.222,  0.265,  0.229, ...,  0.242,  0.14 ,  0.258]])

In [827]:
DVg, DVs, gss = sim.sim_fx(m.inits, analyze=False)

nss = sim.nss; prob = sim.prob
ssd = sim.ssd; tb = sim.tb
ncond = sim.ncond; nssd = sim.nssd

sscancel = ssd + p['sso']

# in contrast w/ RADD/IRM, where full DVg can be
# used to estimate go RT and acc. (rt<tb) DVg is
# influenced by DVs on ss trials. so must be sliced
DVg = DVg[:,nss:]

ssDVg = DVg[:,:nss].reshape(ncond, nssd, int(nss/nssd),-1)
# Go process (No SS Trials)
gdec = sim.resp_up(DVg, p['a'])
gort = sim.RT(p['tr'], gdec)

# Go process SS Trials
ssgdec = sim.ss_resp_up(ssDVg, p['a'])
ssgdec = ssgdec.reshape(ncond, nssd*int(nss/nssd))
ss_gort = sim.RT(p['tr'], ssgdec).reshape(ncond,nssd,int(nss/nssd))

eq = sim.RTQ(zip(ss_gort,[tb]*ncond))
gq = sim.RTQ(zip(gort,[tb]*ncond))
gacc = np.nanmean(np.where(gort<tb, 1, 0), axis=1)
sacc = np.where(ss_gort<sscancel[:,na], 0, 1).mean(axis=2)
yhat = hs([hs([i[ii] for i in [gacc,sacc,gq,eq]]) for ii in range(sim.ncond)])


In [828]:
yhat = 

array([ 0.9994,  1.    ,  0.949 ,  0.676 ,  0.282 ,  0.071 ,  0.394 ,
        0.423 ,  0.448 ,  0.474 ,  0.516 ,  0.394 ,  0.423 ,  0.448 ,
        0.474 ,  0.516 ,  0.9994,  1.    ,  0.957 ,  0.687 ,  0.285 ,
        0.062 ,  0.395 ,  0.425 ,  0.449 ,  0.476 ,  0.517 ,  0.395 ,
        0.425 ,  0.449 ,  0.476 ,  0.517 ])

In [810]:
sscancel

array([ 0.33,  0.38,  0.43,  0.48,  0.53])

In [808]:
ss_gort<sscancel[:,na]

array([[[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]]], dtype=bool)

In [797]:
yhat

array([ 0.999 ,  0.057 ,  0.237 ,  0.628 ,  0.949 ,  1.    ,  0.396 ,
        0.425 ,  0.447 ,  0.473 ,  0.516 ,  0.5064,  0.5304,  0.5514,
        0.5724,  0.6014,  0.9992,  0.068 ,  0.235 ,  0.647 ,  0.958 ,
        0.999 ,  0.396 ,  0.426 ,  0.448 ,  0.474 ,  0.518 ,  0.5074,
        0.5344,  0.5554,  0.5774,  0.6114])

In [750]:
ert = gort[:,:sim.nss].reshape(sim.ncond, sim.nssd, int(sim.nss/sim.nssd))

array([[[   nan,    nan,    nan, ...,    nan,    nan,    nan],
        [   nan,    nan,    nan, ...,    nan,    nan,    nan],
        [   nan,    nan,    nan, ...,  0.402,    nan,    nan],
        [   nan,  0.431,  0.435, ...,  0.436,  0.469,  0.406],
        [ 0.429,  0.47 ,  0.436, ...,  0.494,  0.411,  0.375]],

       [[   nan,    nan,    nan, ...,    nan,    nan,    nan],
        [   nan,    nan,    nan, ...,    nan,    nan,    nan],
        [   nan,    nan,    nan, ...,    nan,  0.409,    nan],
        [   nan,    nan,  0.476, ...,  0.458,  0.403,  0.437],
        [ 0.417,  0.386,  0.478, ...,    nan,    nan,  0.363]]])

In [695]:
array([m.inits['sso']+m.ssd])

array([[ 0.33,  0.38,  0.43,  0.48,  0.53]])

In [801]:
sscancel

array([ 0.33,  0.38,  0.43,  0.48,  0.53])

In [711]:
plt.plot(gss[0,4, -25])
plt.plot(DVs[0,4, -2])
plt.gca().set_ylim(0, m.inits['a'][0])

(0, 0.24265999999999999)

In [194]:
m.inits = {'a':0.4441, 'v':array([1.1078, 1.0651]), 'ssv':-0.9473, 'tr':0.3049, 'z':0.1542}

In [196]:
yhat

array([ 0.9627 ,  0.9985 ,  0.991  ,  0.9515 ,  0.5175 ,  0.125  ,
        0.5114 ,  0.5394 ,  0.5614 ,  0.5834 ,  0.6184 ,  0.50412,
        0.5274 ,  0.5474 ,  0.5674 ,  0.6004 ,  0.937  ,  0.9995 ,
        0.9945 ,  0.9635 ,  0.5865 ,  0.1725 ,  0.5174 ,  0.5464 ,
        0.5694 ,  0.5924 ,  0.6244 ,  0.5114 ,  0.5364 ,  0.5544 ,
        0.5794 ,  0.6084 ])

In [123]:
DVg.shape

(2, 10000, 698)

In [250]:
resp_go = lambda trace, a: np.argmax((trace.T>=a).T, axis=2)*.0005
resp_ss = lambda trace, a: np.argmax((trace.T>=a).T, axis=3)*.0005
resp_lo = lambda trace: np.argmax((trace.T<=0).T, axis=3)*.0005

RT = lambda ontime, rbool: ontime[:, None]+(rbool*np.where(rbool==0, np.nan, 1))
RTQ = lambda zpd: map((lambda x:mq(x[0][x[0]<x[1]], prob)), zpd)

In [16]:
from numpy import newaxis as na

In [175]:
init_ss.shape

(2, 5, 908)

In [205]:
p = sim.vectorize_params(p)
Pg = 0.5*(1 + p['v']*sim.dx/sim.si)
Ps = 0.5*(1 + p['ssv']*sim.dx/sim.si)
Tg = np.ceil((sim.tb-p['tr'])/sim.dt).astype(int)
Ts = np.ceil((sim.tb-sim.ssd)/sim.dt).astype(int)
nt = np.max(np.hstack([Tg,Ts]))

t = np.cumsum([sim.dt]*nt)
sim.xtb = sim.temporal_dynamics(p, t)

nt = np.max(np.hstack([Tg,Ts]))

DVg = sim.base+(sim.xtb[:,na]*np.cumsum(np.where((rs((sim.ncond, sim.ntot, nt)).T<Pg), sim.dx,-sim.dx).T, axis=2))

#init_ss = DVg[0,0,0]*np.ones((sim.nss))[:,:,:,None]
#init_ss = array([[DVg[i,  :sim.nss, ix] for ix in np.zeros(sim.nssd)] for i, DVc in enumerate(DVg)])
DVs = base+np.cumsum(np.where(rs((sim.ncond, int(sim.nss*sim.nssd), nt))<Ps, sim.dx, -sim.dx), axis=2)

#sim.analyze_reactive(DVg, DVs, p)

In [ ]:
m.inits

In [353]:
m = build.Model(data=redf_store.redata, kind='radd')
m.inits = {'a':0.4441, 'v':array([1.1078, 1.0651]), 'ssv':-0.9473, 'tr':0.3049, 'z':0.1542}
m.make_simulator()
sim = m.simulator

In [354]:
sim.sim_fx(m.inits, analyze=True)

array([ 0.9594 ,  0.999  ,  0.993  ,  0.955  ,  0.516  ,  0.1265 ,
        0.5114 ,  0.5384 ,  0.5594 ,  0.5824 ,  0.6174 ,  0.5034 ,
        0.5274 ,  0.5474 ,  0.5684 ,  0.5974 ,  0.9336 ,  0.999  ,
        0.9965 ,  0.97   ,  0.576  ,  0.1715 ,  0.5194 ,  0.5474 ,
        0.5694 ,  0.5924 ,  0.62438,  0.5094 ,  0.5354 ,  0.5574 ,
        0.5774 ,  0.60558])

In [345]:
DVs[0, 3]

array([[ 0.15196,  0.1542 ,  0.15644, ...,  0.49855,  0.49632,  0.49855],
       [ 0.15644,  0.1542 ,  0.15644, ...,  0.588  ,  0.59023,  0.59247],
       [ 0.15196,  0.14973,  0.14749, ...,  0.45383,  0.45607,  0.45831],
       ..., 
       [ 0.15644,  0.15867,  0.15644, ...,  0.55669,  0.55446,  0.55669],
       [ 0.15196,  0.14973,  0.15196, ...,  0.56564,  0.56787,  0.57011],
       [ 0.15196,  0.1542 ,  0.15644, ...,  0.55669,  0.55893,  0.56116]])

In [260]:
p=m.inits

p = sim.vectorize_params(p)
Pg, Tg = sim.__update_go_process__(p)
Ps, Ts = sim.__update_stop_process__(p)

DVg = sim.base+(sim.xtb[:,na]*np.cumsum(np.where((rs((sim.ncond, sim.ntot, Tg.max())).T<Pg), sim.dx,-sim.dx).T, axis=2))
print DVg.shape
# INITIALIZE DVs FROM DVg(t=SSD)
init_ss = array([[DVc[i, :sim.nss, ix] for ix in np.where(Ts<Tg[i], Tg[i]-Ts, 0)] for i, DVc in enumerate(DVg.reshape(2, sim.nssd, sim.nss, Tg.max()))])
print init_ss.shape

DVs = init_ss[:,:,:,na]+np.cumsum(np.where(rs((sim.ncond, sim.nssd, sim.nss, Ts.max()))<Ps, sim.dx, -sim.dx), axis=3)
print DVs.shape

#yhat = sim.analyze_reactive(DVg, DVs, p)

(2, 10000, 698)
(2, 5, 2000)
(2, 5, 2000, 908)


In [257]:
nss = sim.nss; prob = sim.prob
ssd = sim.ssd; tb = sim.tb
ncond = sim.ncond; nssd = sim.nssd

gdec = sim.resp_up(DVg, p['a'])
gort = sim.RT(p['tr'], gdec)
if 'radd' in sim.kind:
      sdec = resp_lo(DVs)
      ssrt = RT(ssd, sdec)
      ert = gort.reshape(2, 5, 2000)

In [255]:
ssrt.shape

(2, 5, 2000)

In [258]:
                    
gort = sim.RT(p['tr'], gdec)
eq = sim.RTQ(zip(ert, ssrt))
gq = sim.RTQ(zip(gort,[tb]*ncond))
gac = np.nanmean(np.where(gort<tb, 1, 0), axis=1)
sacc = np.where(ert<ssrt, 0, 1).mean(axis=2)

In [259]:
sacc

array([[ 0.9995,  0.991 ,  0.9565,  0.5255,  0.0955],
       [ 0.9995,  0.9945,  0.9625,  0.5725,  0.1545]])

In [230]:
DVs.shape
yhat


array([ 0.9614 ,  0.9995 ,  0.992  ,  0.958  ,  0.5335 ,  0.1175 ,
        0.5114 ,  0.5394 ,  0.5614 ,  0.5834 ,  0.6164 ,  0.5054 ,
        0.5294 ,  0.5484 ,  0.5694 ,  0.6014 ,  0.9375 ,  1.     ,
        0.992  ,  0.959  ,  0.561  ,  0.135  ,  0.5184 ,  0.5474 ,
        0.5694 ,  0.5924 ,  0.6244 ,  0.5074 ,  0.5354 ,  0.5544 ,
        0.5764 ,  0.61138])

In [210]:
sdec = resp_ss(DVs, p['a'])
RT(sim.ssd, sdec.reshape(2, 5, 2000))

array([[[ 0.408,  0.39 ,  0.432, ...,  0.406,  0.404,  0.402],
        [ 0.421,  0.401,  0.443, ...,  0.401,  0.484,  0.45 ],
        [ 0.53 ,  0.494,  0.552, ...,  0.549,  0.543,  0.547],
        [ 0.593,  0.497,  0.594, ...,  0.694,  0.535,  0.65 ],
        [ 0.595,  0.696,  0.566, ...,  0.653,  0.578,  0.61 ]],

       [[ 0.456,  0.392,  0.391, ...,  0.385,  0.573,  0.388],
        [ 0.376,  0.441,  0.447, ...,  0.41 ,  0.451,  0.419],
        [ 0.569,  0.54 ,  0.521, ...,  0.476,  0.534,  0.511],
        [ 0.492,  0.559,  0.6  , ...,  0.565,  0.588,  0.597],
        [ 0.6  ,  0.57 ,  0.572, ...,  0.634,  0.681,  0.691]]])

In [148]:
x = sim.simulate_irace(p, analyze=False)

In [ ]:
DVg.reshape()

In [150]:
DVg.shape

(2, 10000, 698)

In [7]:
DVg, DVs = simulate_irace(sim, p)

In [143]:
nss = sim.nss; prob = sim.prob
ssd = sim.ssd; tb = sim.tb
ncond = sim.ncond

gdec = resp_go(DVg, p['a'])
sdec = resp_ss(DVg, p['a'])
gort = RT(p['tr'], gdec)
ssrt = RT(ssd, sdec)

ert = gort[:, :nss][:, None] * np.ones_like(ssrt)
eq = sim.RTQ(zip(ert, ssrt))
gq = sim.RTQ(zip(gort,[tb]*ncond))
gac = np.nanmean(np.where(gort<tb, 1, 0), axis=1)
sacc = np.where(ert<ssrt, 0, 1).mean(axis=2)


ValueError: axis(=3) out of bounds

In [51]:
diff

array([ 210,  110,   10,  -90, -190])

In [73]:
np.max(hs([Tg, Ts]))

908

In [406]:
def __update_params__(sim, p):
      """ update Pg (probability of DVg +dx) and Tg (num go process timepoints)
      for go process and get get dynamic bias signal if 'x' model
      """
      Pg = 0.5*(1 + p['v']*sim.dx/sim.si)
      Ps = 0.5*(1 + p['ssv']*sim.dx/sim.si)
      Tg = np.ceil((sim.tb-p['tr'])/sim.dt).astype(int)
      Ts = np.ceil((sim.tb-p['sso'])/sim.dt).astype(int)
      nt = np.max(hs([Tg, Ts]))
      t = np.cumsum([sim.dt]*nt)
      xtb = sim.temporal_dynamics(p, t)
      return Pg, Tg, Ps, Ts, xtb


In [408]:
Pg, Tg, Ps, Ts, xtb = __update_params__(sim, p)
Ts

array([668, 568, 468, 368, 268])

In [585]:
m = build.Model(data=redf_store.redata, kind='irace')
p = m.inits
m.make_simulator()
sim = m.simulator
sim.ssd=sim.fitparams['ssd']

In [587]:
m.inits['z']=0

In [639]:
# ensure parameters are all vectorized
ssonset = .12
p = sim.vectorize_params(p)
p['sso']=sim.ssd+ssonset

Pg, Tg, Ps, Ts, xtb = __update_params__(sim, p)
sim.bound = p['a']
sim.onset = p['tr']
sso=p['sso']
ncond=sim.ncond; ntot=sim.ntot; dx=sim.dx;
base=sim.base; nss = sim.nss; nssd=sim.nssd;
ssd=sim.ssd; 

nt = np.max(hs([Tg, Ts]))
gomoments = xtb[:,na]*np.where((rs((ncond, ntot, nt)).T<Pg), dx,-dx).T
ssmoments = np.where(rs((ncond, nssd, nss, nt))<Ps, dx, -dx)


Tss = [[s if s<g else g-1 for s in Ts] for g in Tg]
diff = Tg[:,na]-Tss

null = [[ssmoments[ci, ssdi, :, :diff[ci,ssdi]].fill(0) for ssdi in range(sim.nssd)] for ci in range(sim.ncond)]

DVg = base+xtb[:,na]* np.cumsum(gomoments, axis=2)
DVs = base+np.cumsum(ssmoments, axis=3)

dvg = DVg.reshape(sim.ncond, sim.nssd, sim.nss, nt)
dvs = base+np.cumsum(ssmoments, axis=3)

gss = dvg-dvs



In [637]:
null = [[ssmoments[ci, ssdi, :, :diff[ci,ssdi]].fill(0) for ssdi in range(sim.nssd)] for ci in range(sim.ncond)]
dvg = DVg.reshape(sim.ncond, sim.nssd, sim.nss, nt)
dvs = base+np.cumsum(ssmoments, axis=3)

In [634]:
ssmoments[ci, ssdi, :, :diff[ci,ssdi]].fill(0)

In [638]:
ssmoments

array([[[[ 0.     , -0.00224, -0.00224, ...,  0.00224,  0.00224,  0.00224],
         [ 0.     , -0.00224,  0.00224, ..., -0.00224, -0.00224, -0.00224],
         [ 0.     , -0.00224,  0.00224, ..., -0.00224,  0.00224, -0.00224],
         ..., 
         [ 0.     ,  0.00224, -0.00224, ...,  0.00224, -0.00224,  0.00224],
         [ 0.     ,  0.00224, -0.00224, ...,  0.00224,  0.00224,  0.00224],
         [ 0.     , -0.00224,  0.00224, ..., -0.00224, -0.00224,  0.00224]],

        [[ 0.     ,  0.     ,  0.     , ...,  0.00224, -0.00224, -0.00224],
         [ 0.     ,  0.     ,  0.     , ...,  0.00224, -0.00224,  0.00224],
         [ 0.     ,  0.     ,  0.     , ..., -0.00224,  0.00224,  0.00224],
         ..., 
         [ 0.     ,  0.     ,  0.     , ..., -0.00224, -0.00224,  0.00224],
         [ 0.     ,  0.     ,  0.     , ..., -0.00224,  0.00224, -0.00224],
         [ 0.     ,  0.     ,  0.     , ..., -0.00224, -0.00224, -0.00224]],

        [[ 0.     ,  0.     ,  0.     , ...,  0.00224,

In [ ]:
np.append(np.zeros(diff[i]), base+np.cumsum(np.where(rs((ncond, nssd, nss, Tss[i]))<Ps, dx, -dx), axis=3)

In [618]:
for ci in range(sim.ncond):
      for ssdi in range(sim.nssd):
gsi = [[ssmoments[ci, ssdi, :, :diff[ci,ssdi]].fill(0) for ssdi in range(sim.nssd)] for ci in range(sim.ncond)]
            #ssval_onset = DVs[ci, ssdi, :, diff[ci,ssdi]:]
            

In [628]:
ssmoments[ci, ssdi, :, :diff[ci,ssdi]].fill(0)

In [629]:
pssmoments

array([[[[ 0.     ,  0.00224,  0.00224, ...,  0.00224, -0.00224, -0.00224],
         [ 0.     , -0.00224, -0.00224, ...,  0.00224,  0.00224,  0.00224],
         [ 0.     ,  0.00224,  0.00224, ...,  0.00224,  0.00224, -0.00224],
         ..., 
         [ 0.     , -0.00224, -0.00224, ...,  0.00224, -0.00224, -0.00224],
         [ 0.     , -0.00224,  0.00224, ..., -0.00224,  0.00224, -0.00224],
         [ 0.     ,  0.00224,  0.00224, ...,  0.00224,  0.00224,  0.00224]],

        [[ 0.     ,  0.     ,  0.     , ..., -0.00224, -0.00224, -0.00224],
         [ 0.     ,  0.     ,  0.     , ...,  0.00224,  0.00224,  0.00224],
         [ 0.     ,  0.     ,  0.     , ...,  0.00224,  0.00224,  0.00224],
         ..., 
         [ 0.     ,  0.     ,  0.     , ...,  0.00224, -0.00224, -0.00224],
         [ 0.     ,  0.     ,  0.     , ...,  0.00224, -0.00224, -0.00224],
         [ 0.     ,  0.     ,  0.     , ..., -0.00224,  0.00224, -0.00224]],

        [[ 0.     ,  0.     ,  0.     , ...,  0.00224,

In [627]:
[[ssmoments.place([ci, ssdi, :, :diff[ci,ssdi]].fill(0) for ssdi in range(sim.nssd)] for ci in range(sim.ncond)]

[[None, None, None, None, None], [None, None, None, None, None]]

In [619]:
dvs = base+np.cumsum(ssmoments, axis=3)

In [603]:
dvg = DVg.reshape(sim.ncond, sim.nssd, sim.nss, nt)
dvs = base+np.cumsum(ssmoments, axis=3)

In [620]:
gss = dvg-dvs

In [597]:
DVs.shape

(2, 5, 2000, 668)

In [573]:
early = gss[0,0]
late = gss[0,-1]

In [626]:
plt.plot(gss[0,5,1])

IndexError: index 5 is out of bounds for axis 1 with size 5

In [555]:
[[s if s<g else g-1 for s in Ts] for g in Tg]

[[637, 568, 468, 368, 268], [637, 568, 468, 368, 268]]

In [415]:
DVg.shape

(2, 10000, 668)

In [416]:
Ts

array([668, 568, 468, 368, 268])

In [425]:
diff

array([[  30,  -70, -170, -270, -370],
       [  30,  -70, -170, -270, -370]])

In [430]:
diff = Ts-Tg[:,na]
r = [[d if d>0 else tg+d for d in diff[ix]] for ix, tg in enumerate(Tg)]

In [522]:
i = [array([0,1])]*sim.nssd
j = [array([si]) for si in range(sim.nssd)]
#r = [[[array([d])]*nss if d>0 else [array([tg+d])]*nss for d in diff[ix]] for ix, tg in enumerate(Tg)]
r = np.array([[d if d>0 else tg+d for d in diff[ix]] for ix, tg in enumerate(Tg)])

In [523]:
r.flatten()

array([[ 30, 568, 468, 368, 268],
       [ 30, 568, 468, 368, 268]])

In [537]:
i = array([[0,1]*sim.nssd])
j = np.sort(array([np.arange(sim.nssd)]*sim.ncond).flatten())
r = np.array([[d if d>0 else tg+d for d in diff[ix]] for ix, tg in enumerate(Tg)])
r = r.reshape(1,10)

In [545]:
DVg.shape

(2, 10000, 668)

In [548]:
dvg=DVg.reshape(sim.ncond, sim.nssd, sim.nss, Ts.max())
i = array([[0,1]*sim.nssd])
j = np.sort(array([np.arange(sim.nssd)]*sim.ncond).flatten())
r = np.array([[d if d>0 else tg+d for d in diff[ix]] for ix, tg in enumerate(Tg)])
r = r.reshape(1,10)
dvg[i,j,:,r]

array([[[ 0.18364,  0.17917,  0.1747 , ...,  0.16128,  0.16575,  0.15234],
        [ 0.41619,  0.48327,  0.48327, ...,  0.47433,  0.41619,  0.36253],
        [ 0.43855,  0.38936,  0.38489, ...,  0.34464,  0.42066,  0.34911],
        ..., 
        [ 0.4475 ,  0.31781,  0.46539, ...,  0.33569,  0.45197,  0.38042],
        [ 0.367  ,  0.37594,  0.37594, ...,  0.29992,  0.35358,  0.24178],
        [ 0.34017,  0.25967,  0.27756, ...,  0.24178,  0.36253,  0.24178]]])

In [450]:
dvg[:,:,:,r].shape

KeyboardInterrupt: 

[array([0, 1]), array([0, 1]), array([0, 1]), array([0, 1]), array([0, 1])]

In [499]:
dvg[i,j,]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (10,) (5,) 

In [386]:
[array([0,1])]*2

[array([0, 1]), array([0, 1])]

In [381]:
sim.nssd

5

In [94]:




ss_list, go_list=[],[]
for i, (s, g) in enumerate(zip(ds, dg)):
      diff = Ts-Tg[i]
      pad_go = diff[diff>0]
      pad_ss = abs(diff[diff<0])

      go_list.extend([concat((np.zeros((nss, gp)), g[i]), axis=1) for gp in pad_go])
      go_list.extend([g[x] for x in range(len(pad_ss))])

      ss_list.extend([concat((np.zeros((nss, abs(spad))), s[i,:,-(Tg[i]-spad):]), axis=1) for spad in pad_ss])
      ss_list.extend([s[i,:,-tss:] for tss in Ts[:len(pad_go)]])

r = map((lambda x: np.cumsum((x[0] + x[1]), axis=1)), zip(go_list, ss_list))

ValueError: operands could not be broadcast together with shapes (1000,1118) (1000,698) 

In [115]:
sim.nss

5000

In [109]:
DVgR = DVg.reshape(sim.ncond, sim.nssd, (sim.nss/sim.nssd), sim)
for i in range(sim.ncond):
      for ii in range(sim.nssd):
            ix = Ts[i]-Tg[i]
            if ix<0:
                  DVgR[i, :, :abs(ix)]=0
            else:
                  DVgR[i, :, ix:]=0

In [108]:
DVs - DVg

array([[[ 0.     , -0.00224, -0.00447, ..., -0.85957, -0.86483, -0.87457],
        [-0.00224, -0.00447,  0.00224, ..., -0.65969, -0.65552, -0.65582],
        [-0.00447, -0.00671, -0.00894, ..., -1.02   , -1.02537, -1.03075],
        ..., 
        [-2.32775, -2.41495, -2.35011, ..., -3.27868, -2.91234, -3.14527],
        [-2.33445, -2.42166, -2.35682, ..., -3.47668, -3.11977, -3.36661],
        [-2.33669, -2.41943, -2.35011, ..., -3.43711, -3.08017, -3.31769]],

       [[-0.00447, -0.00671, -0.00447, ..., -0.73431, -0.73468, -0.73985],
        [-0.00224, -0.00447, -0.00671, ..., -0.83514, -0.83558, -0.83153],
        [-0.00447, -0.00671, -0.     , ..., -0.65619, -0.66578, -0.6709 ],
        ..., 
        [-2.45744, -2.56253, -2.34564, ..., -2.89965, -3.06593, -3.23669],
        [-2.45967, -2.56477, -2.3434 , ..., -2.8618 , -3.02805, -3.19431],
        [-2.45744, -2.56701, -2.34564, ..., -2.67604, -2.83769, -2.99899]]])

In [ ]:
x = DVg[0]
x