In [3]:
#!/usr/local/bin/env python
from __future__ import division
import time
import numpy as np
from lmfit import Parameters, minimize, fit_report
from numpy.random import random_sample as rs
from scipy.stats.mstats import mquantiles as mq

from radd import fit, build, fitre, fit_flat
p = {k:v for k,v in redf_store['rebsl_boot_popt'].items()}
theta = {k:v for k,v in redf_store['rebsl_boot_popt'].items()}
vval = p['v']
p['v0'], p['v1'] = np.array([vval*1.05, vval*.95])
data = redf_store['redata']
y = data.groupby('Cond').apply(build.rangl_data, kind='reactive')
y2 = build.rangl_data(data, kind='reactive')

NameError: name 'budasild' is not defined

In [2]:
asdf
datdf = data.groupby(['idx']).apply(build.rangl_data, kind=m.kind)
#np.vstack([datdf.apply(m.ifx, kind=m.kind).values for i in indx])
m.dat = datdf.mean(axis=0)

NameError: name 'asdf' is not defined

In [197]:
delays = m.delays
qp_cols = ['Go'] + delays +['c5','c25','c50','c75','c95'] + ['e5','e25','e50','e75','e95']

ixdf = pd.DataFrame({'idx': data.idx.unique(), 'flat': 'flat'}, columns=['idx', 'flat'])
m.observed = pd.concat([ixdf, pd.DataFrame(data=np.vstack(datdf.values), columns=qp_cols)], axis=1)

In [198]:
m.observed

idx  flat      Go    200    250    300    350    400      c5     c25  \
0    28  flat  0.9835  1.000  1.000  0.950  0.700  0.050  5.0522  5.4506   
1    29  flat  0.9793  1.000  1.000  1.000  0.825  0.175  5.3145  5.4670   
2    30  flat  0.9050  1.000  1.000  1.000  0.725  0.350  5.1852  5.7165   
3    31  flat  0.9835  1.000  1.000  1.000  0.750  0.150  5.3173  5.4522   
4    32  flat  0.9587  1.000  1.000  1.000  0.750  0.100  5.4493  5.7169   
5    33  flat  0.9256  1.000  1.000  0.850  0.375  0.100  5.1825  5.3190   
6    34  flat  0.9669  1.000  0.975  1.000  0.575  0.075  5.1805  5.3352   
7    35  flat  0.9711  1.000  1.000  0.950  0.475  0.000  5.0696  5.3209   
8    36  flat  0.9669  1.000  0.950  0.825  0.500  0.075  5.0503  5.3177   
9    37  flat  0.9793  1.000  1.000  0.975  0.600  0.000  5.3174  5.5285   
10   38  flat  0.9793  1.000  0.975  0.925  0.525  0.075  5.1828  5.4503   
11   39  flat  0.9669  0.975  0.975  0.825  0.175  0.025  4.8950  5.1852   
12   40  flat  0.9793  1.000  1.000  0.950  0.500  0.075  5.1851  5.5831   
13   41  flat  0.9876  1.000  1.000  1.000  0.900  0.125  5.4670  5.7177   
14   42  flat  0.9876  1.000  1.000  0.875  0.325  0.050  4.9354  5.1853   
..  ...   ...     ...    ...    ...    ...    ...    ...     ...     ...   
46   78  flat  0.4587  1.000  0.975  0.975  0.925  0.625  5.5846  5.8514   
47   79  flat  0.9339  1.000  1.000  0.975  0.775  0.375  5.1859  5.5850   
48   80  flat  0.9215  1.000  1.000  0.975  0.800  0.275  5.4507  5.7222   
49   81  flat  0.9050  1.000  1.000  0.950  0.775  0.175  5.3160  5.5785   
50   82  flat  0.9008  0.975  1.000  0.975  0.525  0.175  5.0492  5.4496   
51   83  flat  1.0000  1.000  1.000  0.850  0.375  0.000  5.0519  5.3194   
52   84  flat  0.9380  0.975  1.000  0.900  0.375  0.075  5.1832  5.3356   
53   85  flat  0.9876  1.000  0.975  0.600  0.100  0.050  4.8394  5.1836   
54   86  flat  0.9091  1.000  0.950  0.975  0.675  0.125  5.0510  5.3881   
55   87  flat  1.0000  1.000  1.000  0.825  0.325  0.025  5.0499  5.1882   
56   88  flat  0.7645  1.000  0.975  0.900  0.725  0.325  5.0675  5.5845   
57   89  flat  0.9669  1.000  1.000  1.000  0.925  0.450  5.5827  5.8506   
58   90  flat  0.9628  1.000  1.000  0.975  0.825  0.125  5.4512  5.7177   
59   95  flat  0.9876  1.000  0.900  0.700  0.400  0.050  4.7846  5.0512   
60   97  flat  0.9793  0.975  1.000  0.950  0.475  0.025  5.0508  5.3165   

       c50     c75     c95      e5     e25     e50     e75     e95  
0   5.5847  5.8503  6.1167  5.0518  5.3177  5.4524  5.5854  5.8443  
1   5.7174  5.8526  6.2468  5.3145  5.4505  5.5842  5.7177  5.9776  
2   5.8527  6.1174  6.3841  5.3180  5.5846  5.7194  5.9840  6.1176  
3   5.5867  5.8501  6.1174  5.1605  5.4052  5.4576  5.7138  5.9847  
4   5.8517  5.9855  6.3823  5.1842  5.4519  5.6475  5.8506  6.0014  
5   5.5833  5.7197  6.1175  4.9348  5.3170  5.4513  5.5848  5.8519  
6   5.6586  5.8506  6.2507  5.3052  5.4504  5.5841  5.7175  5.8729  
7   5.4537  5.5898  5.9873  5.1831  5.3161  5.3217  5.4550  5.7205  
8   5.5840  5.8506  6.1216  4.9165  5.1815  5.3187  5.5825  5.9944  
9   5.7166  5.8507  6.1174  5.2015  5.4507  5.5843  5.7179  5.9994  
10  5.5850  5.8506  6.1173  5.0506  5.3178  5.4507  5.7174  5.9839  
11  5.4503  5.5848  5.8553  4.6514  5.1828  5.3177  5.5836  5.9153  
12  5.7176  5.8517  6.1173  5.2265  5.4492  5.5836  5.7172  5.9842  
13  5.8526  5.9860  6.2512  5.3600  5.5844  5.7179  5.8517  6.0751  
14  5.4431  5.5837  5.7184  4.9165  5.1828  5.1866  5.3186  5.5843  
..     ...     ...     ...     ...     ...     ...     ...     ...  
46  6.1168  6.2515  6.4344  0.0100  4.8852  5.7160  5.9843  6.3289  
47  5.8508  6.1170  6.3807  5.0518  5.3171  5.5854  5.7394  5.9813  
48  5.9842  6.1232  6.3844  5.4508  5.5842  5.7180  5.9856  6.2176  
49  5.7175  5.9823  6.1290  5.2590  5.5833  5.7170  5.8505  6.1169  
50  5.5847  5.8500  6.1171  5.1845  5.3181  5.5838  5.7177  5.8751  
51  5.5833  5.7174  5.9834  5.0503  5.3181  5.4506  5

In [147]:
y.values

array([ array([ 0.94201326,  0.99426228,  0.98278689,  0.8967213 ,  0.50491804,
        0.10327869,  5.05134583,  5.32041454,  5.58484221,  5.85082388,
        6.24409151,  4.91785669,  5.18539333,  5.45045137,  5.58876324,
        5.9842329 ], dtype=float32),
       array([ 0.92724562,  0.9934426 ,  0.98524588,  0.92540985,  0.5942623 ,
        0.18114755,  5.18260765,  5.45125008,  5.71676922,  5.97715616,
        6.25050116,  5.04096556,  5.31758499,  5.45331287,  5.71764088,
        5.98438311], dtype=float32)], dtype=object)

In [216]:
m = build.Model(data=data, inits=p, kind='reactive', prepare=True)

preparing reactive model to fit on subjects data


In [221]:
wtc, wte = m.wts[0], m.wts[1]

In [222]:
wtc

array([ 0.85994972,  0.93462945,  0.89867025,  0.8657587 ,  0.8045123 ])

In [160]:
try:
      y=np.vstack(yy)
except Exception: 
      print "pass"
      pass

In [150]:
yy = y[0]

In [92]:
wtc, wte = m.wts.T[:5].T, m.wts.T[5:].T
y=np.vstack(y)

#cost = np.hstack([y[:6]-yhat[:6], wtc*y[6:11]-wtc*yhat[6:11], wte*y[11:]-wte*yhat[11:]]).astype(np.float32)
cost = np.hstack(np.hstack([y[:, :6] - yhat[:, :6], wtc*y[:, 6:11] - wtc*yhat[:, 6:11], wte*y[:, 11:] - wte*yhat[:, 11:]])).astype(np.float32)

In [94]:
m = build.Model()
m.fit_model(fit_average=True, ntrials=5000, )

2

In [93]:
cost.reshape(ncond, int(len(cost)/ncond))

array([[-0.04198674, -0.00473772, -0.00321311, -0.0292787 ,  0.10291804,
         0.03627869,  0.04052041,  0.04853142,  0.11296447,  0.16321591,
         0.20858899,  0.02168902,  0.06730543,  0.08688566,  0.02766473,
         0.12001715],
       [ 0.00524562, -0.00455741, -0.00975412, -0.04059014,  0.0052623 ,
         0.00414755, -0.01987585, -0.05200838, -0.00151746,  0.04028806,
         0.03316311,  0.03365685,  0.04734683,  0.01341143,  0.0670687 ,
         0.08363365]], dtype=float32)

In [64]:
m.wts.T[:5].T[0][1]

0.85581923991684972

In [80]:
m.wts.T[:5].T * y[:, 6:11]
m.wts.T[5:].T * y[:, 11:]

array([[ 4.29654889,  4.55331313,  4.47010118,  5.39162268,  5.41818863],
       [ 4.88208522,  4.53930072,  4.47679416,  5.54229194,  5.63366493]])

In [48]:
y[:, 6:11]

array([[ 5.05134583,  5.32041454,  5.58484221,  5.85082388,  6.24409151],
       [ 5.18260765,  5.45125008,  5.71676922,  5.97715616,  6.25050116]], dtype=float32)

In [252]:
def recost_single(theta, y, ntrials=2000, wts=None):

      """
      simulate and cost function for a flat model all params = 1
      
      simulate data via <simulate_full> and return weighted
      cost between observed (y) and simulated values (yhat).

      returned vector is implicitly used by lmfit minimize
      routine invoked in <optimize> which then submits the
      SSE of the already weighted cost to a Nelder-Mead Simplex
      optimization.


      args:
            theta (dict):           param dict
            y (np.array):           NCond x 16 array of observed
                                    values entered into cost f(x)
            wts (np.array)          weights separately applied to
                                    correct and error RT quantile
                                    comparison
      returns:
            cost:                   weighted difference bw
                                    observed (y) and simulated (yhat)
      """

      p = {k:theta[k] for k in theta.keys()}

      ssd=np.arange(.2, .45, .05);
      prob=np.array([.1, .3, .5, .7, .9])

      yhat = simulate_single(p['a'], p['tr'], p['v'], -abs(p['ssv']),  p['z'], prob=prob, ssd=ssd, ntot=ntrials)

      wtc, wte = m.wts[0], m.wts[1]
      cost = np.hstack(np.hstack([y[:6] - yhat[:6], wtc*y[6:11] - wtc*yhat[6:11], wte*y[11:] - wte*yhat[11:]])).astype(np.float32)
      return cost


In [262]:
m = build.Model(data=data, inits=theta, depends_on = {'v':'Cond'}, prepare=True)

preparing reactive model to fit on subjects data


In [267]:
m.wts

array([[ 0.85057508,  0.85581924,  0.80039883,  0.92151512,  0.8677305 ,
         0.23334144,  0.30360656,  0.24355159,  0.07791647,  0.24467036],
       [ 0.94201328,  0.83270821,  0.78309863,  0.92724563,  0.90131412,
         0.28508601,  0.25749045,  0.06398404,  0.25411172,  0.26409836]])

In [266]:
np.ones_like(m.wts).shape
#np.ones((2,10))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [259]:
yhat = fit_flat.recost_flat(theta, y[0])

In [260]:
yhat

array([-0.02298674, -0.00573772, -0.00921311, -0.04727869,  0.00891804,
        0.00527869, -0.03236116, -0.05289244,  0.01113522,  0.06711689,
        0.09038453, -0.11585029, -0.09831365, -0.00325561, -0.05494374,
        0.00472592], dtype=float32)

In [246]:
def simulate_single(a, tr, v, ssv, z, prob=np.array([.1, .3, .5, .7, .9]), ssd=np.arange(.2, .45, .05), ntot=2000, tb=0.650, dt=.0005, si=.01, return_traces = False):
      
      dx=np.sqrt(si*dt)
      nssd = len(ssd)
      nss = int(.5*ntot)

      Pg = 0.5*(1 + v*dx/si)
      Tg = np.ceil((tb-tr)/dt).astype(int)
      Ps = 0.5*(1 + ssv*dx/si)
      Ts = np.ceil((tb-ssd)/dt).astype(int)
      
      # SINGLE CONDITION, ALL SSD
      DVg = z + np.cumsum(np.where(rs((ntot, Tg)) < Pg, dx, -dx), axis=1)
      init_ss = np.array([DVg[:nss, ix] for ix in np.where(Ts<Tg, Tg-Ts, 0)])
      DVs = init_ss[:, :, None] + np.cumsum(np.where(rs((nssd, nss, Ts.max()))<Ps, dx, -dx), axis=2)
      
      grt = np.where(DVg[nss:, :].max(axis=1)>=a, tr + np.argmax(DVg[nss:, :]>=a, axis=1)*dt, np.nan)
      ert = np.where(DVg[:nss, :].max(axis=1)>=a, tr + np.argmax(DVg[:nss, :]>=a, axis=1)*dt, np.nan)
      ssrt = np.where(np.any(DVs<=0, axis=2), ssd[:, None]+np.argmax(DVs<=0, axis=2)*dt, np.nan)
      # compute RT quantiles for correct and error resp.
      gq = mq(grt[grt<tb], prob=prob)
      eq = mq(np.hstack([np.extract(ert<ssi, ert) for ssi in ssrt]), prob=prob)
      # Get response and stop accuracy information
      gac = np.where(grt<tb,1,0).mean()
      sacc = 1 - np.where(ert<ssrt, 1, 0).mean(axis=1)
      
      return np.hstack([gac, sacc, gq*10, eq*10])     

In [230]:
def simulate_full(a, tr, v, ssv, z, analyze=True, ncond=1, prob=np.array([.1, .3, .5, .7, .9]), ssd=np.arange(.2, .45, .05), ntot=2000, tb=0.650, dt=.0005, si=.01):
      """

      Simulates all Conditions, SSD, trials, timepoints simultaneously.
      Vectorized operations are set up so that any of the parameters can be
      a single float or a vector of floats (i.e., when simulating/fitting multiple
      conditions differentiated by the value of one or more model parameters)

      args:
            a, tr, v, ssv, z (float/array):     model parameters
            ssd  (array):                       full set of stop signal delays
            nss  (int):                         number of stop trials
            ntot (int):                         number of total trials
            tb (float):                         time boundary

      returns:

            DVg (Go Process):             3d array for all conditions, trials, timepoints
                                          (i.e. DVg = [COND [NTrials [NTime]]] )
                                          All conditions are simulated simultaneously (i.e., BSL & PNL)

            DVs (Stop Process):           4d array for all conditions, SSD, SS trials, timepoints.
                                          i.e. ( DVs = [COND [SSD [nSSTrials [NTime]]]] )
                                          All ss decision traces are initiated from DVg[Cond](t=SSD | SSD<tr)

      Output can be passed to <analyze_reactive_full()> to extract
      expected values to be entered into the cost f(x)
      """

      print tr
      print v
      nssd = len(ssd)
      nss = int(.5*ntot)
      print nss
      print nssd
      dx=np.sqrt(si*dt)
      Pg = 0.5*(1 + v*dx/si)
      Tg = np.ceil((tb-tr)/dt).astype(int)

      Ps = 0.5*(1 + ssv*dx/si)
      Ts = np.ceil((tb-ssd)/dt).astype(int)

      # a/tr/v Bias: ALL CONDITIONS, ALL SSD
      DVg = z + np.cumsum(np.where((rs((ncond, ntot, Tg.max())).T < Pg), dx, -dx).T, axis=2)
      init_ss = np.array([[DVc[:nss, ix] for ix in np.where(Ts<Tg[i], Tg[i]-Ts, 0)] for i, DVc in enumerate(DVg)])
      DVs = init_ss[:, :, :, None] + np.cumsum(np.where(rs((nss, Ts.max()))<Ps, dx, -dx), axis=1)

      # ALL CONDITIONS, ALL SSD
      grt = (tr + (np.where(DVg[:, nss:, :].max(axis=2)>=a, np.argmax(DVg[:, nss:, :]>=a, axis=2)*dt, np.nan).T)).T
      ert = (tr + (np.where(DVg[:, :nss, :].max(axis=2)>=a, np.argmax(DVg[:, :nss, :]>=a, axis=2)*dt, np.nan).T)).T
      ssrt = np.where(np.any(DVs<=0, axis=3), ssd[:, None]+np.argmax(DVs<=0, axis=3)*dt, np.nan)

      #collapse across SSD and get average ssrt vector for each condition
      c_ssrt = ssrt.mean(axis=1)

      # compute RT quantiles for correct and error resp.
      gq = np.vstack([mq(rtc[rtc<tb], prob=prob)*10 for rtc in grt])
      eq = np.array([mq(np.extract(ert[i]<c_ssrt[i], ert[i]), prob=prob)*10 for i in range(ncond)])

      # Get response and stop accuracy information
      gac = np.mean(np.where(grt<tb, 1, 0), axis=1)
      sacc = np.array([1 - np.where(ert[i]<ssrt[i], 1, 0).mean(axis=1) for i in range(ncond)])

      return [gac, sacc, gq, eq]#np.array([np.hstack([i[ii] for i in [gac, sacc, gq, eq]]) for ii in range(ncond)])