In [71]:
from radd import build

In [123]:
1.5*.001

0.0015

In [32]:
sns.distplot(pro.query('choice=="go"').pivot_table('rt', 'idx'))#, 'pGo')
ixrt = pro.query('choice=="go"').pivot_table('rt', 'idx')

In [128]:
dat[1]

array([], dtype=float64)

In [158]:
pro.query('choice=="go"&rt>.5').rt.hist(bins=90)#, kde=False, norm_hist=True, bins=50)
#sns.distplot(dat[1][dat[1]>.5], kde=False, norm_hist=True, bins=20)#plt.gca().set_xlim(.45,.6)

In [27]:
pro.query('choice=="go"&rt<.555').rt

0.5296765677325582

In [24]:
sns.distplot(pro.query('idx==41 & choice=="go"').rt)

In [84]:
from radd import theta
theta=reload(theta)
build=reload(build)
apopt={'a': array([ 0.2979]), 'xb': array([ 0.91365]), 'tr': array([ 0.29971]), 'v': array([ 1.12735])}
trpopt={'a': array([ 0.62868]), 'xb': array([ 0.64083]), 'tr': array([ 0.12783]), 'v': array([ 1.42112])}
vpopt={'a': array([ 0.48986]), 'xb': array([ 1.51129]), 'tr': array([ 0.29207]), 'v': array([ 1.72645])}


In [85]:
m = build.Model(data=pro, kind='xpro', depends_on={'tr':'pGo'}, inits=apopt)

In [137]:
m = build.Model(data=pro, kind='xpro', depends_on={'v':'pGo', 'xb':'pGo'})

In [487]:
m.make_optimizer()

In [582]:
m=build.Model(kind='xdpm', data=redata)

In [583]:
popt={'a': array([ 0.53625,  0.53625]), 'v_pnl': 1.2435812523041054, 'v': array([ 1.2887 ,  1.24358]), 'xb': array([ 0.87761,  0.87761]), 'ssv': -0.9839646215235698, 'tr': array([ 0.17801,  0.17801]), 'v_bsl': 1.2886965219271527}

In [584]:
delays = np.append(np.array([[c]*nss for c in sd]), [1000]*nss*nssd)

In [580]:
np.tile(delays,2)[:10001]

array([ 200,  200,  200, ..., 1000, 1000,  200])

In [587]:
x = m.simulate(analyze=False, p=popt)

In [590]:
1-x.groupby(['cond', 'ssd']).mean()

response      rt
cond ssd                   
bsl  200     1.0000  0.4342
     250     1.0000  0.4342
     300     0.9310  0.4342
     350     0.4720  0.4342
     400     0.1090  0.4342
     1000    0.0350  0.4332
pnl  200     1.0000  0.4236
     250     1.0000  0.4236
     300     0.9470  0.4236
     350     0.5860  0.4236
     400     0.1750  0.4236
     1000    0.0698  0.4232

In [596]:
ttype=np.tile(array(['stop']*5000 + ['go']*5000),2)

In [598]:
ttype.shape

(20000,)

In [507]:
x.groupby('cond').mean().gort

cond
bsl    0.5666
pnl    0.5765
Name: gort, dtype: float64

In [508]:
redata.query('response==1 & acc==1').groupby('Cond').mean().rt

Cond
bsl    0.5603
pnl    0.5673
Name: rt, dtype: float64

In [542]:
ert.reshape(2, 5000)

array([[     nan,  0.57101,  0.55601, ...,  0.56501,  0.58901,  0.56201],
       [ 0.55301,  0.58001,  0.64001, ...,  0.59501,  0.57401,  0.59201]])

In [549]:
np.vstack(ssrt.shape

(2, 5, 1000)

In [543]:
rt = np.concatenate([ert.reshape(2, 5000), gort[:, nssd*nss:]], axis=1)

In [552]:
ssrt.shape

(2, 5, 1000)

In [523]:
np.where(ert<ssrt, 1, 0).reshape(2,5000)

array([[0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]])

In [547]:
resp = np.concatenate([np.where(ert<ssrt, 1, 0).reshape(2,5000), gacc[:, nssd*nss:]], axis=1)

In [548]:
resp.shape

(2, 10000)

In [545]:
rt.shape

(2, 10000)

In [496]:
len(m.labels*(sim.ntot/sim.ncond))

10000

In [472]:
m.make_simulator()
m.simulate(a)

array([ 0.9731 ,  1.     ,  1.     ,  0.927  ,  0.472  ,  0.103  ,
        0.52301,  0.54851,  0.56501,  0.58601,  0.61301,  0.51401,
        0.53651,  0.55751,  0.57401,  0.60251,  0.9411 ,  1.     ,
        1.     ,  0.946  ,  0.569  ,  0.161  ,  0.53201,  0.56051,
        0.57701,  0.59651,  0.62501,  0.52001,  0.54851,  0.56501,
        0.58301,  0.61151])

In [460]:
x[0].shape

(2, 10000, 315)

In [455]:
x.groupby(['ssd', 'C').mean().response

ssd
200    0.000
250    0.000
300    0.030
350    0.370
400    0.784
Name: response, dtype: float64

In [449]:
for k in x.keys():
      print len(x[k])

10000
10000
10000
10000
10000


In [426]:
sd=[int(d) for d in ssd*1000]
out={'ssd':np.hstack([[c]*nss for c in sd]*nc),
'response':np.hstack(np.vstack(sacc)),
'ssrt':np.hstack(np.vstack(ssrt)),
'ert':np.hstack(np.vstack(ert)), 
'gort':np.hstack(gort)}



In [434]:
ssrt.shape

(2, 5, 1000)

In [439]:
np.nanmean(np.hstack(np.vstack(ssrt))[:5000])

0.46049656079304069

In [440]:
np.nanmean(ssrt[0])

0.46049656079304069

In [441]:
pd.DataFrame(out).shape

(10000, 3)

In [425]:
len(out['response'])

10000

In [424]:
len(out['ssrt'])

10000

In [414]:
pd.DataFrame(np.hstack(x[-1]).T, columns=[int(d) for d in ssd*1000])
n

200  250  300  350  400
0       1    1    1    1    0
1       1    1    1    1    0
2       1    1    1    1    0
3       1    1    1    1    1
4       1    1    1    1    1
5       1    1    0    0    0
6       1    1    1    0    0
7       1    1    1    1    0
8       1    1    1    0    0
9       1    1    1    0    0
10      1    1    0    0    1
11      1    1    1    0    0
12      1    1    1    0    0
13      1    1    0    0    0
14      1    1    1    0    0
...   ...  ...  ...  ...  ...
1985    1    1    1    1    0
1986    1    1    1    1    0
1987    1    1    1    1    1
1988    1    1    1    1    1
1989    1    1    1    1    0
1990    1    1    1    1    1
1991    1    1    1    0    0
1992    1    1    1    1    1
1993    1    1    1    0    0
1994    1    1    1    1    1
1995    1    1    1    1    1
1996    1    1    1    0    0
1997    1    1    1    1    1
1998    1    1    1    0    0
1999    1    1    1    0    0

[2000 rows x 5 columns]

In [395]:
x = m.simulate(analyze=False, all_data=True)

2
5
1000


In [382]:
x

array([ 0.8945 ,  1.     ,  0.999  ,  0.967  ,  0.612  ,  0.196  ,
        0.53801,  0.56501,  0.58601,  0.60701,  0.63101,  0.52907,
        0.55601,  0.57401,  0.59501,  0.61901,  0.8149 ,  1.     ,
        1.     ,  0.977  ,  0.709  ,  0.297  ,  0.54701,  0.57701,
        0.59501,  0.61601,  0.63701,  0.53501,  0.56501,  0.58301,
        0.60101,  0.62801])

In [176]:
DVg, DVs = sim.sim_fx(p=m.inits, analyze=False)

In [178]:
p=m.inits

In [384]:
prob=sim.prob;  ssd=sim.ssd;
tb=sim.tb;  nc=sim.ncond;
nss=sim.nss; nssd=sim.nssd

if 'sso' in p.keys():
      ssd = ssd + p['sso']
gdec = sim.resp_up(DVg, p['a'])
if 'irace' in sim.kind:
      sdec = sim.ss_resp_up(DVs, p['a'])
else:
      sdec = sim.resp_lo(DVs)
gort = sim.RT(p['tr'], gdec)
ssrt = sim.RT(ssd, sdec)
ert = np.tile(gort[:,:nss],nssd).reshape(nc, nssd, nss)
gacc = np.where(gort<tb, 1, 0)
sacc = np.where(ert<ssrt, 0, 1)

In [322]:
ertx = ert[0,0]

In [ ]:
np.

In [328]:
ssrtx = pd.DataFrame(np.vstack(ssrt).T)


In [340]:
ertx=pd.Series(ertx)

In [ ]:
ert = [pd.Series(ert[i, np.where(ert[i]<ssrt[i], True, False)]) for i in range(nc)]

In [357]:
ertdf = pd.concat([pd.Series(ert[i, np.where(ert[i]<ssrt[i], True, False)]) for i in range(nc)], axis=1)
ertdf.columns=
gort = pd.DataFrame(gort.T, columns=m.labels)

In [386]:
r = map((lambda z: z[0][z[0]<z[1]]), es)

In [387]:
es = zip(ert, ssrt)
x = lambda z: z[0][z[0]<z[1]]
r = map(x, es)

In [389]:
ert

array([[[     nan,  0.57101,  0.55601, ...,  0.56501,  0.58901,  0.56201],
        [     nan,  0.57101,  0.55601, ...,  0.56501,  0.58901,  0.56201],
        [     nan,  0.57101,  0.55601, ...,  0.56501,  0.58901,  0.56201],
        [     nan,  0.57101,  0.55601, ...,  0.56501,  0.58901,  0.56201],
        [     nan,  0.57101,  0.55601, ...,  0.56501,  0.58901,  0.56201]],

       [[ 0.55301,  0.58001,  0.64001, ...,  0.59501,  0.57401,  0.59201],
        [ 0.55301,  0.58001,  0.64001, ...,  0.59501,  0.57401,  0.59201],
        [ 0.55301,  0.58001,  0.64001, ...,  0.59501,  0.57401,  0.59201],
        [ 0.55301,  0.58001,  0.64001, ...,  0.59501,  0.57401,  0.59201],
        [ 0.55301,  0.58001,  0.64001, ...,  0.59501,  0.57401,  0.59201]]])

In [376]:
gort

array([[     nan,  0.57101,  0.55601, ...,  0.61901,  0.56801,  0.61301],
       [ 0.55301,  0.58001,  0.64001, ...,  0.61601,  0.60101,  0.62501]])

In [373]:
r[1].shape

(1019,)

In [362]:
gort = pd.DataFrame(gort.T, columns=m.labels)


bsl    pnl
0       NaN  0.553
1     0.571  0.580
2     0.556  0.640
3     0.532  0.649
4     0.583  0.577
5     0.628  0.589
6     0.535  0.634
7     0.604    NaN
8     0.541  0.613
9     0.625    NaN
10    0.613  0.583
11    0.589  0.643
12    0.586    NaN
13    0.646    NaN
14    0.568  0.595
...     ...    ...
9985  0.640  0.571
9986  0.610  0.613
9987  0.553  0.649
9988  0.631  0.628
9989  0.613  0.499
9990  0.616  0.568
9991    NaN  0.604
9992  0.574  0.571
9993    NaN  0.649
9994  0.637  0.637
9995  0.577  0.637
9996  0.604  0.574
9997  0.619  0.616
9998  0.568  0.601
9999  0.613  0.625

[10000 rows x 2 columns]

In [358]:
ertdf.columns=m.labels
gort=

In [359]:
ertdf.mean()

bsl    0.5725
pnl    0.5833
dtype: float64

In [278]:
gort.shape

(2, 10000)

In [279]:
ssrt.shape

(2, 5, 1000)

In [216]:
x = np.nan_to_num(sacc.reshape(2,5000))
xx = np.nan_to_num(ssrt.reshape(2,5000))

In [226]:
xx.shape

(2, 5000)

In [258]:
ssrt = pd.DataFrame(np.vstack(ssrt).T, columns=columns)

In [262]:
ssrt.shape

(1000, 10)

In [264]:
ert = ert.reshape(1000, 10)

In [272]:

ssrt.mean().T - (ssrt.columns*.001)

200    0.0287
250    0.0932
300    0.1588
350    0.2259
400    0.2894
200    0.0288
250    0.0907
300    0.1514
350    0.2156
400    0.2772
dtype: float64

In [274]:
ssrt.mean()

200    0.2287
250    0.3432
300    0.4588
350    0.5759
400    0.6894
200    0.2288
250    0.3407
300    0.4514
350    0.5656
400    0.6772
dtype: float64

In [242]:
columns = [int(sd) for sd in np.hstack([sim.ssd]*2)*1000]

In [249]:
ert = pd.DataFrame(np.vstack(ert).T, columns=columns)

In [233]:
pd.DataFrame(np.nanmean(ert, axis=1).T)

0      1
0      NaN  0.553
1    0.571  0.580
2    0.556  0.640
3    0.532  0.649
4    0.583  0.577
5    0.628  0.589
6    0.535  0.634
7    0.604    NaN
8    0.541  0.613
9    0.625    NaN
10   0.613  0.583
11   0.589  0.643
12   0.586    NaN
13   0.646    NaN
14   0.568  0.595
..     ...    ...
985  0.580  0.601
986  0.628  0.595
987  0.535  0.610
988  0.646  0.646
989  0.538  0.553
990  0.562  0.562
991  0.637  0.622
992  0.616  0.610
993  0.610  0.613
994  0.514  0.640
995  0.598    NaN
996  0.568  0.589
997  0.565  0.595
998  0.589  0.574
999  0.562  0.592

[1000 rows x 2 columns]

In [230]:
pd.DataFrame(ert)

ValueError: Must pass 2-d input

In [215]:
xrt = np.nan_to_num(xx)

In [201]:
ssrt[np.where(ert<ssrt,1,0)].shape

(2, 5, 1000, 5, 1000)

In [208]:
ert

IndexError: too many indices for array

In [203]:
ssrt.shape


(2, 5, 1000)

In [202]:
sacc.shape

(2, 5, 1000)

In [132]:
m.inits['xb']=1.5

In [140]:
dvg = m.opt.simulator.sim_fx(p=m.inits, analyze=False)
dat = m.opt.simulator.analyze_pro_data(dvg, p=m.inits)

In [77]:
grt = dat[1]

In [93]:
x = pro.query('choice=="go"&rt<.555&rt>.45').rt

In [95]:
xxx=np.append(x.values, array([0]))

In [105]:
r =np.diff(np.sort(x))
r = r[r<.002]

In [97]:
(xx-xxx).min()

-0.47984929999999992

In [94]:
xx = np.append(array([0]), x.values)

In [171]:
sns.kdeplot(mq(dat[1], prob=m.fitparams['prob']), cumulative=True, bw=.01)
sns.kdeplot(m.avg_y[6:11], cumulative=True, bw=.01)

In [163]:
sns.distplot(grt, norm_hist=True, kde=False)
sns.distplot(pro.query('choice=="go"&rt<.555&rt>.45').rt, norm_hist=True, kde=False, bins=17)


In [86]:
m.optimize(stage='flat')

basinhopping step 0: f 0.000656584
basinhopping step 1: f 0.00563785 trial_f 0.00563785 accepted 1  lowest_f 0.000656584
basinhopping step 2: f 0.203764 trial_f 0.203764 accepted 1  lowest_f 0.000656584
basinhopping step 3: f 0.256039 trial_f 0.256039 accepted 1  lowest_f 0.000656584
basinhopping step 4: f 0.16176 trial_f 0.16176 accepted 1  lowest_f 0.000656584
basinhopping step 5: f 0.00895983 trial_f 0.00895983 accepted 1  lowest_f 0.000656584
basinhopping step 6: f 0.0310247 trial_f 0.0310247 accepted 1  lowest_f 0.000656584
basinhopping step 7: f 0.199543 trial_f 0.199543 accepted 1  lowest_f 0.000656584
basinhopping step 8: f 0.242429 trial_f 0.242429 accepted 1  lowest_f 0.000656584
basinhopping step 9: f 0.00269639 trial_f 0.00269639 accepted 1  lowest_f 0.000656584
adaptive stepsize: acceptance rate 0.900000 target 0.500000 new stepsize 0.0555556 old stepsize 0.05
basinhopping step 10: f 0.00269639 trial_f 0.237342 accepted 0  lowest_f 0.000656584
basinhopping step 11: f 0.004

In [88]:
m.opt.basin_decision

'using default inits: fmin=0.000656584'

In [ ]:
#m.flat_popt=vpopt
m.optimize(stage='conditional')

basinhopping step 0: f 0.20631
basinhopping step 1: f 0.297353 trial_f 0.297353 accepted 1  lowest_f 0.20631
basinhopping step 2: f 0.0148666 trial_f 0.0148666 accepted 1  lowest_f 0.0148666
found new global minimum on step 2 with function value 0.0148666
basinhopping step 3: f 0.00184288 trial_f 0.00184288 accepted 1  lowest_f 0.00184288
found new global minimum on step 3 with function value 0.00184288
basinhopping step 4: f 0.0047983 trial_f 0.0047983 accepted 1  lowest_f 0.00184288
basinhopping step 5: f 0.00106143 trial_f 0.00106143 accepted 1  lowest_f 0.00106143
found new global minimum on step 5 with function value 0.00106143
basinhopping step 6: f 0.00300509 trial_f 0.00300509 accepted 1  lowest_f 0.00106143
basinhopping step 7: f 0.00680287 trial_f 0.00680287 accepted 1  lowest_f 0.00106143
basinhopping step 8: f 0.00680287 trial_f 2.10649 accepted 0  lowest_f 0.00106143
basinhopping step 9: f 0.00680287 trial_f 2.10649 accepted 0  lowest_f 0.00106143
adaptive stepsize: accept

In [87]:
m.fitinfo.AIC

AttributeError: 'Model' object has no attribute 'fitinfo'

In [23]:
popt={'a': array([ 0.2979]), 'xb': array([ 0.91365]), 'tr': array([ 0.29971]), 'v': array([ 1.12735])}
