In [642]:
#!/usr/local/bin/env python
from __future__ import division
import time
from numpy import array

from copy import deepcopy
from numpy.random import random_sample as rs
from scipy.stats.mstats import mquantiles as mq
from radd import build
from radd.models import Simulator
from radd import models
model=reload(models)

model=reload(models)
ss = Simulator(model=m)
DVg, DVs = ss.sim_fx(ss.inits,analyze=False)
y1 = ss.analyze_radd(DVg, DVs, ss.inits)
y2 = ss.new_analyze_radd(DVg, DVs, ss.inits)
y1


array([ 0.9554,  0.999 ,  0.993 ,  0.9582,  0.5328,  0.1384,  0.5144,
        0.5434,  0.5644,  0.5864,  0.6204,  0.5054,  0.5314,  0.5504,
        0.5704,  0.6024,  0.9542,  0.9992,  0.9938,  0.961 ,  0.5356,
        0.1336,  0.5154,  0.5424,  0.5634,  0.5854,  0.6194,  0.5074,
        0.5314,  0.5514,  0.5724,  0.6034])

In [629]:
resp_up = lambda a, dvg: np.argmax((dvg.T>=a).T, axis=2)*.0005
resp_lo = lambda dvs: np.argmax((dvs.T<=0).T, axis=3)*.0005
RT = lambda ot, ru: ot[:, None]+(ru*np.where(ru==0, np.nan, 1))
#RT = lambda ru: (ru*np.where(ru==0, np.nan, 1))

gp = resp_up(a, DVg); sp=resp_lo(DVs)
s1 = RT(ssd, sp)
ert1 = RT(tr, gp)[:, :nss][:, None] * np.ones_like(s1)


s2 = SRT2(ssd, DVs)
ert2 = RT2(a, tr, DVg)[:, :nss]
ert2 = np.array([ert2[i] * np.ones_like(s2[i]) for i in range(ncond)])

In [591]:
len([t1<s2])
#len(t1.flatten())

ValueError: operands could not be broadcast together with shapes (2,10000) (2,5,5000) 

In [625]:
ert2 = t2[:, :nss]
ert1 = t1[:, :nss][:, None] * np.ones_like(s1)

In [626]:
ert1

array([[[ 0.5734,  0.5914,  0.5134, ...,  0.5414,  0.5384,  0.5474],
        [ 0.5734,  0.5914,  0.5134, ...,  0.5414,  0.5384,  0.5474],
        [ 0.5734,  0.5914,  0.5134, ...,  0.5414,  0.5384,  0.5474],
        [ 0.5734,  0.5914,  0.5134, ...,  0.5414,  0.5384,  0.5474],
        [ 0.5734,  0.5914,  0.5134, ...,  0.5414,  0.5384,  0.5474]],

       [[ 0.5654,  0.6014,  0.5014, ...,  0.5564,  0.5214,  0.6084],
        [ 0.5654,  0.6014,  0.5014, ...,  0.5564,  0.5214,  0.6084],
        [ 0.5654,  0.6014,  0.5014, ...,  0.5564,  0.5214,  0.6084],
        [ 0.5654,  0.6014,  0.5014, ...,  0.5564,  0.5214,  0.6084],
        [ 0.5654,  0.6014,  0.5014, ...,  0.5564,  0.5214,  0.6084]]])

In [614]:
ert1 = ert1[:, None]*np.ones_like(s1)
ert2 = np.array([ert2[i] * np.ones_like(s2[i]) for i in range(ncond)])


In [632]:
x2 = np.where(ert2<s2, 0, 1).mean(axis=2)
x1 = np.where(ert1<s1, 0, 1).mean(axis=2)

In [634]:
x1

array([[ 0.9994,  0.9932,  0.9586,  0.5414,  0.1392],
       [ 0.999 ,  0.9924,  0.9614,  0.5382,  0.1338]])

In [619]:
np.all(x1==x2)

True

In [598]:
ert2[ert2 < ert1]

array([], dtype=float64)

In [569]:
len(s2[np.isnan(s2)])

0

In [570]:
len(s1[s1!=s2])
s1[s1!=s2]

array([ 0.35,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,
        0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,
        0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,
        0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,
        0.4 ,  0.4 ,  0.35,  0.35,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,
        0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,
        0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,
        0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,
        0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ])

In [557]:
len(s2[s2!=s1])
s2[s2!=s1]

array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan])

In [ ]:
ert = array([ertx[i] * np.ones_like(ssrt[i]) for i in range(ncond)])


In [588]:
RT2 = lambda a, tr, dvg: (tr+(np.where((DVg.max(axis=2).T>=a).T, np.argmax((dvg.T>=a).T,axis=2)*.0005, np.nan).T)).T

SRT2 = lambda ssd, DVs: np.where(np.any(DVs<=0, axis=3), ssd[:, None]+np.argmax(DVs<=0, axis=3)*.0005,np.nan)

In [458]:
%%timeit 
for i in xrange(5):
      DVg, DVs = ss.sim_fx(ss.inits,analyze=False)
      yhat = ss.analyze_radd(DVg, DVs, ss.inits)

KeyboardInterrupt: 

In [383]:
%%timeit 
for i in xrange(5):
      DVg, DVs = ss.sim_fx(ss.inits,analyze=False)
      yhat = ss.new_analyze_radd(DVg, DVs, ss.inits)

1 loops, best of 3: 4.03 s per loop


In [640]:
x = np.arange(len(y1[:6]))
plt.plot(x, y1[:6], alpha=.9, color='Blue', linestyle='-')
plt.plot(x, y2[:6], alpha=.9, color='Green', linestyle='--')

In [641]:
x = np.arange(len(y1[6:11]))
plt.plot(x, y1[11:16], alpha=.9, color='Blue', linestyle='-')
plt.plot(x, y2[11:16], alpha=.9, color='Green', linestyle='--')

In [325]:

yhat = ss.analyze_radd(DVg, DVs, ss.inits)
yhat =  (DVg, DVs, ss.inits) 

In [219]:
lbd = lambda DVg, a, tr: (tr+(np.where((DVg[:, ss.nss:, :].max(axis=2).T>=a).T, np.argmax((DVg[:, ss.nss:, :].T>=a).T,axis=2)*.0005, np.nan).T)).T

gort_func = lambda gtrace, a, t: (tr+(np.where((gtrace.max(axis=2).T>=a).T, np.argmax((gtrace.T>=a).T,axis=2)*.0005, np.nan).T)).T

ssrt_func = lambda strace: np.where(np.any(strace<=0, axis=3), ss.ssd[:, None]+np.argmax(strace<=0, axis=3)*.0005, np.nan)

ssrt_func2 = lambda strace: ss.ssd[:, None] + np.where(DVs.min(axis=3)<=0, np.argmax(DVs<=0,axis=3)*.0005, np.nan)

In [ ]:
4202 function calls in 27.292 seconds
3602 function calls in 23.881 seconds

In [118]:
np.where(DVg.max(axis=2).T>=a)

(array([   0,    0,    1, ..., 9998, 9999, 9999]),
 array([0, 1, 0, ..., 1, 0, 1]))

In [228]:
resp_up = lambda trace, a: np.argmax((trace.T>=a).T, axis=2)*.0005
resp_lo = lambda trace, b: np.argmax((trace.T<=b).T, axis=3)*.0005
RT = lambda ontime, rbool: ontime[:, None]+(rbool*np.where(rbool==0, np.nan, 1))


In [239]:
go_dec

array([[ 0.192 ,  0.202 ,  0.2455, ...,  0.227 ,  0.1615,  0.189 ],
       [ 0.2465,  0.199 ,  0.1845, ...,  0.1865,  0.1305,  0.167 ]])

In [254]:
ert = ertx[:, None]*np.ones_like(ssrt)

In [261]:
%timeit eq = map((lambda x: mq(x[0][x[0]<x[1]], prob)), zip(ert, ssrt))

1000 loops, best of 3: 1.17 ms per loop


In [262]:
%timeit eq = [mq(ert[i][ert[i]<ssrt[i]], prob=prob)*scale for i in range(ncond)]

1000 loops, best of 3: 1.32 ms per loop


In [258]:
eq

[array([ 0.4519,  0.4704,  0.4829,  0.4979,  0.5209]),
 array([ 0.4529,  0.4709,  0.4839,  0.4984,  0.5219])]

In [260]:
eq

[array([ 0.4519,  0.4704,  0.4829,  0.4979,  0.5209]),
 array([ 0.4529,  0.4709,  0.4839,  0.4984,  0.5219])]

In [253]:
 zip(ertx, ssrt)[1]

(array([ 0.5169,  0.4584,  0.5014, ...,  0.4914,  0.4354,  0.4719]),
 array([[ 0.3995,  0.3165,  0.3475, ...,  0.3915,  0.3025,  0.3535],
        [ 0.4495,  0.3665,  0.3975, ...,  0.4415,  0.3525,  0.4035],
        [ 0.4995,  0.4165,  0.4475, ...,  0.4915,  0.4025,  0.4535],
        [ 0.5615,  0.5375,  0.5565, ...,  0.5745,  0.5035,  0.5435],
        [ 0.6215,  0.626 ,  0.663 , ...,  0.631 ,  0.5865,  0.656 ]]))

In [240]:
%%timeit
for i in xrange(20):
      go_dec = resp_up(DVg, a)
      ss_dec = resp_lo(DVs, 0)
      gort = RT(tr, go_dec[:, :nss])
      ssrt = RT(ss.ssd, ss_dec)      

      ert = RT(tr, go_dec[:, nss:])[:,None]*np.ones_like(ssrt)


1 loops, best of 3: 1.69 s per loop


In [234]:
ssrt

array([[[ 0.3995,  0.3165,  0.3475, ...,  0.3915,  0.3025,  0.3535],
        [ 0.4495,  0.3665,  0.3975, ...,  0.4415,  0.3525,  0.4035],
        [ 0.4995,  0.4165,  0.4475, ...,  0.4915,  0.4025,  0.4535],
        [ 0.598 ,  0.557 ,  0.5605, ...,  0.609 ,  0.4805,  0.5215],
        [ 0.7095,  0.6875,  0.647 , ...,  0.8   ,  0.6095,  0.6785]],

       [[ 0.3995,  0.3165,  0.3475, ...,  0.3915,  0.3025,  0.3535],
        [ 0.4495,  0.3665,  0.3975, ...,  0.4415,  0.3525,  0.4035],
        [ 0.4995,  0.4165,  0.4475, ...,  0.4915,  0.4025,  0.4535],
        [ 0.5615,  0.5375,  0.5565, ...,  0.5745,  0.5035,  0.5435],
        [ 0.6215,  0.626 ,  0.663 , ...,  0.631 ,  0.5865,  0.656 ]]])

In [ ]:
%%timeit
for i in xrange(200):
      grt
      grt = resp_up(DVg[:, :nss, :], a)
      ertx = resp_up(DVg[:, nss:, :], a)
      ssrtx = ssrt_func(DVs)

In [222]:
%%timeit
for i in xrange(20):
      grt = gort_func(DVg[:, :nss, :], a, tr)
      ertx = gort_func(DVg[:, nss:, :], a, tr)
      ssrtx = ssrt_func(DVs)

1 loops, best of 3: 2.5 s per loop


In [223]:
%%timeit
for i in xrange(20):
      grt = (tr+(np.where((DVg[:, nss:, :].max(axis=2).T>=a).T, np.argmax((DVg[:, nss:, :].T>=a).T,axis=2)*dt, np.nan).T)).T
      ertx = (tr+(np.where((DVg[:, :nss, :].max(axis=2).T>=a).T, np.argmax((DVg[:, :nss, :].T>=a).T,axis=2)*dt, np.nan).T)).T
      #ssrt = ss.ssd[:, None] + np.where((DVs.min(axis=3).T<=0).T, np.argmax((DVs.T<=0).T,axis=3)*.0005, np.nan).T
      ssrt = np.where(np.any(DVs<=0, axis=3), ss.ssd[:, None]+np.argmax(DVs<=0, axis=3)*.0005, np.nan)


1 loops, best of 3: 2.56 s per loop


In [102]:
%timeit ssrt = np.where(np.any(DVs<=0, axis=3), ss.ssd[:, None]+np.argmax(DVs<=0, axis=3)*.0005, np.nan)

10 loops, best of 3: 99.4 ms per loop


In [109]:
%timeit ssrt = ss.ssd[:, None] + np.where(DVs.min(axis=3)<=0, np.argmax(DVs<=0,axis=3)*.0005, np.nan)

10 loops, best of 3: 82.8 ms per loop


In [50]:
def x(p, a_dots=False, a_fewerdots=False, a_nodots=False):
      
      p = ss.vectorize_params(p)
      Pg, Tg = ss.__update_go_process__(p)
      Ps, Ts = ss.__update_stop_process__(p)

      # a/tr/v Bias: ALL CONDITIONS, ALL SSD
      DVg = ss.lowerb+(ss.xtb[:,None]*np.cumsum(np.where((rs((ss.ncond, ss.ntot, Tg.max())).T<Pg), ss.dx,-ss.dx).T, axis=2))
      init_ss = array([[DVc[:ss.nss, ix] for ix in np.where(Ts<Tg[i], Tg[i]-Ts, 0)] for i, DVc in enumerate(DVg)])
      DVs = init_ss[:, :, :, None]+np.cumsum(np.where(rs((ss.nss, Ts.max()))<Ps, ss.dx, -ss.dx), axis=1)

      if a_dots:
            return dots(DVg, DVs, p)
      elif a_fewerdots:
            return fewerdots(DVg, DVs, p)
      elif a_nodots:
            return nodots(DVg, DVs, p)
      else:
            return DVg, DVs

In [64]:
dt=ss.dt; nss=ss.nss; ncond=ss.ncond; ssd=ss.ssd; ntot=ss.ntot
tb=ss.tb; prob=ss.prob; scale=ss.scale; a=p['a']; tr=p['tr']; dx=ss.dx


In [ ]:

      dt=ss.dt; nss=ss.nss; ncond=ss.ncond; ssd=ss.ssd;
      tb=ss.tb; prob=ss.prob; scale=ss.scale; a=p['a']; tr=p['tr']
      
      
      p = ss.vectorize_params(p)
      Pg, Tg = ss.__update_go_process__(p)
      Ps, Ts = ss.__update_stop_process__(p)

      # a/tr/v Bias: ALL CONDITIONS, ALL SSD
      DVg = ss.lowerb+(ss.xtb[:,None]*np.cumsum(np.where((rs((ss.ncond, ss.ntot, Tg.max())).T<Pg), ss.dx,-ss.dx).T, axis=2))
      init_ss = array([[DVc[:ss.nss, ix] for ix in np.where(Ts<Tg[i], Tg[i]-Ts, 0)] for i, DVc in enumerate(DVg)])
      DVs = init_ss[:, :, :, None]+np.cumsum(np.where(rs((ss.nss, Ts.max()))<Ps, ss.dx, -ss.dx), axis=1)
      

      grt = (tr+(np.where((DVg[:, nss:, :].max(axis=2).T>=a).T, np.argmax((DVg[:, nss:, :].T>=a).T,axis=2)*dt, np.nan).T)).T
      ertx = (tr+(np.where((DVg[:, :nss, :].max(axis=2).T>=a).T, np.argmax((DVg[:, :nss, :].T>=a).T,axis=2)*dt, np.nan).T)).T
      ssrt = np.where(np.any(DVs<=0, axis=3), ssd[:, None]+np.argmax(DVs<=0, axis=3)*dt,np.nan)

      # compute RT quantiles for correct and error resp.
      ert = array([ertx[i] * np.ones_like(ssrt[i]) for i in range(ncond)])
      gq = np.vstack([mq(rtc[rtc<tb], prob=prob)*scale for rtc in grt])
      eq = [mq(ert[i][ert[i]<ssrt[i]], prob=prob)*scale for i in range(ncond)]
      # Get response and stop accuracy information
      gac = np.nanmean(np.where(grt<tb, 1, 0), axis=1)
      sacc = np.where(ert<ssrt, 0, 1).mean(axis=2)

      return np.hstack([np.hstack([i[ii] for i in [gac, sacc, gq, eq]]) for ii in range(ncond)])


In [ ]:
grt = (tr+(np.where((DVg[:, nss:, :].max(axis=2).T>=a).T, np.argmax((DVg[:, nss:, :].T>=a).T,axis=2)*.0005, np.nan).T)).T

In [ ]:
l = []
map(, )
#[ertx[i] * np.ones_like(ssrt[i]) for i in range(ncond)]

- a_dots              3702 function calls in 8.593 seconds
- a_fewerdots         3702 function calls in 8.102 seconds
- a_nodots            3702 function calls in 9.375 seconds

In [ ]:
      grt = (tr+(np.where((DVg[:, nss:, :].max(axis=2).T>=a).T, np.argmax((DVg[:, ss.nss:, :].T>=a).T,axis=2)*dt, np.nan).T)).T
      ertx = (tr+(np.where((DVg[:, :nss, :].max(axis=2).T>=a).T, np.argmax((DVg[:, :nss, :].T>=a).T,axis=2)*dt, np.nan).T)).T
      ssrt = np.where(np.any(DVs<=0, axis=3), ssd[:, None]+np.argmax(DVs<=0, axis=3)*dt,np.nan)

      # compute RT quantiles for correct and error resp.
      ert = array([ertx[i] * np.ones_like(ssrt[i]) for i in range(ncond)])
      gq = np.vstack([mq(rtc[rtc<tb], prob=prob)*scale for rtc in grt])
      eq = [mq(ert[i][ert[i]<ssrt[i]], prob=prob)*scale for i in range(ncond)]
      # Get response and stop accuracy information
      gac = np.nanmean(np.where(grt<tb, 1, 0), axis=1)
      sacc = np.where(ert<ssrt, 0, 1).mean(axis=2)

      return np.hstack([np.hstack([i[ii] for i in [gac, sacc, gq, eq]]) for ii in range(ncond)])

In [ ]:

def simulate_and_analyze(p):
      
      
      dt=ss.dt; nss=ss.nss; ncond=ss.ncond; ssd=ss.ssd;
      tb=ss.tb; prob=ss.prob; scale=ss.scale; a=p['a']; tr=p['tr']
      
      p = ss.vectorize_params(p)
      Pg, Tg = ss.__update_go_process__(p)
      Ps, Ts = ss.__update_stop_process__(p)

      # a/tr/v Bias: ALL CONDITIONS, ALL SSD
      DVg = ss.lowerb+(ss.xtb[:,None]*np.cumsum(np.where((rs((ss.ncond, ss.ntot, Tg.max())).T<Pg), ss.dx,-ss.dx).T, axis=2))
      init_ss = array([[DVc[:ss.nss, ix] for ix in np.where(Ts<Tg[i], Tg[i]-Ts, 0)] for i, DVc in enumerate(DVg)])
      DVs = init_ss[:, :, :, None]+np.cumsum(np.where(rs((ss.nss, Ts.max()))<Ps, ss.dx, -ss.dx), axis=1)
      
      grt = (tr+(np.where((DVg[:, nss:, :].max(axis=2).T>=a).T, np.argmax((DVg[:, ss.nss:, :].T>=a).T,axis=2)*dt, np.nan).T)).T
      ertx = (tr+(np.where((DVg[:, :nss, :].max(axis=2).T>=a).T, np.argmax((DVg[:, :nss, :].T>=a).T,axis=2)*dt, np.nan).T)).T
      ssrt = np.where(np.any(DVs<=0, axis=3), ssd[:, None]+np.argmax(DVs<=0, axis=3)*dt,np.nan)

      # compute RT quantiles for correct and error resp.
      ert = array([ertx[i] * np.ones_like(ssrt[i]) for i in range(ncond)])
      gq = np.vstack([mq(rtc[rtc<tb], prob=prob)*scale for rtc in grt])
      eq = [mq(ert[i][ert[i]<ssrt[i]], prob=prob)*scale for i in range(ncond)]
      # Get response and stop accuracy information
      gac = np.nanmean(np.where(grt<tb, 1, 0), axis=1)
      sacc = np.where(ert<ssrt, 0, 1).mean(axis=2)

      return np.hstack([np.hstack([i[ii] for i in [gac, sacc, gq, eq]]) for ii in range(ncond)])