In [2]:
from radd import build, vis
from radd.toolbox import analyze
from __future__ import division

In [6]:
m.inits

{'a': 0.48758096, 'tr': 0.29223792, 'v': 1.69870371, 'xb': 1.5}

In [22]:
mv = build.Model(data=pro, kind='xpro', depends_on={'v':'pGo'})

In [211]:
ma = build.Model(data=pro, kind='xpro', depends_on={'a':'pGo'})

In [235]:
mtr = build.Model(data=pro, kind='xpro', depends_on={'tr':'pGo'})

In [236]:
trinits={'a': array([ 0.37609]),
'tr': array([ 0.35126]),
'v': array([ 1.38347]),
'xb': array([ 3.9265])}

In [237]:
mtr.inits=trinits

In [226]:
ma.flat_popt = {'a': 0.51141400553255789,
 'tr': 0.32001314851667217,
 'v': 1.5185917057414291,
 'xb': 3.8071450802621083}

In [23]:
inits = {'a': 0.4748, 'tr': 0.2725, 'v': 1.6961, 'xb': 1.5}

In [170]:
inits = {'a': 0.4748, 'tr': 0.2725, 'v': 1.6961, 'xb': 1.5}
vtrinits = {'a': 0.51016066165044993,
  'tr': 0.27860619645820422,
  'v': 1.7283025570538106,
  'xb': 1.4078975403059684}
vinits={'a': array([ 0.47969]),
 'tr': array([ 0.27451]),
 'v': array([ 1.05802]),
 'xb': array([ 3.79324])}

In [127]:
theta=reload(theta)

In [ ]:
wts = array([1.4487, 0.9254, 0.8490, 0.8228, 1.0876, 1.4984, 0.3254, 1.2268, 5.2735, 3.7082, 0.9067, 0.0932, 0.5286, 1.2207, 1.0658, 0.2834])
yhat = array([0.9441, 0.8139, 0.5450, 0.3205, 0.1164, 0.0828, 0.5180, 0.5290, 0.5350, 0.5410, 0.5490, 0.5300, 0.5390, 0.5450, 0.5490, 0.5530])
y = array([0.9399, 0.7903, 0.5477, 0.3399, 0.1180, 0.0813, 0.5034, 0.5315, 0.5409, 0.5442, 0.5452, 0.5337, 0.5439, 0.5446, 0.5451, 0.5453])


In [172]:
basins = np.array(basins)
bp = np.array(bp)
good_basin_params = bp[np.where(basins<.001)]
ma.opt.hop_around(p=ainits, ninits=50, disp=False)

basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhopping finished
basinhoppi

{'a': 0.31675202209831299,
 'tr': 0.33742271628069459,
 'v': 1.2873593812059114,
 'xb': 2.3423274442412558}

In [173]:
basins.extend(mv.opt.basins)
bp.extend(mv.opt.basins_popt)

In [176]:
#basins = np.array(basins)
bp = np.array(bp)

In [177]:
#basins.extend(mv.opt.basins)
#bp.extend(mv.opt.basins_popt)
#basins = np.array(basins)
#bp = np.array(bp)
good_basin_params = bp[np.where(basins<.001)]

In [316]:
ma.make_optimizer(disp=False)
ma.optimize(stage='flat', multiopt=True, disp=False)
ma.optimize(stage='conditional', multiopt=True, disp=False)

basinhopping finished
basinhopping finished
{'a': array([ 0.51493]), 'xb': array([ 3.85894]), 'tr': array([ 0.32001]), 'v': array([ 1.53749])}
basinhopping finished


In [330]:
mtr.make_optimizer(disp=False)
mtr.optimize(stage='flat', multiopt=True, disp=False)
mtr.optimize(stage='conditional', multiopt=True, disp=False)

In [336]:
mv.make_optimizer(disp=False)
mv.optimize(stage='flat', multiopt=True, disp=False)
mv.optimize(stage='conditional', multiopt=True, disp=False)

In [327]:
mvtr.optimize(stage='flat', multiopt=True, disp=False)
mvtr.optimize(stage='conditional', multiopt=True, disp=False)

In [311]:
ma.flat_popt

{'a': array([ 0.2363 ,  0.21577,  0.20472,  0.19372,  0.1731 ,  0.16878]),
 'tr': 0.46959856280677126,
 'v': 2.2959903151647625,
 'xb': 2.211136807669311}

In [335]:
ma.fitinfo

a_0        0.60686
a_100       0.4356
a_20       0.52805
a_40       0.52515
a_60       0.49985
a_80       0.47221
chi       0.068755
cnvrg        False
ndata           16
nfev          3308
nvary            6
tr         0.32001
v           1.5375
xb          3.8589
df              10
rchi     0.0068755
logp       -79.677
AIC        -67.677
BIC        -75.112
dtype: object

In [329]:
mvtr.fitinfo

a            0.51224
chi        0.0027448
cnvrg           True
ndata             16
nfev             272
nvary             12
tr_0         0.31135
tr_100       0.30166
tr_20        0.28602
tr_40        0.28043
tr_60        0.26729
tr_80        0.26701
v_0            1.704
v_100          2.111
v_20          1.6344
v_40          1.7049
v_60          1.6983
v_80           1.822
xb            1.4068
df                 4
rchi      0.00068619
logp         -116.55
AIC           -92.55
BIC          -111.29
dtype: object

In [323]:
mv.fitinfo

a           0.47415
chi       0.0041533
cnvrg          True
ndata            16
nfev            172
nvary             6
tr          0.27517
v_0          1.2857
v_100        1.7721
v_20         1.4121
v_40         1.5451
v_60          1.621
v_80         1.7358
xb           1.4421
df               10
rchi     0.00041533
logp        -124.58
AIC         -112.58
BIC         -120.02
dtype: object

In [320]:
mtr.fitinfo

a             0.3786
chi        0.0034976
cnvrg           True
ndata             16
nfev             175
nvary              6
tr_0         0.37864
tr_100       0.32956
tr_20        0.36963
tr_40        0.35435
tr_60        0.34414
tr_80        0.32911
v             1.3882
xb            3.9776
df                10
rchi      0.00034976
logp         -127.33
AIC          -115.33
BIC          -122.77
dtype: object

In [321]:
ma.fitinfo

a_0        0.60686
a_100       0.4356
a_20       0.52805
a_40       0.52515
a_60       0.49985
a_80       0.47221
chi       0.068755
cnvrg        False
ndata           16
nfev          3308
nvary            6
tr         0.32001
v           1.5375
xb          3.8589
df              10
rchi     0.0068755
logp       -79.677
AIC        -67.677
BIC        -75.112
dtype: object

In [305]:
mtr.fitinfo

a            0.37609
chi        0.0017233
cnvrg           True
ndata             16
nfev             146
nvary              6
tr_0         0.38011
tr_100       0.32463
tr_20        0.36825
tr_40         0.3547
tr_60         0.3459
tr_80        0.32894
v             1.3835
xb            3.9265
df                10
rchi      0.00017233
logp         -138.66
AIC          -126.66
BIC          -134.09
dtype: object

In [221]:
ma.opt.basins_popt

[{'a': 0.51141400553255789,
  'tr': 0.32001314851667217,
  'v': 1.5185917057414291,
  'xb': 3.8071450802621083},
 {'a': 0.22906928021368561,
  'tr': 0.41140989913844778,
  'v': 1.5338475767808279,
  'xb': 1.9282849313237926}]

In [219]:
ma.opt.basins

[0.0033072427804599416, 0.00065432068003523278]

In [199]:
mv.popt

{'a': array([ 0.23303,  0.23303,  0.23303,  0.23303,  0.23303,  0.23303]),
 'tr': array([ 0.37322,  0.37322,  0.37322,  0.37322,  0.37322,  0.37322]),
 'v': array([ 0.86204,  1.02591,  1.19121,  1.2927 ,  1.46035,  1.50436], dtype=float32),
 'v_0': 0.86203886680559694,
 'v_100': 1.5043647619061067,
 'v_20': 1.0259066231448535,
 'v_40': 1.1912131737626024,
 'v_60': 1.2926964160105026,
 'v_80': 1.4603505955760996,
 'xb': array([ 1.44234,  1.44234,  1.44234,  1.44234,  1.44234,  1.44234])}

In [304]:
mtr.fitinfo

a            0.37609
chi        0.0017233
cnvrg           True
ndata             16
nfev             146
nvary              6
tr_0         0.38011
tr_100       0.32463
tr_20        0.36825
tr_40         0.3547
tr_60         0.3459
tr_80        0.32894
v             1.3835
xb            3.9265
df                10
rchi      0.00017233
logp         -138.66
AIC          -126.66
BIC          -134.09
dtype: object

In [225]:
finfo

a           0.51141
chi       0.0012979
cnvrg          True
ndata            16
nfev            177
nvary             6
tr          0.32001
v_0          1.2206
v_100        1.7641
v_20         1.3622
v_40          1.497
v_60         1.6018
v_80         1.7238
xb           3.8071
df               10
rchi     0.00012979
logp        -143.19
AIC         -131.19
BIC         -138.63
dtype: object

In [227]:
ma.flat_popt

{'a': 0.5114140055325579,
 'tr': 0.3200131485166722,
 'v': 1.518591705741429,
 'xb': 3.8071450802621083}

In [238]:
mtr.optimize(stage='flat', multiopt=True, inits=trinits)

basinhopping step 0: f 0.00114096
basinhopping step 1: f 0.229617 trial_f 0.229617 accepted 1  lowest_f 0.00114096
basinhopping step 2: f 0.274175 trial_f 0.274175 accepted 1  lowest_f 0.00114096
basinhopping step 3: f 0.286275 trial_f 0.286275 accepted 1  lowest_f 0.00114096
basinhopping step 4: f 0.259804 trial_f 0.259804 accepted 1  lowest_f 0.00114096
basinhopping step 5: f 0.268038 trial_f 0.268038 accepted 1  lowest_f 0.00114096
basinhopping step 6: f 0.224504 trial_f 0.224504 accepted 1  lowest_f 0.00114096
basinhopping step 7: f 0.0126639 trial_f 0.0126639 accepted 1  lowest_f 0.00114096
basinhopping step 8: f 0.016402 trial_f 0.016402 accepted 1  lowest_f 0.00114096
basinhopping step 9: f 0.016402 trial_f 0.301423 accepted 0  lowest_f 0.00114096
adaptive stepsize: acceptance rate 0.800000 target 0.500000 new stepsize 0.0555556 old stepsize 0.05
basinhopping step 10: f 0.207581 trial_f 0.207581 accepted 1  lowest_f 0.00114096
basinhopping step 11: f 0.134959 trial_f 0.134959 ac

In [240]:
mtr.opt.basin_decision

'using default inits: fmin=0.001140959'

In [244]:
trinits = {'a': array([ 0.37609]),
'tr': array([ 0.35126]),
'v': array([ 1.38347]),
'xb': array([ 3.9265])}

mv.flat_popt=trinits
mv.optimize(stage='conditional', multiopt=True, inits = trinits)

{'a': array([ 0.37609]), 'xb': array([ 3.9265]), 'tr': array([ 0.35126]), 'v': array([ 1.38347])}
basinhopping step 0: f 0.213395
basinhopping step 1: f 0.227633 trial_f 0.227633 accepted 1  lowest_f 0.213395
basinhopping step 2: f 0.31051 trial_f 0.31051 accepted 1  lowest_f 0.213395
basinhopping step 3: f 0.33179 trial_f 0.33179 accepted 1  lowest_f 0.213395
basinhopping step 4: f 0.422948 trial_f 0.422948 accepted 1  lowest_f 0.213395
basinhopping step 5: f 0.513775 trial_f 0.513775 accepted 1  lowest_f 0.213395
basinhopping step 6: f 0.428601 trial_f 0.428601 accepted 1  lowest_f 0.213395
basinhopping step 7: f 0.611245 trial_f 0.611245 accepted 1  lowest_f 0.213395
basinhopping step 8: f 0.614617 trial_f 0.614617 accepted 1  lowest_f 0.213395
basinhopping step 9: f 0.649066 trial_f 0.649066 accepted 1  lowest_f 0.213395
adaptive stepsize: acceptance rate 0.900000 target 0.500000 new stepsize 0.0555556 old stepsize 0.05
basinhopping step 10: f 0.778321 trial_f 0.778321 accepted 1  

In [309]:
ma.fitinfo

a_0         0.23437
a_100       0.16889
a_20        0.21604
a_40        0.20462
a_60        0.19354
a_80        0.17044
chi       0.0069037
cnvrg         False
ndata            16
nfev           3387
nvary             6
tr           0.4696
v             2.296
xb           2.2111
df               10
rchi     0.00069037
logp        -116.45
AIC         -104.45
BIC         -111.89
dtype: object

In [289]:
dvg = mv.simulate(analyze=False)
dvga = ma.simulate(analyze=False)
acc, hi, lo = mv.opt.simulator.analyze_pro_data(dvg, mv.popt)
acca, hia, loa = ma.opt.simulator.analyze_pro_data(dvga, ma.popt)

In [277]:
hi_rts = mv.data.query('response==1 & pGo>.5 & rt<.550').rt.values
lo_rts = mv.data.query('response==1 & pGo<.5 & rt<.550').rt.values

In [301]:
shade=True; alpha=.5; bw=.001; lw=2.5; ls='-'
sns.kdeplot(lo_rts,  color='k',  cumulative=True, shade=True, bw=.01)
sns.kdeplot(lo, color='Blue', cumulative=True, shade=True, bw=.01)
sns.kdeplot(loa, color='Red', cumulative=True, shade=True, bw=.01)
plt.gca().set_xlim(.42, .6)

(0.42, 0.6)

In [272]:
dvg = mv.simulate(analyze=False)


In [270]:
f, axes=plt.subplots(2)
vis.plot_fits(mv.avg_y, mv.fits, kind='pro', data=mv.data)
vis.plot_fits(ma.avg_y, ma.fits, kind='pro', cdf=True)
vis.plot_fits(ma.avg_y, mtr.fits, kind='pro', cdf=True)

In [266]:
mv.avg_y

array([ 0.93996,  0.79037,  0.54775,  0.33996,  0.11803,  0.08139,
        0.50343,  0.53158,  0.54094,  0.54427,  0.54527,  0.53376,
        0.54393,  0.5447 ,  0.54517,  0.54533])

In [248]:
mv.fits

array([ 0.93637,  0.81273,  0.54142,  0.33493,  0.13025,  0.08403,
        0.51426,  0.52626,  0.53226,  0.54126,  0.54926,  0.52826,
        0.53726,  0.54426,  0.54926,  0.55226])

In [246]:
mv.fitinfo.to_csv("FINAL_DRIFT_FITINFO_LOWESTYET.CSV")

In [243]:
mtr.fitinfo

a            0.37609
chi        0.0017233
cnvrg           True
ndata             16
nfev             146
nvary              6
tr_0         0.38011
tr_100       0.32463
tr_20        0.36825
tr_40         0.3547
tr_60         0.3459
tr_80        0.32894
v             1.3835
xb            3.9265
df                10
rchi      0.00017233
logp         -138.66
AIC          -126.66
BIC          -134.09
dtype: object

In [ ]:
{'a': array([ 0.37609]),
'tr': array([ 0.35126]),
'v': array([ 1.38347]),
'xb': array([ 3.9265])}

array([ 0.46519,  0.51657,  0.52957,  0.53657,  0.54457,  0.54957])

In [179]:
finfolist = []
aiclist = []
poptlist = []
for gbp in good_basin_params:
      mv.flat_popt=deepcopy(gbp)
      mv.optimize(stage='conditional', multiopt=True, inits=deepcopy(gbp))
      finfolist.append(mv.fitinfo)
      aiclist.append(mv.fitinfo.AIC)
      poptlist.append(deepcopy(mv.popt))

{'a': 0.64052056636986543, 'xb': 1.4432602282816778, 'tr': 0.1968285182570477, 'v': 1.5769258285831571}
basinhopping step 0: f 0.186146
basinhopping step 1: f 0.0962864 trial_f 0.0962864 accepted 1  lowest_f 0.0962864
found new global minimum on step 1 with function value 0.0962864
basinhopping step 2: f 0.185515 trial_f 0.185515 accepted 1  lowest_f 0.0962864
basinhopping step 3: f 0.170946 trial_f 0.170946 accepted 1  lowest_f 0.0962864
basinhopping step 4: f 0.347689 trial_f 0.347689 accepted 1  lowest_f 0.0962864
basinhopping step 5: f 0.30477 trial_f 0.30477 accepted 1  lowest_f 0.0962864
basinhopping step 6: f 0.229593 trial_f 0.229593 accepted 1  lowest_f 0.0962864
basinhopping step 7: f 0.144545 trial_f 0.144545 accepted 1  lowest_f 0.0962864
basinhopping step 8: f 0.0896293 trial_f 0.0896293 accepted 1  lowest_f 0.0896293
found new global minimum on step 8 with function value 0.0896293
basinhopping step 9: f 0.118435 trial_f 0.118435 accepted 1  lowest_f 0.0896293
adaptive ste

In [206]:
mvtr.flat_popt#popt

{'a': 0.36380650531493897,
 'tr': array([ 0.38333,  0.39058,  0.36488,  0.35775,  0.38482,  0.36123]),
 'v': array([ 1.38373,  1.69022,  1.49825,  1.52847,  2.00428,  1.72298]),
 'xb': 3.658959723741662}

In [204]:
mvtr.fitinfo

a            0.36381
chi        0.0010015
cnvrg           True
ndata             16
nfev             287
nvary             12
tr_0         0.38167
tr_100       0.36103
tr_20        0.39122
tr_40        0.36513
tr_60        0.35786
tr_80         0.3855
v_0           1.3708
v_100         1.7399
v_20           1.685
v_40          1.4892
v_60          1.5205
v_80          1.9959
xb             3.659
df                 4
rchi      0.00025038
logp         -132.68
AIC          -108.68
BIC          -127.42
dtype: object

In [207]:
ma.flat_popt

NameError: name 'ma' is not defined

In [203]:
mvtr.popt

{'a': array([ 0.36381,  0.36381,  0.36381,  0.36381,  0.36381,  0.36381]),
 'tr': array([ 0.38167,  0.39122,  0.36513,  0.35786,  0.3855 ,  0.36103], dtype=float32),
 'tr_0': 0.38167202081159535,
 'tr_100': 0.3610285728873196,
 'tr_20': 0.39122023571847409,
 'tr_40': 0.36513362506794322,
 'tr_60': 0.35785785068540399,
 'tr_80': 0.38549723272003322,
 'v': array([ 1.37083,  1.68503,  1.48921,  1.52049,  1.99585,  1.73992], dtype=float32),
 'v_0': 1.3708348468421001,
 'v_100': 1.7399212885055055,
 'v_20': 1.685029581536184,
 'v_40': 1.4892101474959447,
 'v_60': 1.5204918672126355,
 'v_80': 1.9958527128341399,
 'xb': array([ 3.65896,  3.65896,  3.65896,  3.65896,  3.65896,  3.65896])}

In [180]:
aics = np.array(aiclist)

In [201]:
poptlist[np.argmin(aics)]

{'a': array([ 0.51141,  0.51141,  0.51141,  0.51141,  0.51141,  0.51141]),
 'tr': array([ 0.32001,  0.32001,  0.32001,  0.32001,  0.32001,  0.32001]),
 'v': array([ 1.22063,  1.36224,  1.49704,  1.60176,  1.72381,  1.76406], dtype=float32),
 'v_0': 1.2206296380937256,
 'v_100': 1.7640615823592622,
 'v_20': 1.3622358968043313,
 'v_40': 1.4970380849011338,
 'v_60': 1.6017636718723776,
 'v_80': 1.7238067015995366,
 'xb': array([ 3.80715,  3.80715,  3.80715,  3.80715,  3.80715,  3.80715])}

In [195]:
fidf = pd.DataFrame([fi.T for fi in finfolist])
fidf.to_csv("xpro_v_finfoDF.csv", index=False)

In [188]:
poptlist[np.argmin(aics)]

{'a': array([ 0.51141,  0.51141,  0.51141,  0.51141,  0.51141,  0.51141]),
 'tr': array([ 0.32001,  0.32001,  0.32001,  0.32001,  0.32001,  0.32001]),
 'v': array([ 1.22063,  1.36224,  1.49704,  1.60176,  1.72381,  1.76406], dtype=float32),
 'v_0': 1.2206296380937256,
 'v_100': 1.7640615823592622,
 'v_20': 1.3622358968043313,
 'v_40': 1.4970380849011338,
 'v_60': 1.6017636718723776,
 'v_80': 1.7238067015995366,
 'xb': array([ 3.80715,  3.80715,  3.80715,  3.80715,  3.80715,  3.80715])}

In [200]:
finfo

a           0.51141
chi       0.0012979
cnvrg          True
ndata            16
nfev            177
nvary             6
tr          0.32001
v_0          1.2206
v_100        1.7641
v_20         1.3622
v_40          1.497
v_60         1.6018
v_80         1.7238
xb           3.8071
df               10
rchi     0.00012979
logp        -143.19
AIC         -131.19
BIC         -138.63
dtype: object

In [186]:
finfo = finfolist[np.argmin(aics)]

In [187]:
finfo.to_csv("xpro_v_bestfit.csv")

In [181]:
aics.min()

-131.19292667291396

In [210]:
good_basin_params[np.argmin(aics)]

{'a': 0.51141400553255789,
 'tr': 0.32001314851667217,
 'v': 1.5185917057414291,
 'xb': 3.8071450802621083}

In [95]:
mv.opt.basins

AttributeError: 'Optimizer' object has no attribute 'basins'

In [82]:
mv.opt.basins_popt

[{'a': 0.55462858703181417,
  'tr': 0.26398651103596854,
  'v': 1.7673282483493904,
  'xb': 1.3401673471562019},
 {'a': 0.17201215725501884,
  'tr': 0.43329276092854546,
  'v': 1.2841073233875073,
  'xb': 3.7372332816408869}]

In [81]:
mv.flat_popt

{'a': array([ 0.17281]),
 'tr': array([ 0.43397]),
 'v': array([ 1.27777]),
 'xb': array([ 3.75511])}

In [80]:
mv.opt.basin_decision

'found global miniumum new: fmin=0.000099364; norig= 0.000254)'

In [26]:

mv.opt.basins

[0.00044805596740578834, 0.088714205214259267]

In [34]:

mv.opt.basins

[0.0013064018956089945, 0.28646659807077635]

In [96]:
mv.fitinfo

a           0.17201
chi       0.0047582
cnvrg          True
ndata            16
nfev           2358
nvary             6
tr          0.43329
v_0         0.88325
v_100        1.6125
v_20        0.99207
v_40         1.2072
v_60         1.3499
v_80         1.5435
xb           3.7372
df               10
rchi     0.00047582
logp        -122.41
AIC         -110.41
BIC         -117.84
dtype: object

In [27]:
mv.opt.basins_popt

[{'a': 0.51016066165044993,
  'tr': 0.27860619645820422,
  'v': 1.7283025570538106,
  'xb': 1.4078975403059684},
 {'a': 0.29266157500660589,
  'tr': 0.31411670241855211,
  'v': 0.97796140068505277,
  'xb': 4.0352163020078144}]

In [35]:
mv.opt.basins_popt

[{'a': 0.27621675678541591,
  'tr': 0.40127391703820292,
  'v': 1.7443969456408273,
  'xb': 1.5166260083689638},
 {'a': 0.20188696340928183,
  'tr': 0.33147127742948851,
  'v': 1.368240896469221,
  'xb': 3.665310793757258}]

In [226]:
mtr.flat_fits

array([ 0.46519,  0.51657,  0.52957,  0.53657,  0.54457,  0.54957])

In [13]:
mv.opt.basins_popt

[{'a': 0.55007398002696273,
  'tr': 0.24675438885453144,
  'v': 1.6926394016790585,
  'xb': 1.5592374417709391},
 {'a': 0.36424027809315812,
  'tr': 0.36670680171140724,
  'v': 1.5230483046560184,
  'xb': 3.6088743279051378}]

In [221]:
mv.fits

array([ 0.93337,  0.76411,  0.55762,  0.35654,  0.11765,  0.09784,
        0.4965 ,  0.5135 ,  0.5245 ,  0.5355 ,  0.5475 ,  0.5235 ,
        0.5355 ,  0.5425 ,  0.5475 ,  0.5525 ])

In [208]:
ma.fitinfo

NameError: name 'ma' is not defined

In [209]:
mx.flat_popt
#mx.flat_fitinfo

NameError: name 'mx' is not defined

In [42]:
mvtr.opt.basin_decision

'found global miniumum new: fmin=0.000300352; norig= 0.002184)'

In [87]:
vinits = {'a': 0.51016066165044993,
  'tr': 0.27860619645820422,
  'v': 1.7283025570538106,
  'xb': 1.4078975403059684}
vinits={'a': array([ 0.47969]),
 'tr': array([ 0.27451]),
 'v': array([ 1.05802]),
 'xb': array([ 3.79324])}
vinits={'a':0.47594, 
        'tr':0.2815, 
        'v':1.6128, 
        'xb':1.483}
vinits={'a': 0.17201215725501884,
  'tr': 0.43329276092854546,
  'v': 1.2841073233875073,
  'xb': 3.7372332816408869}

In [88]:
vinits

{'a': 0.17201215725501884,
 'tr': 0.43329276092854546,
 'v': 1.2841073233875073,
 'xb': 3.737233281640887}

In [100]:
mv.flat_popt=vinits
mv.flat_popt

{'a': 0.5101606616504499,
 'tr': 0.2786061964582042,
 'v': 1.7283025570538106,
 'xb': 1.4078975403059684}

In [89]:
mv.flat_popt=vinits

In [101]:
mv.optimize(stage='conditional', multiopt=True, inits=vinits)

{'a': 0.5101606616504499, 'xb': 1.4078975403059684, 'tr': 0.2786061964582042, 'v': 1.7283025570538106}
basinhopping step 0: f 0.237306
basinhopping step 1: f 0.24438 trial_f 0.24438 accepted 1  lowest_f 0.237306
basinhopping step 2: f 0.233828 trial_f 0.233828 accepted 1  lowest_f 0.233828
found new global minimum on step 2 with function value 0.233828
basinhopping step 3: f 0.0842588 trial_f 0.0842588 accepted 1  lowest_f 0.0842588
found new global minimum on step 3 with function value 0.0842588
basinhopping step 4: f 0.212616 trial_f 0.212616 accepted 1  lowest_f 0.0842588
basinhopping step 5: f 0.149593 trial_f 0.149593 accepted 1  lowest_f 0.0842588
basinhopping step 6: f 0.116561 trial_f 0.116561 accepted 1  lowest_f 0.0842588
basinhopping step 7: f 0.0606814 trial_f 0.0606814 accepted 1  lowest_f 0.0606814
found new global minimum on step 7 with function value 0.0606814
basinhopping step 8: f 0.132925 trial_f 0.132925 accepted 1  lowest_f 0.0606814
basinhopping step 9: f 0.241508

In [52]:
mv.flat_popt

{'a': 0.47969,
 'tr': 0.27451,
 'v': array([ 0.74956,  0.90685,  1.031  ,  1.11662,  1.25574,  1.28095]),
 'xb': 3.79324}

In [ ]:
m.data

In [72]:
prodata=mv.data.copy()

In [74]:
prodata['r'] = prodata.response.copy()

prodata.ix[(prodata['rt']>.555), 'r']=0
prodata['response']=prodata.r.copy()
#prodata.groupby('pGo').mean().r

In [77]:
vis.plot_fits(mv.avg_y, mv.fits, kind='pro', cdf=True, data=mv.data)

In [65]:
mv.flat_popt

{'a': 0.47594,
 'tr': 0.2815,
 'v': array([ 1.58054,  1.50748,  1.58395,  1.67238,  1.68923,  1.81712]),
 'xb': 1.483}

In [59]:
mv.flat_fitinfo

a           0.47743
chi      0.00019065
cnvrg          True
ndata             6
nfev            126
nvary             4
tr          0.28159
v            1.6101
xb           1.4972
df                2
rchi     9.5323e-05
logp        -55.549
AIC         -47.549
BIC         -52.371
dtype: object

In [92]:
mv.flat_fitinfo

a           0.17281
chi      0.00011243
cnvrg          True
ndata             6
nfev            108
nvary             4
tr          0.43397
v            1.2778
xb           3.7551
df                2
rchi     5.6214e-05
logp        -58.718
AIC         -50.718
BIC          -55.54
dtype: object

In [50]:
mv.flat_fitinfo

a           0.47743
chi      0.00019065
cnvrg          True
ndata             6
nfev            126
nvary             4
tr          0.28159
v            1.6101
xb           1.4972
df                2
rchi     9.5323e-05
logp        -55.549
AIC         -47.549
BIC         -52.371
dtype: object

In [60]:
mv.fitinfo

a          0.47594
chi       0.004823
cnvrg         True
ndata           16
nfev           243
nvary            6
tr          0.2815
v_0         1.3605
v_100        1.835
v_20        1.4718
v_40        1.5806
v_60        1.6674
v_80        1.7957
xb           1.483
df              10
rchi     0.0004823
logp       -122.19
AIC        -110.19
BIC        -117.63
dtype: object

In [49]:
mv.fitinfo

a           0.47969
chi       0.0024194
cnvrg          True
ndata            16
nfev            160
nvary             6
tr          0.27451
v_0         0.74578
v_100        1.2828
v_20        0.90025
v_40         1.0281
v_60         1.1172
v_80          1.249
xb           3.7932
df               10
rchi     0.00024194
logp        -133.23
AIC         -121.23
BIC         -128.66
dtype: object

In [93]:
mv.fitinfo

a           0.17201
chi       0.0047582
cnvrg          True
ndata            16
nfev           2358
nvary             6
tr          0.43329
v_0         0.88325
v_100        1.6125
v_20        0.99207
v_40         1.2072
v_60         1.3499
v_80         1.5435
xb           3.7372
df               10
rchi     0.00047582
logp        -122.41
AIC         -110.41
BIC         -117.84
dtype: object

In [58]:
mv.fitinfo

a          0.47594
chi       0.004823
cnvrg         True
ndata           16
nfev           243
nvary            6
tr          0.2815
v_0         1.3605
v_100        1.835
v_20        1.4718
v_40        1.5806
v_60        1.6674
v_80        1.7957
xb           1.483
df              10
rchi     0.0004823
logp       -122.19
AIC        -110.19
BIC        -117.63
dtype: object

In [46]:
mv.fitinfo.to_csv("PRODRIFT1.csv")

In [48]:
mv.fits

array([ 0.96098,  0.78091,  0.53301,  0.35114,  0.10744,  0.09604,
        0.50051,  0.51651,  0.52751,  0.53651,  0.54751,  0.51951,
        0.53151,  0.54151,  0.54551,  0.55251])

In [47]:
mv.flat_fits

array([ 0.48019,  0.51759,  0.53159,  0.53959,  0.54659,  0.55259])

In [102]:
mv.fitinfo

a          0.51016
chi       0.013822
cnvrg        False
ndata           16
nfev          3279
nvary            6
tr         0.27861
v_0         1.3078
v_100       1.8963
v_20        1.5382
v_40        1.6888
v_60        1.7631
v_80        1.8503
xb          1.4079
df              10
rchi     0.0013822
logp       -105.34
AIC        -93.345
BIC        -100.78
dtype: object

In [17]:
mvtr.fitinfo

a            0.36381
chi        0.0010015
cnvrg           True
ndata             16
nfev             287
nvary             12
tr_0         0.38167
tr_100       0.36103
tr_20        0.39122
tr_40        0.36513
tr_60        0.35786
tr_80         0.3855
v_0           1.3708
v_100         1.7399
v_20           1.685
v_40          1.4892
v_60          1.5205
v_80          1.9959
xb             3.659
df                 4
rchi      0.00025038
logp         -132.68
AIC          -108.68
BIC          -127.42
dtype: object

In [80]:
m.avg_y

array([ 0.93996,  0.79037,  0.54775,  0.33996,  0.11803,  0.08139,
        0.50343,  0.53158,  0.54094,  0.54427,  0.54527,  0.53376,
        0.54393,  0.5447 ,  0.54517,  0.54533])

In [90]:
pro.query('choice=="go"').rt.max()

0.5599845999999999

In [ ]:
from sklearn.neighbors.KernelDensity 

In [113]:
analyze=reload(analyze)

In [125]:
from sklearn.neighbors import KernelDensity
kdefit = KernelDensity(kernel='gaussian', bandwidth=.01).fit(ma.fits[6:11])
samples = kdefit.score_samples(ma.fits[6:11][:,None])#.flatten()

ValueError: query data dimension must match training data dimension

In [123]:
samples

array([ 18.43116])

In [116]:
def kde_fit_quantiles(rtquants, nsamples=1000, bw=.01):
      """ takes quantile estimates and fits cumulative density function
      returns samples to pass to sns.kdeplot()
      """
      kdefit = KernelDensity(kernel='linear', bandwidth=bw).fit(rtquants)
      samples = kdefit.sample(n_samples=nsamples).flatten()
      return samples

In [131]:
dvg = m.simulate(analyze=False)

In [137]:
p = m.opt.simulator.vectorize_params(m.inits)
gacc, hi, lo = analyze_pro_data(sim, dvg, m.inits)
hi
def analyze_pro_data(sim, dvg, p):
      gdec = sim.resp_up(dvg, p['a'])
      rt = sim.RT(p['tr'], gdec)
      hi = hs(rt[3:])
      low = hs(rt[1:3])
      # Get response and stop accuracy information
      gacc = 1-np.where(rt<sim.tb, 1, 0)
      return [gacc, hi[~np.isnan(hi)], low[~np.isnan(low)]]


In [187]:
p = m.opt.simulator.vectorize_params(m.inits)
gacc, hi, lo = analyze_pro_data(sim, dvg, m.inits)

emp_kq = lambda rts: analyze.kde_fit_quantiles(mq(rts, prob=np.arange(0,1,.02)), bw=.01)
hiq = emp_kq(hi)
loq = emp_kq(lo)
hi_rts = m.data.query('response==1 & pGo>.5').rt.values
lo_rts = m.data.query('response==1 & pGo<.5').rt.values
dat_cq = emp_kq(hi_rts)
dat_cq = emp_kq(lo_rts)
m.simulator.tb
#sns.kdeplot(hiq, bw=.01)
#sns.kdeplot(dat_cq, bw=.01)
f, (ax1, ax2, ax3) = plt.subplots(1,3,figsize=(14, 5.5), sharey=False)
#axes, pp = vis.plot_data_dists(pro, kind='pro', cdf=False, axes=[ax1,ax2,ax3], data_type='real')
#shade=pp['shade']; lw=pp['lw']; ls=pp['ls']; alpha=pp['alpha']; bw=pp['bw']

dat_cq = emp_kq(hi_rts)
dat_eq = emp_kq(lo_rts)
sns.distplot(dat_cq, kde=False, color='k', norm_hist=True, ax=ax1, bins=50)
sns.distplot(dat_eq, kde=False, color='k', norm_hist=True, ax=ax2, bins=50)

sns.distplot(hiq, kde=False, color=colors[0], norm_hist=True, ax=ax1, bins=18)
sns.distplot(loq, kde=False, color=colors[1], norm_hist=True, ax=ax2, bins=18)
ax1.set_xlim(.45, .6)
ax2.set_xlim(.45, .6)
for ax in axes:
      if ax.is_last_col():
            continue
      ax.set_xlim(.45, .6)




In [130]:
vis.plot_fits(ma.avg_y, ma.fits, kind='pro', data=m.data, cdf=False)

In [77]:
ma.fits

array([ 0.93878,  0.79712,  0.57383,  0.34094,  0.17047,  0.10684,
        0.50398,  0.51898,  0.52998,  0.53998,  0.54998,  0.52798,
        0.53798,  0.54298,  0.54898,  0.55398])

In [76]:
ma.fitinfo

a_0         0.43677
a_100        0.2831
a_20        0.39807
a_40        0.35938
a_60        0.32689
a_80        0.29366
chi       0.0050086
cnvrg         False
ndata            16
nfev           3293
nvary             6
tr          0.34498
v            1.1852
xb           4.0508
df               10
rchi     0.00050086
logp        -121.59
AIC         -109.59
BIC         -117.02
dtype: object

In [49]:
mx.fitinfo.to_csv('xpro_tr_final_fits.csv')

In [12]:

m = build.Model(data=pro, kind='xpro', depends_on={'v':'pGo'}, inits=inits)
m.make_optimizer()
m.optimize(stage='flat', multiopt=True)

basinhopping step 0: f 0.108714
basinhopping step 1: f 0.269723 trial_f 0.269723 accepted 1  lowest_f 0.108714
basinhopping step 2: f 0.161829 trial_f 0.161829 accepted 1  lowest_f 0.108714
basinhopping step 3: f 0.259388 trial_f 0.259388 accepted 1  lowest_f 0.108714
basinhopping step 4: f 0.228015 trial_f 0.228015 accepted 1  lowest_f 0.108714
basinhopping step 5: f 0.135389 trial_f 0.135389 accepted 1  lowest_f 0.108714
basinhopping step 6: f 0.254996 trial_f 0.254996 accepted 1  lowest_f 0.108714
basinhopping step 7: f 0.320869 trial_f 0.320869 accepted 1  lowest_f 0.108714
basinhopping step 8: f 0.2924 trial_f 0.2924 accepted 1  lowest_f 0.108714
basinhopping step 9: f 0.334412 trial_f 0.334412 accepted 1  lowest_f 0.108714
adaptive stepsize: acceptance rate 0.900000 target 0.500000 new stepsize 0.0555556 old stepsize 0.05
basinhopping step 10: f 0.371264 trial_f 0.371264 accepted 1  lowest_f 0.108714
basinhopping step 11: f 0.385591 trial_f 0.385591 accepted 1  lowest_f 0.108714


In [13]:
mvtr.optimize(stage  ='conditional', multiopt=True)

basinhopping step 0: f 0.78673
basinhopping step 1: f 0.650493 trial_f 0.650493 accepted 1  lowest_f 0.650493
found new global minimum on step 1 with function value 0.650493
basinhopping step 2: f 0.823418 trial_f 0.823418 accepted 1  lowest_f 0.650493
basinhopping step 3: f 0.651832 trial_f 0.651832 accepted 1  lowest_f 0.650493
basinhopping step 4: f 0.518028 trial_f 0.518028 accepted 1  lowest_f 0.518028
found new global minimum on step 4 with function value 0.518028
basinhopping step 5: f 0.32507 trial_f 0.32507 accepted 1  lowest_f 0.32507
found new global minimum on step 5 with function value 0.32507
basinhopping step 6: f 0.39338 trial_f 0.39338 accepted 1  lowest_f 0.32507
basinhopping step 7: f 0.460583 trial_f 0.460583 accepted 1  lowest_f 0.32507
basinhopping step 8: f 0.609261 trial_f 0.609261 accepted 1  lowest_f 0.32507
basinhopping step 9: f 0.719134 trial_f 0.719134 accepted 1  lowest_f 0.32507
adaptive stepsize: acceptance rate 0.900000 target 0.500000 new stepsize 0.0

In [41]:
m.opt.basin

{'interval': 10,
 'maxiter': 20,
 'method': 'TNC',
 'ninits': 2,
 'niter': 500,
 'nsuccess': 20,
 'stepsize': 0.05,
 'tol': 0.001}

In [18]:
mvtr.fitinfo

a            0.36381
chi        0.0010015
cnvrg           True
ndata             16
nfev             287
nvary             12
tr_0         0.38167
tr_100       0.36103
tr_20        0.39122
tr_40        0.36513
tr_60        0.35786
tr_80         0.3855
v_0           1.3708
v_100         1.7399
v_20           1.685
v_40          1.4892
v_60          1.5205
v_80          1.9959
xb             3.659
df                 4
rchi      0.00025038
logp         -132.68
AIC          -108.68
BIC          -127.42
dtype: object

In [5]:
iv = {'v':array([ 1.41106,  1.56252,  1.68275,  1.76071,  1.87995,  1.92475]), 'a': 0.487226, 'xb':   1.563474, 'tr':   0.292126}
ivtr = {'a': 0.06720971, 'xb': 1.467605,  'v':array([ 0.83108,  0.97048,  0.96678,  0.97912,  0.93224,  1.07883]), 'tr':array([ 0.51509,  0.50619,  0.49248,  0.47988,  0.45145,  0.46361])}
itr = {'a': 0.62868, 'v': 1.421123, 'xb': 0.640829, 'tr':array([ 0.18203,  0.16131,  0.13355,  0.11741,  0.08473,  0.07697])}
ia = {'a':array([ 0.37922,  0.34356,  0.30503,  0.28076,  0.24567,  0.23642]), 'xb': 0.9136456, 'v': 1.127346, 'tr': 0.2997148}
ixb={'a': 0.48158, 'xb': array([ 0.04638,  0.1547 ,  0.37575,  0.53875,  1.29523,  1.29254]), 'tr':0.27438, 'v': 1.54521}


names = ['v', 'tr', 'a', 'xb']
inits_list = [iv, itr, ia, ixb]
for i, idc in enumerate(inits_list):
      idc[names[i]] = np.mean(idc[names[i]])

ivtr['v']=np.mean(ivtr['v'])
ivtr['tr']=np.mean(ivtr['tr'])
inits_list.append(ivtr)

In [6]:
parameter = 'a'
depends_on = {parameter:'pGo'}
finfo_list, yhat_list = [], []
d = '/'.join(['FinalPro', parameter])
if not os.path.isdir(pth+d):
      os.mkdir(pth+d)
os.chdir(pth+d)

finfo_list, yhat_list = [], []

In [8]:
for i in range(20):
      xinits_list = [dict(deepcopy(xinit)) for xinit in inits_list]
      for xi in xinits_list:
            model = build.Model(data=prodata, kind='xpro', inits=xi, depends_on=depends_on)
            model.make_optimizer(tol=1.e-5, multiopt=True, maxfev=500)
            opt=model.opt
            opt.make_simulator()
            xi = model.__nudge_params__(xi)
            ydata, ywts = model.avg_y, model.avg_wts
            # STAGE 3 (Final Simplex)
            yhat, finfo, xiv = opt.gradient_descent(y=ydata, wts=ywts, inits=xi, is_flat=False)
            finfo_list.append(finfo)
            yhat_list.append(yhat)

Optimization terminated successfully.
         Current function value: 0.000009
         Iterations: 103
         Function evaluations: 227
Optimization terminated successfully.
         Current function value: 0.000006
         Iterations: 99
         Function evaluations: 221
Optimization terminated successfully.
         Current function value: 0.000004
         Iterations: 85
         Function evaluations: 199
Optimization terminated successfully.
         Current function value: 0.000005
         Iterations: 89
         Function evaluations: 210
Optimization terminated successfully.
         Current function value: 0.000008
         Iterations: 120
         Function evaluations: 302
Optimization terminated successfully.
         Current function value: 0.000012
         Iterations: 86
         Function evaluations: 208
Optimization terminated successfully.
         Current function value: 0.000005
         Iterations: 98
         Function evaluations: 229
Optimization terminated s

In [9]:
dfx = pd.DataFrame([fi.T for fi in finfo_list])
dff = dfx[['cnvrg', 'logp', 'chi', 'rchi', 'AIC', 'BIC', 'a_0', 'a_20', 'a_40', 'a_60', 'a_80',  'a_100', 'v', 'tr', 'xb']]

dff.to_csv('xpro_a_bootinfo.csv', index=False)
yhatdf = pd.DataFrame(np.asarray(yhat_list))
yhatdf.to_csv('xpro_a_bootfits.csv', index=False)